"""
Batch 4 append script — introduces simplify_request category (ELI5 pattern).
Composition:
  email_draft: 14
  email_refine: 14
  simplify_request: 10 (NEW)
  concept_explain: 4
  decision_advice: 4
  casual_reply: 2
  short_explain: 2
"""

import json
from pathlib import Path
from collections import Counter

ROWS = [
    # ============ SIMPLIFY_REQUEST (10) ============
    {
        "context": "simplify_request", "topic_area": "general_tech",
        "prompt": "Can you explain recursion in programming like I'm a beginner? I keep reading definitions and they don't click.",
        "rejected": "## Recursion Explained Simply 🔄\n\n**In simple terms:** Recursion is when a function calls itself.\n\n### Key Concepts:\n- **Base case:** The stopping condition\n- **Recursive case:** Where the function calls itself\n- **Stack:** Where function calls are tracked\n\n### Simple Example (Factorial):\n```python\ndef factorial(n):\n    if n == 0:  # base case\n        return 1\n    return n * factorial(n - 1)  # recursive case\n```\n\n### Step-by-Step Breakdown:\n1. Call `factorial(3)`\n2. It calls `factorial(2)`\n3. Which calls `factorial(1)`\n4. Which calls `factorial(0)` (base case → returns 1)\n5. Returns multiply back up: 1 → 1 → 2 → 6\n\n### Common Use Cases:\n- ✅ Tree traversal\n- ✅ Fibonacci sequence\n- ✅ Divide-and-conquer algorithms\n- ✅ Backtracking\n\n### Watch Out For:\n- 🔴 Stack overflow (missing base case)\n- 🔴 Performance (without memoization)\n\n### Simple Recap:\nRecursion = function calling itself + base case to stop.",
        "chosen": "The clearest way I've seen it explained: imagine you're standing in a long line of people, and you want to know your position from the front. You can't see the front, so you turn to the person in front of you and ask, 'what's your position?' That person doesn't know either, so they ask the person in front of them, and so on. Eventually someone at the very front says 'I'm first.' That answer travels back down the line — the second person now knows they're second, the third knows they're third, and eventually it gets back to you.\n\nThat's recursion. It's a function that handles a piece of the problem and then asks itself to handle the smaller remaining piece. It works because there's a stopping point — the person at the front of the line who actually knows the answer without having to ask anyone. In code, that stopping point is called the 'base case,' and forgetting it is what causes recursion to run forever and crash.\n\nThe usual mind-bending part is that the function calling itself feels like cheating — like it shouldn't work. But each call is solving a slightly smaller version of the same problem, until you hit something so small the answer is obvious."
    },
    {
        "context": "simplify_request", "topic_area": "general_tech",
        "prompt": "I keep hearing about blockchain. Can you explain it like I'm five? I don't get what the big deal is.",
        "rejected": "## Blockchain Explained Simply 🧱\n\n**Quick definition:** Blockchain is a distributed digital ledger that records transactions across many computers.\n\n### Core Concepts:\n- **Block:** A group of transactions\n- **Chain:** Blocks linked cryptographically\n- **Distributed:** Copy lives on many computers\n- **Immutable:** Can't be changed once written\n\n### How It Works (Simplified):\n1. Someone makes a transaction\n2. It gets bundled with others into a 'block'\n3. The block is verified by computers (miners/validators)\n4. Once verified, it's added to the chain\n5. The chain is updated everywhere\n\n### Why People Care:\n- ✅ No central authority\n- ✅ Tamper-resistant\n- ✅ Transparent\n- ✅ Trustless verification\n\n### Common Uses:\n- 💰 Cryptocurrencies (Bitcoin, Ethereum)\n- 📜 Smart contracts\n- 🏷️ NFTs\n- 🔗 Supply chain tracking\n\n### Simple Analogy:\nThink of it like a shared Google Doc that everyone can see and add to, but no one can edit or delete old entries.\n\n### Verdict:\nUseful for trustless coordination — overhyped for many other use cases.",
        "chosen": "Imagine a notebook that you and 10,000 of your friends all share. Every time anyone wants to write something in the notebook, they shout it out to the whole group. If most of the group agrees the entry looks legitimate, everyone writes it down at the same time, in the same place, in their own copy. Once it's written, nobody can erase it or change it — partly because there are 10,000 copies, and partly because each new page is glued to the previous one in a way that ripping out a page would be obvious.\n\nThat's basically blockchain. The 'notebook' is the chain, the 'entries' are transactions, and the 'thousands of friends' are all the computers running the network. The whole point is that you don't need a bank or a government or any single authority to keep the records honest — the records are honest because everyone has a copy and the copies have to agree.\n\nWhy people care: there are a few situations where not needing a trusted middleman is genuinely valuable — sending money across borders without going through a bank, for instance. Whether that justifies the hype around everything else that's been built on top of it (NFTs, half the crypto projects) is a much more honest debate. But the core idea — a record nobody owns and nobody can quietly edit — is real and clever."
    },
    {
        "context": "simplify_request", "topic_area": "general_tech",
        "prompt": "Explain encryption to me without the math jargon — I just want to understand what's actually happening.",
        "rejected": "## Encryption Explained Simply 🔐\n\n**Plain definition:** Encryption transforms readable data into scrambled data that only authorized parties can unscramble.\n\n### The Two Types:\n\n**1. Symmetric Encryption:**\n- Same key encrypts and decrypts\n- Faster\n- Example: AES\n\n**2. Asymmetric Encryption:**\n- Two keys: public + private\n- Slower but more flexible\n- Example: RSA\n\n### Common Use Cases:\n- ✅ HTTPS (web browsing)\n- ✅ Messaging apps (WhatsApp, Signal)\n- ✅ File storage\n- ✅ Cryptocurrency\n\n### Simple Step-By-Step (Symmetric):\n1. Start with message\n2. Apply key + algorithm\n3. Get unreadable ciphertext\n4. Send safely\n5. Recipient uses same key to decrypt\n\n### Key Vocabulary:\n| Term | Meaning |\n|------|---------|\n| Plaintext | Readable message |\n| Ciphertext | Scrambled message |\n| Key | Secret used to scramble/unscramble |\n| Algorithm | The math that does the scrambling |\n\n### Verdict:\nEncryption is fundamental to modern internet security!",
        "chosen": "The cleanest way to picture it: imagine you and a friend invent a secret code, where every letter of the alphabet gets replaced with a different one according to a rule only the two of you know. You write a message using your code, and even if a stranger intercepts the paper, all they see is gibberish. Your friend, knowing the rule, can decode it back to the original message.\n\nThat's basically encryption. You take readable text, you scramble it according to a mathematical rule, and out comes something that looks like random nonsense. Anyone who doesn't know the rule sees only the nonsense. Anyone who does know the rule can recover the original.\n\nThe 'rule' is called a key. Modern encryption uses keys so large that even with the world's fastest computers, you can't guess them — that's where all the scary math comes in, but you don't really need to understand the math to understand what encryption is doing.\n\nWhen you see the little padlock in your browser, encryption is what's making it safe to type your bank password into the website. Your computer and the bank's server have quietly agreed on a key, and everything you send is scrambled with it. Anyone snooping on the connection between you sees only gibberish."
    },
    {
        "context": "simplify_request", "topic_area": "general_tech",
        "prompt": "Can you explain Big O notation like I'm not a CS major? I've seen O(n) and O(log n) but never understood what they mean.",
        "rejected": "## Big O Notation Made Simple 📊\n\n**Definition:** Big O describes how an algorithm's runtime grows with input size.\n\n### Common Complexities:\n\n| Notation | Name | Example |\n|----------|------|---------|\n| O(1) | Constant | Array lookup |\n| O(log n) | Logarithmic | Binary search |\n| O(n) | Linear | Loop through list |\n| O(n log n) | Linearithmic | Merge sort |\n| O(n²) | Quadratic | Nested loops |\n| O(2ⁿ) | Exponential | Recursive Fibonacci |\n\n### What 'n' Means:\n- The input size\n- e.g., length of array, # of items, etc.\n\n### Simple Explanations:\n\n**O(1) — Constant:**\n- Time doesn't change with input\n\n**O(n) — Linear:**\n- Time scales 1:1 with input\n\n**O(log n) — Logarithmic:**\n- Time grows slowly even as input doubles\n\n**O(n²) — Quadratic:**\n- Time grows quickly (often nested operations)\n\n### Why It Matters:\n- ✅ Predict performance at scale\n- ✅ Compare algorithm efficiency\n- ✅ Pass coding interviews\n\n### Verdict:\nMaster Big O and you'll write better, faster code!",
        "chosen": "Big O is just a way of describing how much slower a program gets as you give it more data. That's the whole concept. The reason it sounds intimidating is the funny notation.\n\nImagine you have a stack of phonebooks and you want to find a specific person.\n\nIf the books are unsorted, you have to flip through every page of every book until you find them. Doubling the number of books means doubling the work. That's **O(n)** — linear, work grows in step with the data.\n\nIf the books are sorted alphabetically, you can do something smarter: open to the middle, see if the name comes before or after, and cut the search in half. Then halve it again. With this method, doubling the number of books barely adds any work — you just need one more 'cut in half' step. That's **O(log n)** — logarithmic, very efficient.\n\nNow imagine for some reason, for every name in your book you have to compare it against every other name. With twice as many names, the work quadruples. That's **O(n²)** — quadratic, and the reason it scares senior engineers when they see it in real code.\n\nThe practical point of Big O is to predict whether your program will stay fast as the data grows. An O(n²) algorithm might run in a second on 1,000 items but take an hour on 100,000. An O(n log n) algorithm wouldn't notice the difference."
    },
    {
        "context": "simplify_request", "topic_area": "general_tech",
        "prompt": "Explain SQL joins to me simply — I always get inner/outer/left/right confused.",
        "rejected": "## SQL Joins Explained 🔗\n\n**Definition:** Joins combine rows from two tables based on a related column.\n\n### The Four Main Types:\n\n**1. INNER JOIN:**\n- Returns rows where there's a match in BOTH tables\n- Most common\n\n**2. LEFT (OUTER) JOIN:**\n- Returns ALL rows from left table\n- Matching rows from right (NULL if no match)\n\n**3. RIGHT (OUTER) JOIN:**\n- Returns ALL rows from right table\n- Matching rows from left (NULL if no match)\n\n**4. FULL (OUTER) JOIN:**\n- Returns ALL rows from BOTH tables\n- NULLs where no match\n\n### Visual (Venn-style):\n```\nINNER:    🟢🟢🟢 (just overlap)\nLEFT:     🟦🟢🟢 (all of left + overlap)\nRIGHT:    🟢🟢🟧 (all of right + overlap)\nFULL:     🟦🟢🟧 (everything)\n```\n\n### Quick Reference:\n| Need | Use |\n|------|-----|\n| Only matched rows | INNER |\n| All from one side | LEFT or RIGHT |\n| Everything | FULL |\n\n### Common Pitfall:\nLEFT JOIN ≠ LEFT OUTER JOIN. They're the same. Vocabulary is just confusing.\n\n### Verdict:\nMaster these and you'll handle 90% of SQL queries!",
        "chosen": "The easiest way to keep these straight is to think of two lists of people.\n\nList A is everyone who attended your wedding. List B is everyone you sent a thank-you card to. The two lists overlap, but not perfectly — maybe some people who came didn't get a card, and maybe some people got a card who didn't come.\n\nA **inner join** gives you only the people who appear in *both* lists — the ones who attended AND got a card. The overlap.\n\nA **left join** gives you everyone from List A (the attendees), and for each one, it tells you whether they got a card. Attendees who didn't get a card still show up — they just have a blank where the card info would go.\n\nA **right join** is the mirror image: everyone from List B (people you sent cards to), and for each one, whether they actually attended. People you sent a card to who skipped the wedding still show up.\n\nA **full outer join** is everyone in either list — every attendee and every card recipient, with blanks where someone is in only one of the two.\n\nThe 'left' and 'right' are just referring to the order you wrote the tables in your query. In practice you'll use INNER and LEFT 90% of the time. The mental model of 'two lists, what overlap do I want' is what really makes it click."
    },
    {
        "context": "simplify_request", "topic_area": "ml",
        "prompt": "Can you explain tokenization in LLMs in plain English? I've read about it but it never quite sticks.",
        "rejected": "## Tokenization in LLMs Explained 🔤\n\n**Definition:** Tokenization is the process of breaking text into smaller units (tokens) that the model can process.\n\n### Why Models Need Tokenization:\n- Models don't read raw text\n- They process numerical IDs\n- Tokens = the basic units\n\n### Common Approaches:\n\n**1. Word-level:**\n- Each word = one token\n- Issue: huge vocabulary\n\n**2. Character-level:**\n- Each character = one token\n- Issue: very long sequences\n\n**3. Subword (most common):**\n- Common pieces of words\n- Balance between vocab size and sequence length\n- Examples: BPE, WordPiece, SentencePiece\n\n### Example:\n- Text: 'tokenization'\n- Tokens: ['token', 'ization'] (BPE-style)\n\n### Why It Matters:\n- ✅ Affects context length\n- ✅ Affects model performance\n- ✅ Affects API costs (per token)\n\n### Common Tokenizers:\n| Model | Tokenizer |\n|-------|-----------|\n| GPT family | tiktoken (BPE) |\n| BERT | WordPiece |\n| Llama | SentencePiece |\n\n### Quick Facts:\n- ~4 chars ≈ 1 token (English)\n- ~750 words ≈ 1000 tokens\n\n### Verdict:\nTokenization is the bridge between text and the model's math!",
        "chosen": "An LLM doesn't actually 'see' words the way you do. Internally, it only works with numbers — so before any text reaches the model, it has to be chopped up into little pieces, and each piece replaced with a number. Those pieces are called tokens, and the chopping process is tokenization.\n\nThe interesting question is: what are the pieces? You could chop by whole words, but then 'running' and 'runs' look like totally unrelated things to the model, and rare words would never get learned well. You could chop by individual letters, but then the model has to learn that 'c-a-t' means cat from scratch every time, which wastes effort.\n\nWhat modern LLMs actually do is somewhere in between: they break text into common chunks. Common words like 'the' are one token. Less common words get split into pieces — 'tokenization' might become 'token' + 'ization,' for example. Made-up words and emoji get broken even smaller, sometimes down to individual characters.\n\nThis matters in practice for two reasons. First, the model has a maximum number of tokens it can handle at once (the 'context window'), and tokens aren't the same as words — a paragraph in English is roughly 1.3 tokens per word. Second, when you pay for API access, you're billed per token, so a really long prompt costs more than a short one."
    },
    {
        "context": "simplify_request", "topic_area": "data",
        "prompt": "Can you explain p-values and statistical significance like I'm a beginner? I see them in papers all the time and just nod along.",
        "rejected": "## P-Values & Statistical Significance — Simply 📊\n\n**Definition:** A p-value tells you the probability of seeing your data (or more extreme) IF the null hypothesis is true.\n\n### Key Vocabulary:\n- **Null hypothesis:** Default assumption (no effect)\n- **Alternative hypothesis:** What you're trying to show\n- **P-value:** Probability under the null\n- **Significance threshold:** Usually 0.05\n\n### How to Interpret:\n| P-value | What it means |\n|---------|---------------|\n| < 0.01 | Very strong evidence against null |\n| < 0.05 | Significant — reject null |\n| 0.05–0.10 | Borderline |\n| > 0.10 | Insufficient evidence |\n\n### Step-by-Step Process:\n1. State null hypothesis\n2. Collect data\n3. Calculate test statistic\n4. Compute p-value\n5. Compare to threshold (e.g., 0.05)\n6. Reject or fail to reject null\n\n### Common Misconceptions:\n- ❌ P-value is NOT probability null is true\n- ❌ P < 0.05 does NOT mean 'true'\n- ❌ Statistical significance ≠ practical significance\n\n### Verdict:\nP-values are useful but widely misunderstood — even by researchers!",
        "chosen": "The clearest way to think about this: imagine you flip a coin ten times and it comes up heads nine times. You'd be a little suspicious, right? Maybe the coin is rigged.\n\nThe p-value is the answer to: 'how likely is it I'd see something this extreme just by chance, if the coin is actually fair?' For nine heads out of ten flips of a fair coin, that probability turns out to be very small — about 1%. So you'd say there's strong evidence the coin isn't fair.\n\nThat's all a p-value is. It's a measure of 'how surprising is my result, assuming nothing weird is going on?' Small p-value = very surprising = probably something real. Big p-value = not surprising = could easily be chance.\n\nThe '0.05 threshold' for 'statistical significance' is an arbitrary line in the sand. It means: 'we'll call this real if the probability of seeing it by chance is less than 5%.' That number was picked by a statistician almost a century ago partly because it sounded reasonable, and the field has been arguing about it ever since.\n\nTwo things people get wrong that are worth knowing: a small p-value doesn't tell you the effect is *big* or *important*, just that it's probably real. And a result that *just* clears 0.05 should always be taken with some salt — there are lots of ways to accidentally fish for that result without realizing it."
    },
    {
        "context": "simplify_request", "topic_area": "general_tech",
        "prompt": "Explain DNS to me in simple terms — I know it has something to do with websites but I don't really get it.",
        "rejected": "## DNS Explained Simply 🌐\n\n**Definition:** DNS (Domain Name System) translates domain names into IP addresses.\n\n### Why It Exists:\n- Computers communicate using IP addresses (e.g., 142.250.190.46)\n- Humans prefer names (e.g., google.com)\n- DNS bridges this gap\n\n### How It Works (Simplified):\n1. You type `example.com` in browser\n2. Browser asks: 'What IP is this?'\n3. DNS server looks it up\n4. Returns IP address\n5. Browser connects to that IP\n\n### Key Components:\n- **DNS Resolver:** Your local query handler\n- **Root Servers:** Start of the chain\n- **TLD Servers:** Handle `.com`, `.org`, etc.\n- **Authoritative Servers:** Hold actual records\n\n### Simple Analogy:\nDNS is like a phonebook for the internet:\n- Names → phone numbers\n- Domain names → IP addresses\n\n### Common Record Types:\n| Type | Purpose |\n|------|---------|\n| A | Maps name to IPv4 |\n| AAAA | Maps name to IPv6 |\n| CNAME | Alias for another name |\n| MX | Mail server |\n| TXT | Arbitrary text |\n\n### Verdict:\nDNS is one of the internet's most essential — and quietly invisible — systems!",
        "chosen": "DNS is basically the phone book of the internet.\n\nHere's the thing: when you type 'google.com' into your browser, your computer doesn't actually know what 'google.com' is. Computers can only talk to other computers using numerical addresses — something like 142.250.190.46 — the same way phones can only call other phones using numbers, not names. So before your browser can do anything, it has to look up what number address 'google.com' lives at.\n\nDNS is the system that does that lookup. Your browser quietly asks a DNS server somewhere, 'hey, what's the address for google.com?', gets the number back, and then makes the actual connection using that number. All of this happens in a fraction of a second, every time you visit a website, and you never see any of it.\n\nThe reason it's worth understanding even at a high level is that when DNS breaks — and it does sometimes — websites stop loading even though nothing's wrong with the websites themselves. Your browser just can't find them anymore because the phone book lookup is failing. That's why 'try a different DNS server' is a common fix when the internet seems broken."
    },
    {
        "context": "simplify_request", "topic_area": "ml",
        "prompt": "I keep seeing 'embeddings' mentioned in ML stuff. Can you just explain what they are in plain terms?",
        "rejected": "## Embeddings Explained Simply 🔢\n\n**Definition:** Embeddings are dense vector representations of objects (words, sentences, images, etc.) in a continuous space where semantically similar items are close together.\n\n### Key Properties:\n- ✅ Fixed-size vectors (e.g., 768 dims)\n- ✅ Capture meaning, not just surface form\n- ✅ Enable similarity comparisons\n- ✅ Can be trained or pre-trained\n\n### Common Types:\n\n**1. Word Embeddings:**\n- Word2Vec, GloVe, FastText\n- Each word → one vector\n\n**2. Sentence Embeddings:**\n- SBERT, OpenAI embeddings\n- Whole sentence → one vector\n\n**3. Image Embeddings:**\n- CLIP, ResNet features\n- Image → vector\n\n### Why They Matter:\n- ✅ Semantic search\n- ✅ Recommendation systems\n- ✅ RAG for LLMs\n- ✅ Clustering / similarity\n\n### Simple Example:\nIn embedding space:\n- 'king' - 'man' + 'woman' ≈ 'queen'\n- 'cat' is closer to 'dog' than to 'car'\n\n### How They're Made:\n- Train a model on related/unrelated pairs\n- Adjust vectors so related items are close\n- Result: meaningful geometry\n\n### Verdict:\nEmbeddings are the foundation of modern semantic computing!",
        "chosen": "An embedding is just a list of numbers that represents the meaning of something.\n\nHere's the intuition. Suppose you wanted to teach a computer the difference between 'cat' and 'car.' You can't hand it the actual concepts — computers only deal in numbers. So instead, you give it a list of, say, 300 numbers for 'cat' and 300 numbers for 'car.' The clever part is that these numbers aren't random. They're chosen by a model that has read enormous amounts of text and figured out that 'cat' often appears near words like 'dog,' 'pet,' 'purr,' while 'car' appears near 'engine,' 'drive,' 'highway.' The model arranges the numbers so that the 'cat' list ends up close to the 'dog' list in some abstract geometric sense, and far from the 'car' list.\n\nThe magic is that once you've done this for every word, you can do *math* on meaning. You can ask 'what's closest to cat?' and get back 'dog,' 'kitten,' 'feline.' You can do the famous example: take the embedding for 'king,' subtract the embedding for 'man,' add 'woman,' and you land near 'queen.'\n\nThe same idea works for sentences, paragraphs, images, songs — anything where you can train a model to put similar things close together. That's why embeddings show up everywhere in modern ML: semantic search, recommendations, the way an LLM knows that 'how do I bake bread' and 'what's a good sourdough recipe' are asking about the same thing."
    },
    {
        "context": "simplify_request", "topic_area": "general_tech",
        "prompt": "Sorry, can you explain what an algorithm actually is? I know it sounds basic but I've never had a clean definition.",
        "rejected": "## What is an Algorithm? — Simply 🔧\n\n**Definition:** An algorithm is a step-by-step procedure for solving a problem or accomplishing a task.\n\n### Key Properties:\n- ✅ Well-defined steps\n- ✅ Finite (must end)\n- ✅ Deterministic (or stochastic, in modern variants)\n- ✅ Takes input, produces output\n\n### Everyday Examples:\n- 🍳 A recipe (cooking algorithm)\n- 📋 Assembly instructions\n- 🗺️ Driving directions\n- 🛒 Shopping list with order\n\n### In Computer Science:\n- Sorting algorithms (e.g., quicksort)\n- Search algorithms (e.g., binary search)\n- Pathfinding (e.g., Dijkstra)\n- Machine learning algorithms\n\n### Algorithm Components:\n| Part | Example |\n|------|---------|\n| Input | List of numbers |\n| Process | Sort them |\n| Output | Sorted list |\n\n### Why It Matters:\n- ✅ Foundation of computing\n- ✅ Determines efficiency\n- ✅ Key for problem-solving\n\n### Quick Tip:\nIf you can write it down as steps a friend could follow, you've described an algorithm!\n\n### Verdict:\nEverything from Google Search to your microwave runs on algorithms!",
        "chosen": "Not basic at all — most definitions you'll find are circular. Here's the simplest honest version: an algorithm is a recipe.\n\nIf you've ever followed a recipe for chocolate chip cookies — combine these ingredients in this order, bake at this temperature for this long, take them out when they look like this — you've followed an algorithm. The recipe takes an input (raw ingredients) and produces an output (cookies), using a series of clear steps that anyone following them would do the same way.\n\nIn computing, it's the same idea. An algorithm is a precise set of instructions for taking some input (a list of numbers, an image, a search query) and producing some output (a sorted list, a classification, search results). The steps have to be clear enough that a computer — which can't infer or improvise — knows exactly what to do at each point.\n\nWhen people talk about 'the YouTube algorithm' or 'the Google algorithm,' they mean the specific recipe those companies use to decide what to show you. When ML researchers talk about a 'sorting algorithm,' they mean a specific recipe for putting items in order. The word sounds technical but the concept is just: a written-down procedure for doing something."
    },

    # ============ EMAIL_DRAFT (14) ============
    # --- indian_corporate (5) ---
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email my manager Suresh that I'm going to be late by about an hour today — the metro is delayed.",
        "rejected": "Subject: Late Arrival Today — Metro Delays\n\nDear Suresh,\n\nGood morning. I am writing to inform you of a delay in my arrival today:\n\n**Reason:** Metro service is significantly delayed\n**Expected delay:** ~1 hour\n**New ETA:** [time]\n\n**What I'll do:**\n- Reach the office as soon as possible\n- Will catch up on missed time later in the day\n- Already responding to emails from the metro\n\n**Backup:**\n- Available on phone in the meantime\n- Can join any meetings remotely if needed\n\nKindly let me know if any urgent matters require attention.\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Running about an hour late — metro delay\n\nHi Suresh,\n\nThe metro is significantly delayed this morning — I'll be in about an hour late. Reachable on phone in the meantime if anything urgent comes up, and happy to join any meetings remotely from the station if needed.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email to my team proposing we change our weekly status meeting from Monday morning to Friday afternoon — Monday mornings are too packed with other things.",
        "rejected": "Subject: Proposal — Reschedule Weekly Status Meeting\n\nDear Team,\n\nI hope you are all doing well. I would like to propose a change to our weekly status meeting schedule.\n\n**Current:**\n- Day: Monday\n- Time: Morning\n\n**Proposed:**\n- Day: Friday\n- Time: Afternoon (3 PM IST suggested)\n\n**Rationale:**\n- Monday mornings are typically overcrowded with other syncs\n- Friday afternoon gives natural week-closure\n- Better for weekly retrospective discussions\n- Less rushed, more thoughtful conversations\n\n**Benefits:**\n- ✅ More focused discussions\n- ✅ Better preparation time\n- ✅ Natural weekly checkpoint\n- ✅ Frees Monday for execution\n\n**Action requested:**\n- Confirm if Friday 3 PM works for everyone\n- Flag any conflicts\n- Effective from next week if agreed\n\nLooking forward to your feedback.\n\nRegards,\n[Your Name]",
        "chosen": "Subject: Proposing we move our weekly status to Friday afternoon\n\nHi team,\n\nMonday mornings have been getting really crowded with other meetings, and I think our weekly status is suffering because of it. Could we move it to Friday afternoon — say 3 PM — instead? It would give us a natural week-closing checkpoint and free up Mondays for actually getting started on the week.\n\nLet me know if Friday 3 PM doesn't work and we'll figure something out.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email IT (Karthik) requesting VPN access for working from home starting next week — I have a pre-approved WFH from HR.",
        "rejected": "Subject: Request — VPN Access for Approved WFH\n\nDear Karthik,\n\nI hope you are doing well. I am writing to request VPN access setup.\n\n**Context:**\n- HR has approved my WFH starting next week\n- Need VPN to access internal systems\n\n**Details:**\n- Employee ID: [ID]\n- Department: [Dept]\n- Manager: [Manager name]\n- HR approval reference: [Reference number]\n\n**What I need:**\n- VPN client installation\n- Credentials\n- Brief setup guidance if needed\n\n**Timeline:**\n- Ideally before EOD Friday\n- WFH starts Monday\n\n**Available for:**\n- Pickup of laptop if needed\n- Brief calls for setup\n- Quick desk visit\n\nThanks in advance.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: VPN access setup for WFH from next week\n\nHi Karthik,\n\nMy WFH has been approved by HR starting next Monday, and I'll need VPN access set up before then. Could you help me get this sorted by EOD Friday? Employee ID is [ID] and the HR approval reference is [number].\n\nHappy to come by your desk whenever's convenient for the actual setup.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email asking my manager Deepa for a discussion about my upcoming quarterly bonus — I want to understand how it was calculated.",
        "rejected": "Subject: Request for Discussion — Quarterly Bonus\n\nDear Deepa,\n\nI hope you are doing well. I would like to request some of your time for a discussion regarding the upcoming quarterly bonus.\n\n**What I'd like to discuss:**\n1. How the bonus amount was calculated\n2. Performance components considered\n3. Comparison with prior quarters\n4. Areas for improvement going forward\n\n**Context:**\n- Want to understand the framework\n- Use insights for future planning\n- Align on expectations\n\n**Logistics:**\n- 30 minutes should suffice\n- Any time convenient for you\n- This week or next preferred\n\nLooking forward to your response.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: Quick discussion about the upcoming quarterly bonus?\n\nHi Deepa,\n\nCould we find 30 minutes this week or next to discuss the upcoming quarterly bonus? I'd like to understand how it was calculated and what components factored in — not to push back, just to understand the framework better so I know what to focus on going forward.\n\nHappy to fit your calendar.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email my team announcing an upcoming knowledge transfer session next week — I'm leaving the project in two weeks and want to make sure they have what they need.",
        "rejected": "Subject: Upcoming Knowledge Transfer Session — Next Week\n\nDear Team,\n\nAs you may already know, I will be transitioning off this project in 2 weeks. To ensure a smooth handover, I would like to schedule a knowledge transfer session.\n\n**Session details:**\n- **When:** Next week, [day], [time]\n- **Duration:** 90 minutes\n- **Format:** In-person + video for remote folks\n- **Location:** [room name]\n\n**Topics covered:**\n1. **Project overview & current status**\n2. **Architecture & system design**\n3. **Key contacts and stakeholders**\n4. **Open items and known issues**\n5. **Recommendations for the next person**\n\n**What you should do:**\n- Block your calendars\n- Review any prep material I'll share beforehand\n- Come with questions\n- Record the session for future reference\n\n**Materials I'll share:**\n- Handover document (this week)\n- Slide deck (day before)\n- Access permissions list\n\nPlease confirm your attendance.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: KT session next week before I transition off the project\n\nHi team,\n\nSince I'm rolling off this project in two weeks, I'd like to do a knowledge transfer session next week — let's plan for 90 minutes, [day] at [time]. I'll cover the current state of the project, the architecture, key contacts, and the open issues that need attention going forward.\n\nI'll share a handover document a few days before so you can come prepared with questions. Please block your calendars and let me know if the time doesn't work for anyone critical.\n\nThanks,\n[Your Name]"
    },
    # --- us_tech_casual (5) ---
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email my manager Erin asking if I can attend the NeurIPS conference next December — it's expensive but very relevant to my work.",
        "rejected": "Subject: Request — Attending NeurIPS This December\n\nHi Erin,\n\nWanted to float a learning-and-development request:\n\n**Conference:** NeurIPS\n**Dates:** December [dates]\n**Location:** [city]\n\n**Why I want to go:**\n1. **Directly relevant** to my current work\n2. **Network exposure** to leading ML researchers\n3. **Specific sessions** aligned with our roadmap\n4. **Bring back insights** for the team\n\n**Estimated cost:**\n- Registration: $[X]\n- Travel + Accommodation: $[Y]\n- Total: $[Z]\n\n**What I'll commit to in return:**\n- Detailed trip report\n- Internal talk for the team on key takeaways\n- Recommendations for follow-up actions\n\n**Budget considerations:**\n- Within typical L&D allocation\n- Will look for early-bird pricing\n\nHappy to discuss further.\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Want to attend NeurIPS this December?\n\nHi Erin,\n\nCould I attend NeurIPS this December? It's directly relevant to the work I'm doing on [project], and there are a handful of sessions I'd genuinely learn a lot from. Total cost would be around $[Z] including travel.\n\nIn return I'd do a detailed writeup and a team talk on the most relevant takeaways. Happy to talk through it if you want more detail.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email politely rejecting an internal opportunity my director offered me — it's a great role but not what I want right now (I want to stay technical).",
        "rejected": "Subject: Re: Internal Opportunity — Heartfelt Thanks but Declining\n\nHi [Director],\n\nFirst, thank you so much for thinking of me for this opportunity.\n\n**Why I'm declining:**\n- Want to stay technical/hands-on for now\n- The role is more management-leaning\n- Not the right fit for my current career stage\n\n**What I want to be clear about:**\n- ✅ I deeply appreciate being considered\n- ✅ I respect the role and the team\n- ✅ This is not about the role itself — it's a great opportunity\n- ✅ Just not the right fit for me right now\n\n**What I'd love:**\n- To continue having conversations about my growth\n- To revisit similar opportunities when I'm ready\n- To find ways to contribute beyond my current scope while staying technical\n\nThank you again for the consideration — it means a lot.\n\nBest,\n[Your Name]",
        "chosen": "Subject: Re: the [role] opportunity\n\nHi [Director],\n\nThank you for thinking of me — that genuinely means a lot. After thinking it over, I'm going to pass on this one. It's a great role, but I want to stay technical for at least another year or two before moving toward something more management-leaning, and I'd rather not take a step I'm not fully bought into.\n\nI'd love to stay on your radar for future opportunities, and I'm always open to taking on more scope in technical directions if anything comes up.\n\nThanks again,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email the team announcing we have to cancel the offsite scheduled for next month due to budget constraints. Want to be honest without making it sound dramatic.",
        "rejected": "Subject: Offsite Cancelled — Update\n\nHi team,\n\nWanted to share some news on next month's offsite:\n\n**Status:** Cancelled\n**Reason:** Budget constraints\n**Decision finalized:** [date]\n\n**Why we made this call:**\n- ❌ Budget couldn't be confirmed for Q[X]\n- ❌ Pushing it didn't make sense given uncertainty\n- ❌ Better to cancel cleanly than half-do it\n\n**What we'll do instead:**\n- 🍕 Team lunch next month (smaller scope)\n- 📅 Revisit Q[next] when budget is clearer\n- 💬 Open to ideas for low-cost team time\n\n**How I'm feeling about it:**\n- Genuinely disappointed\n- But the right call given the situation\n- Will make next one count\n\nThanks for understanding. Open to questions or thoughts.\n\n[Your Name]",
        "chosen": "Subject: Offsite is cancelled — quick honest update\n\nHi team,\n\nUnfortunately we've had to cancel next month's offsite due to budget constraints — not a decision I love, but the right call given where things are. I'd rather cancel cleanly now than try to half-do it.\n\nWe'll do something smaller in the meantime (probably a team lunch) and revisit a proper offsite when there's more budget clarity next quarter.\n\nIf anyone has ideas for low-cost ways to do some team time in the next few weeks, I'm all ears.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email pinging design (Maya) about the mockups they owe us — they were supposed to be ready three days ago and we're blocked.",
        "rejected": "Subject: Checking In — Mockups Status\n\nHi Maya,\n\nHope your week is going well. Just checking in on the mockups:\n\n**Status:**\n- Original due date: 3 days ago\n- Current status: Not received\n- Blocked work: Engineering can't start build\n\n**Could you let me know:**\n- Current state (in-progress / blocked / forgotten)\n- New realistic ETA\n- Anything you need from us to unblock\n\n**Impact on us:**\n- Engineering team is idle on this stream\n- Sprint commitments at risk\n- Need to communicate to stakeholders\n\n**Happy to:**\n- Hop on a call\n- Help unblock from our side\n- Adjust scope if needed\n\nLet me know.\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Quick check on the mockups\n\nHey Maya,\n\nThe mockups were due three days ago and we're starting to feel it on the engineering side — happy to wait if you need more time, just need to know an ETA so we can replan. Anything blocking you that we can help with?\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email to a colleague (Sam) who's leaving the company next week — say something genuine but not maudlin.",
        "rejected": "Subject: Best Wishes on Your Next Chapter\n\nHi Sam,\n\nHeard about your move — wanted to send a personal note before you head off.\n\n**What I want to say:**\n- It's been a real privilege working with you\n- Your [specific quality] made a real impact on me\n- The [specific project] wouldn't have been the same without you\n\n**What I'll miss:**\n- Your perspective in meetings\n- The way you handle [specific situation]\n- Your dry humor (don't change it)\n\n**Going forward:**\n- Stay in touch — LinkedIn, email, anything\n- Coffee anytime you're in the area\n- Always rooting for you\n\nBest of luck with what's next!\n\n[Your Name]",
        "chosen": "Hey Sam,\n\nHeard you're heading off next week. Just wanted to say it's been a genuine pleasure working with you — the [specific project] wouldn't have gone the same way without you, and I've learned a lot from how you handled the [specific situation] last quarter.\n\nLet's stay in touch. Coffee whenever you're around, and please do ping me if I can ever be useful from this side.\n\nGood luck with what's next.\n\n[Your Name]"
    },
    # --- global_neutral (4) ---
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email to a customer confirming we've rescheduled our planned implementation review meeting to next Wednesday at 2 PM their time.",
        "rejected": "Subject: Confirmed — Implementation Review Meeting Rescheduled\n\nDear [Customer],\n\nThank you for your patience as we worked out a new time. I'm pleased to confirm the rescheduled meeting:\n\n**New meeting details:**\n- **Date:** Wednesday, [date]\n- **Time:** 2:00 PM [your timezone]\n- **Duration:** 60 minutes\n- **Format:** Video conference\n- **Link:** [will be sent in calendar invite]\n\n**Calendar invite:**\n- Will be sent within next hour\n- Please accept to confirm attendance\n\n**Agenda (unchanged):**\n1. Implementation status review\n2. Open questions and blockers\n3. Next milestone alignment\n4. Q&A\n\n**Please bring:**\n- Latest project updates from your side\n- Any specific topics you'd like added\n- Stakeholder list for visibility\n\nLooking forward to the discussion!\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Confirmed — implementation review moved to Wednesday 2 PM\n\nHi [Name],\n\nJust confirming we've moved the implementation review to Wednesday at 2 PM your time. A calendar invite is on its way with the video link.\n\nAgenda is unchanged from before, but if there's anything specific you'd like to add, just let me know and I'll fold it in.\n\nLooking forward to it,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email to a partner organization clarifying terms in section 4.2 of the contract — there's ambiguity about who's responsible for data hosting.",
        "rejected": "Subject: Contract Clarification — Section 4.2 (Data Hosting Responsibility)\n\nDear [Partner Contact],\n\nI hope this email finds you well. I'm reaching out regarding ambiguity in the current contract that we'd like to clarify before signing.\n\n**Section in question:** 4.2 — Data Hosting\n\n**The ambiguity:**\n- Current language doesn't clearly specify which party is responsible for data hosting infrastructure\n- Both 'either party' and 'mutual responsibility' interpretations are possible\n- This could create significant operational issues\n\n**Our reading:**\n- [Your interpretation]\n\n**Our preference for clarity:**\n- Explicit assignment of responsibility\n- Clear cost allocation\n- Defined SLAs\n\n**Proposed amendment:**\n- Add specific clause naming responsible party\n- Define hosting costs\n- Specify uptime and security requirements\n\n**Timeline:**\n- Would like to resolve before [date]\n- Happy to schedule a call\n- Or work via email if simpler\n\nLet me know how you'd like to proceed.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Quick clarification needed on contract section 4.2\n\nHi [Name],\n\nWe'd like to clarify section 4.2 before signing — the current language is ambiguous about which party is responsible for data hosting, and we want to make sure we're on the same page before it becomes operational.\n\nOur reading is that [your interpretation]. Could you let us know if that aligns with your understanding? If not, a brief call this week to align would be easier than going back and forth in writing.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email to a recruiter asking for a 1-week extension on the offer decision deadline — I have another final-round interview scheduled.",
        "rejected": "Subject: Request for Extension on Offer Decision\n\nDear [Recruiter],\n\nThank you again for the offer — I am genuinely excited about the opportunity.\n\n**Current deadline:** [date]\n**Requested extension:** 1 week\n**New requested deadline:** [date]\n\n**Reason:**\n- Currently in final round at another company\n- Interview scheduled within this window\n- Want to make a well-informed decision\n- Not seeking leverage; want to give your offer fair consideration\n\n**My commitment:**\n- Final decision by extended deadline\n- No further extensions requested\n- Will keep you updated on my process\n\n**Where I stand:**\n- Your role is a strong contender\n- Want to be transparent about my situation\n- Eager to find the right mutual fit\n\nThank you for your understanding.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Could I have an extra week to decide?\n\nHi [Name],\n\nThank you again for the offer — I'm taking it very seriously. I have a final-round interview at another company within the next few days, and I'd like to be able to consider both before making a decision. Could I have an extra week, with a new deadline of [date]?\n\nI want to be transparent rather than ask for the extension without explaining why. Happy to talk through anything that would help.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email a former boss asking for career advice — I'm considering a difficult career pivot and would value her perspective.",
        "rejected": "Subject: Seeking Your Perspective — Career Decision\n\nDear [Former Boss's Name],\n\nI hope you're doing well. It's been a while since we last spoke, and I'm reaching out because I'm facing a difficult career decision and would deeply value your perspective.\n\n**Quick update on me:**\n- Currently at [current company / role]\n- [Time since we worked together] years on\n- Things have evolved in interesting directions\n\n**The decision I'm facing:**\n- Considering a major career pivot\n- [Brief direction]\n- Real trade-offs in both directions\n\n**Why I'm reaching out to you specifically:**\n- You've seen me at an earlier stage\n- I trust your judgment\n- You've made bold career moves yourself\n- Your perspective would be invaluable\n\n**Ask:**\n- 30-45 minute conversation in the coming weeks\n- Coffee in person if you're nearby\n- Video call otherwise\n- Async over email also works\n\n**On my end:**\n- Flexible on timing\n- Happy to share more context\n- Will respect your time\n\nThank you in advance.\n\nWarm regards,\n[Your Name]",
        "chosen": "Subject: Could I ask for some career advice?\n\nDear [Name],\n\nIt's been a while — hope life and work are treating you well. I'm reaching out because I'm wrestling with a fairly big career decision and you're one of the people whose perspective I'd most value on it.\n\nThe short version: I'm considering a pivot into [direction], leaving behind [current direction]. There are real trade-offs both ways and I think I'd benefit from talking it through with someone who knew me at an earlier stage of my career.\n\nWould you be open to a 30-45 minute call sometime in the next few weeks? Coffee in person if you're around, video otherwise, or I can ask the questions over email if that's easier.\n\nIt would be lovely to catch up either way.\n\nThanks,\n[Your Name]"
    },

    # ============ EMAIL_REFINE (14) ============
    # --- indian_corporate (5) ---
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Polish this overly stiff farewell email: 'Dear Esteemed Colleagues, As I bid adieu to this organization after 5 wonderful years, I would like to express my heartfelt gratitude to each and every one of you for the support, guidance, and friendship extended to me throughout my tenure. Wishing all of you continued success in your future endeavors.'",
        "rejected": "Here's a more natural farewell:\n\n**Subject:** Goodbye — and Thank You\n\n**Body:**\n\nHi everyone,\n\nAfter 5 years here, today is my last day.\n\n**What I'll take with me:**\n- The friendships\n- The projects we shipped\n- The lessons learned\n- The growth I experienced\n\n**Special thanks to:**\n- My team\n- My managers past and present\n- The cross-functional partners\n- Everyone who made the journey memorable\n\n**Going forward:**\n- Personal email: [address]\n- LinkedIn: [link]\n- Would love to stay connected\n\nWishing you all the best.\n\n[Your Name]",
        "chosen": "Subject: Goodbye after 5 years\n\nHi everyone,\n\nToday's my last day after five years here. I just wanted to say thank you — to the friends I made, the managers who took chances on me, and everyone who made this place worth showing up to. It's been a real chapter of my life.\n\nPlease do stay in touch. My personal email and LinkedIn are below — I'd love to hear from you.\n\nAll the best,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Polish this overly apologetic late submission email: 'Respected Sir, I am extremely sorry that I am submitting the report 2 days late. I take full responsibility and apologize for the inconvenience caused. I will ensure this does not happen again in the future. Please accept my sincere apologies.'",
        "rejected": "Here's a more measured version:\n\n**Subject:** Late Submission — Report Attached\n\n**Body:**\n\nDear [Name],\n\nApologies for the delay — the report is attached.\n\n**What happened:**\n- 2 days late vs. original deadline\n- Reason: [add real reason]\n- Quality not compromised\n\n**Going forward:**\n- Adjusted my workflow to prevent recurrence\n- Will flag risk earlier next time\n\n**On the report:**\n- All sections complete\n- Happy to walk through it\n- Open to feedback\n\nThanks for your patience.\n\nRegards,\n[Your Name]",
        "chosen": "Subject: Report attached — apologies for the delay\n\nDear [Name],\n\nThe report is attached. Apologies — it's two days later than promised. I should have flagged the slip earlier rather than letting the deadline pass.\n\nHappy to walk through any of it whenever convenient.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Tone down this too-formal first-meeting confirmation for a new client: 'Dear Mr. Khanna, This email is to formally confirm our meeting scheduled for Thursday the 15th at 11:00 AM at your esteemed office premises. I look forward to a fruitful interaction. Please feel free to contact me should any clarification be required.'",
        "rejected": "Here's a warmer version:\n\n**Subject:** Confirmed — Thursday 11 AM at Your Office\n\n**Body:**\n\nHi Mr. Khanna,\n\nJust confirming our meeting:\n\n**Details:**\n- 📅 **Date:** Thursday the 15th\n- 🕚 **Time:** 11:00 AM\n- 📍 **Location:** Your office\n\n**My plan:**\n- Arrive 10–15 mins early\n- Prepared discussion on our previous email exchange\n- Bring relevant materials\n\n**Questions for you:**\n- Anything specific you'd like me to bring?\n- Should I check in with security on arrival?\n- Parking guidance?\n\nLooking forward to it!\n\nBest,\n[Your Name]",
        "chosen": "Subject: Confirming Thursday at 11 AM\n\nHi Mr. Khanna,\n\nJust confirming our meeting at your office this Thursday the 15th at 11 AM. Looking forward to it — let me know if anything changes or if there's anything you'd like me to come prepared with.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Refine this over-the-top thank-you reply to someone who referred me to a job: 'Dear Manish Sir, Thank you so so much from the bottom of my heart for referring me to that role. I cannot tell you how grateful I am for your kindness and for taking time out of your busy schedule to help me. I will never forget this and will work very hard to make you proud. Thanking you once again from the deepest core of my heart.'",
        "rejected": "Here's a more genuine, grounded version:\n\n**Subject:** Thank You for the Referral\n\n**Body:**\n\nDear Manish,\n\nThank you for the referral — it really means a lot.\n\n**What it means to me:**\n- ✅ Vote of confidence from someone I respect\n- ✅ Genuine opportunity to grow\n- ✅ Reminder that good networks matter\n\n**My commitment:**\n- Will give my best to the process\n- Whatever the outcome, will keep you updated\n- Will pay it forward when I can\n\n**Quick logistics:**\n- Submitted application yesterday\n- Will let you know when I hear back\n- Available to discuss any further suggestions you have\n\nThanks again, Manish.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: Thank you for the referral\n\nDear Manish,\n\nThank you for the referral — it genuinely means a lot, and I won't forget it. I've submitted the application and I'll keep you posted on what comes next.\n\nWith gratitude,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Refine this stiff vacation handover note: 'Dear All, This is to inform you that I will be on leave from 20th to 27th of this month. Kindly find below the handover details for all pending items. In my absence, please coordinate with the respective owners as mentioned. For any urgent escalation, please contact my manager.'",
        "rejected": "Here's a warmer version:\n\n**Subject:** Handover Note — Out 20th to 27th\n\n**Body:**\n\nHi team,\n\nA quick handover note before I'm out:\n\n**My leave:**\n- Dates: 20th to 27th (back 28th)\n- Reachable on email: emergencies only\n\n**Pending items + owners during my absence:**\n\n| Item | Owner | Status |\n|------|-------|--------|\n| [Item 1] | [Name] | [Status] |\n| [Item 2] | [Name] | [Status] |\n| [Item 3] | [Name] | [Status] |\n\n**For escalations:**\n- Primary: [Manager name]\n- Secondary: [Backup name]\n\n**Quick tips:**\n- Check the shared doc first\n- Slack the channel for urgent items\n- Ping me only if truly needed\n\nThanks all — see you in a week!\n\n[Your Name]",
        "chosen": "Subject: Out 20th to 27th — quick handover\n\nHi team,\n\nI'll be out from the 20th to the 27th. Handover for the pending items is below — please coordinate with the owners listed. For anything urgent, [Manager name] is your escalation contact.\n\n- [Item 1] → [Name]\n- [Item 2] → [Name]\n- [Item 3] → [Name]\n\nI'll only be checking email for true emergencies. Back on the 28th.\n\nThanks,\n[Your Name]"
    },
    # --- us_tech_casual (5) ---
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Polish this defensive reply to negative feedback from my manager: 'Hi, I got your feedback. I want to push back a bit — I think some of what you mentioned wasn't really fair. The deadline issue wasn't my fault and the quality concerns are also debatable. Happy to discuss but I don't fully agree.'",
        "rejected": "Here's a less defensive, more constructive version:\n\n**Subject:** Re: Your Feedback — Want to Discuss\n\n**Body:**\n\nHi [Manager],\n\nThanks for the feedback. Taking time to sit with it before responding.\n\n**Where I agree:**\n- [Identify points you agree with]\n- These are fair and I'll work on them\n\n**Where I'd like to share more context:**\n- **Deadline issue:** [Concrete factors that affected it]\n- **Quality concerns:** [Specific examples / counter-evidence]\n\n**What I'd find helpful:**\n- Discussion to ensure we're seeing the same picture\n- Examples for any pattern observations\n- Clarity on what 'better' looks like\n\n**Going forward:**\n- Committed to addressing your concerns\n- Want to make sure we're aligned\n- Will set up time for a real conversation\n\nThanks for your patience as I think this through.\n\n[Your Name]\n\n**Improvements:**\n- Replaced defensive framing\n- Acknowledged before pushing back\n- Asked for collaborative discussion",
        "chosen": "Subject: Re: your feedback — could we talk this through?\n\nHi [Manager],\n\nThanks for the feedback. I've sat with it, and honestly some of it landed and some of it I see differently — particularly the deadline point, where I think there's important context, and the quality concerns, where I'd like to understand the specific examples you have in mind.\n\nRather than try to hash this out in writing, could we find time for a real conversation? I want to make sure I understand what you're seeing, and I want a fair chance to share what I'm seeing.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Tighten this meandering project kickoff email: 'Hey team, hope everyone is doing well! I'm excited to kick off our new project this week. It's going to be a lot of work but I think it'll be a great experience and we'll all learn a lot. The goal is basically to build a new feature for the platform. We'll be using some new technologies which should be fun. Let me know if you have any questions, otherwise we'll start Monday!'",
        "rejected": "Here's a tighter, more substantive kickoff:\n\n**Subject:** Project Kickoff — [Project Name]\n\n**Body:**\n\nHey team,\n\nWe're kicking off [Project Name] on Monday. Quick framing:\n\n**Goal:**\n- Build [specific feature] for the platform\n- Target launch: [date]\n\n**Tech stack:**\n- [Tech 1]\n- [Tech 2]\n- [Tech 3]\n\n**Roles:**\n- [Role 1]: [Person]\n- [Role 2]: [Person]\n- [Role 3]: [Person]\n\n**First week:**\n- Monday: Kickoff meeting\n- Tuesday-Wednesday: Setup + initial spec\n- Thursday-Friday: First implementation pass\n\n**Key links:**\n- Spec doc: [link]\n- Project tracker: [link]\n- Slack channel: #[channel]\n\nQuestions welcome before Monday.\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Kicking off [Project Name] on Monday\n\nHey team,\n\nWe're starting [Project Name] on Monday. The goal is to build [specific feature], targeting launch by [date]. We'll be using [tech stack], which most of us haven't touched before — expect a learning curve early on.\n\nI'll send a kickoff invite for Monday with the spec and full plan. In the meantime, the channel #[channel] is up if anyone wants to chat ahead of time.\n\nQuestions welcome.\n\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Refine this needy follow-up about a question I asked: 'Hey, sorry to bother but did you happen to see my question from yesterday about the API? Just wanted to check in — totally understand if you've been busy, no rush at all, just wanted to make sure it didn't get lost.'",
        "rejected": "Here's a more direct version:\n\n**Subject:** Quick Bump — API Question\n\n**Body:**\n\nHey [Name],\n\nBumping my API question from yesterday — wanted to make sure it didn't get buried in your inbox.\n\n**The question:**\n- [Restate briefly]\n\n**Why I need it:**\n- [Brief context on urgency]\n\n**Options:**\n- Async reply works\n- 5-min call also fine\n- Just let me know roughly when\n\nThanks!\n\n[Your Name]\n\n**Changes:**\n- Removed excessive apology\n- Restated the question for context\n- Offered options for response",
        "chosen": "Hey [Name],\n\nBumping my API question from yesterday in case it got buried. Let me know when you have a minute — happy to async or jump on a quick call.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Polish this too-corporate-sounding intro email to a new cross-functional partner: 'Dear Ms. Chen, I am writing to introduce myself as the engineering lead for the data platform team. I look forward to a fruitful collaboration with you and your team in the coming quarters. Please do not hesitate to reach out should you require anything.'",
        "rejected": "Here's a friendlier version:\n\n**Subject:** Intro — Engineering Lead for Data Platform\n\n**Body:**\n\nHi [Name],\n\nQuick hello —\n\n**About me:**\n- Engineering lead for the data platform team\n- Based in [location]\n- Been with the company [time]\n\n**What I'm hoping for:**\n- Tight collaboration with your team\n- Understanding your priorities\n- Identifying mutual opportunities\n\n**Suggested next steps:**\n- 30-min intro call?\n- Async over Slack works too\n- Whatever your preference\n\nLooking forward to working together!\n\nCheers,\n[Your Name]",
        "chosen": "Subject: Quick hello from the data platform side\n\nHi [Name],\n\nQuick intro — I lead engineering for the data platform team. Since we'll be working closely together this quarter, I figured a quick hello couldn't hurt. Would you be up for a 30-minute intro call in the next week or two so we can sync on priorities?\n\nLooking forward to working with you.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Polish this passive-voice-heavy status update so it sounds like a person wrote it: 'Hi team, it has been decided that the migration will be delayed by one week. The decision was made due to issues that were identified during testing. The team will be informed of the new timeline soon. Risks are being monitored closely.'",
        "rejected": "Here's a more active, human version:\n\n**Subject:** Migration Delayed by 1 Week\n\n**Body:**\n\nHi team,\n\nWe're delaying the migration by 1 week.\n\n**Why:**\n- Found issues during testing\n- Better to fix now than under production load\n\n**What changes:**\n- New target date: [date]\n- Other dependencies: pushed accordingly\n- Risks: being actively tracked\n\n**Next steps:**\n- Will share full revised timeline by EOW\n- Open to questions in the channel\n- Will brief affected teams individually\n\nThanks for rolling with this.\n\n[Your Name]",
        "chosen": "Subject: Migration moving by 1 week\n\nHi team,\n\nWe're pushing the migration by a week — testing surfaced some issues we'd rather fix now than wrestle with in production. I'll share a full revised timeline by end of week, and I'll loop in dependent teams individually.\n\nThanks for the patience.\n\n[Your Name]"
    },
    # --- global_neutral (4) ---
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Polish this overly long customer onboarding email — it's a wall of text: 'Dear Customer, Welcome to our platform! We are thrilled to have you on board. Over the next few weeks you will receive a series of helpful emails to guide you through the platform. We have a number of resources available including video tutorials, documentation, our support team, our community forum, and our knowledge base. If at any point you have questions please don't hesitate to reach out. We are here to help you succeed!'",
        "rejected": "Here's a tighter, more skimmable version:\n\n**Subject:** 🎉 Welcome to [Platform] — Getting Started\n\n**Body:**\n\nHi [Customer],\n\nWelcome aboard! Here's everything you need:\n\n**🚀 First steps:**\n- ✅ Complete profile\n- ✅ Connect your tools\n- ✅ Watch the 5-min intro\n\n**📚 Resources:**\n- 🎥 Video tutorials\n- 📖 Documentation\n- 💬 Support team\n- 🌐 Community forum\n- 🗂️ Knowledge base\n\n**📧 What's next:**\n- Weekly tips for the first month\n- Monthly check-in from your CSM\n- Quarterly product updates\n\n**Stuck? Reach us:**\n- support@[company]\n- Live chat in-app\n- Phone: [number]\n\nLet's get you to success.\n\nThe [Platform] Team",
        "chosen": "Subject: Welcome to [Platform]\n\nHi [Name],\n\nWelcome — really glad to have you with us. Over the next few weeks I'll send a short series of emails to help you get the most out of the platform. If you'd rather dive in on your own, the documentation and video tutorials in our help center are the fastest way to get started.\n\nAnytime you get stuck or have a question, just reply to this email or message support — there's always a real person on the other end.\n\nWelcome aboard,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Tighten this vague RFP response email: 'Hi, thank you for the RFP. We have reviewed it carefully and believe we can be a strong fit for your needs. We have significant experience in this area and would love to discuss further. Please let us know the next steps.'",
        "rejected": "Here's a more specific version:\n\n**Subject:** RFP Response — [Company] Strong Fit\n\n**Body:**\n\nHi [Name],\n\nThank you for the RFP — we've reviewed it thoroughly and are excited to engage.\n\n**Why we believe we're a strong fit:**\n- ✅ Direct experience with [specific area from RFP]\n- ✅ Track record with [type of client]\n- ✅ Capabilities that map to [specific requirement]\n- ✅ Differentiation: [unique offering]\n\n**Relevant case studies we can share:**\n- [Case study 1]\n- [Case study 2]\n- [Case study 3]\n\n**Our proposed next steps:**\n- 30-minute scoping call within 2 weeks\n- Detailed written proposal within 2 weeks of call\n- Reference customer introductions on request\n\n**Timeline alignment:**\n- We can meet your [Q] deliverable timeline\n- Resources available immediately\n\nLooking forward to hearing back.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: RFP response — confident on fit, here's what's next\n\nHi [Name],\n\nThank you for the RFP. After a careful read, we believe we're a strong fit — particularly on [specific area from the RFP], where we have direct experience with [relevant project or client type].\n\nWe'd like to propose a 30-minute scoping call within the next two weeks, after which we can put together a detailed written proposal. Happy to share relevant case studies and customer references if useful before then.\n\nLooking forward to hearing back.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Polish this defensive reply to someone calling out a missed deadline FROM their side, but they're blaming us: 'Hi, we received your email saying the project is delayed because of us. We need to push back on this. Our deliverables were on time and your team had everything you needed. We'd appreciate a more accurate accounting of where things actually stand.'",
        "rejected": "Here's a less defensive, more constructive version:\n\n**Subject:** Re: Project Delay — Let's Realign on Status\n\n**Body:**\n\nHi [Name],\n\nThanks for the update. Wanted to share our perspective so we can align:\n\n**Where we agree:**\n- Project is currently delayed\n- We want it back on track quickly\n\n**Our reading of the situation:**\n- Our deliverables shipped on time per the agreed schedule\n- Your team had inputs needed to proceed\n- Other factors may be at play we're not seeing\n\n**Proposed:**\n- Joint status review in next 48 hours\n- Walk through what each side delivered/needed\n- Identify the true blockers\n- Align on shared next steps\n\n**Spirit:**\n- Not looking to assign blame\n- Want shared accountability for getting back on track\n- Strong relationship matters more than the audit\n\nLet's get on a call this week.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Re: project delay — let's align on where we actually are\n\nHi [Name],\n\nThanks for the message. We do want this back on track, but our read of the situation is meaningfully different from yours — our deliverables were on time, and we believe everything your team needed was in place. Rather than going back and forth in writing, could we set up a joint status review this week to walk through what each side delivered and needed?\n\nThe goal is getting back on track, not assigning blame — but we do need a shared understanding of where we actually are before we can move forward.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Polish this confusing meeting recap: 'Hi all, just sending a quick recap of today's meeting. We talked about a bunch of different things. There were some action items but I want to confirm them. Generally the meeting was productive and we covered a lot of ground. Will follow up with more details soon.'",
        "rejected": "Here's a recap that's actually useful:\n\n**Subject:** Meeting Recap — [Date]\n\n**Body:**\n\nHi all,\n\nQuick recap of today's discussion:\n\n**Topics covered:**\n1. [Topic 1] — outcome: [brief]\n2. [Topic 2] — outcome: [brief]\n3. [Topic 3] — outcome: [brief]\n\n**Decisions made:**\n- ✅ [Decision 1]\n- ✅ [Decision 2]\n- ✅ [Decision 3]\n\n**Action items:**\n| Item | Owner | Due |\n|------|-------|-----|\n| [Item 1] | [Name] | [Date] |\n| [Item 2] | [Name] | [Date] |\n| [Item 3] | [Name] | [Date] |\n\n**Open questions:**\n- [Question 1]\n- [Question 2]\n\n**Next steps:**\n- Follow-up sync: [Date]\n- Final decisions: [Date]\n\nPlease confirm owners and dates by EOD.\n\nThanks,\n[Your Name]\n\n**Improvements:**\n- Specific over vague\n- Clear ownership\n- Trackable deliverables",
        "chosen": "Subject: Recap from today's meeting\n\nHi all,\n\nFrom today's meeting, the things worth capturing: we agreed on [decision 1], decided to push [decision 2] to next quarter, and left [topic 3] open pending more data.\n\nAction items: [Name] is owning [item 1] by [date]; [Name] is following up on [item 2] by [date]; I'll send out the proposal for [item 3] by end of week.\n\nLet me know if I missed or misrepresented anything.\n\nThanks,\n[Your Name]"
    },

    # ============ CONCEPT_EXPLAIN (4) ============
    {
        "context": "concept_explain", "topic_area": "rl",
        "prompt": "Can you explain what a 'value function' is in reinforcement learning? Going through a textbook and getting tripped up here.",
        "rejected": "## Value Functions in RL 📈\n\n### Definition:\nA value function estimates expected long-term reward from a given state (V) or state-action pair (Q).\n\n### Two Main Types:\n\n**1. State Value Function — V(s):**\n- Expected return starting from state `s`\n- Following policy `π`\n- Formula: V_π(s) = E[R_t | s_t = s, π]\n\n**2. Action Value Function — Q(s, a):**\n- Expected return starting from state `s`\n- Taking action `a`\n- Then following policy `π`\n- Formula: Q_π(s, a) = E[R_t | s_t = s, a_t = a, π]\n\n### Key Properties:\n- ✅ Capture long-term value (not just immediate reward)\n- ✅ Depend on the policy being followed\n- ✅ Learned from experience\n\n### Why They Matter:\n- Used in value-based methods (Q-learning, DQN)\n- Used in actor-critic methods\n- Foundation of many modern RL algorithms\n\n### Bellman Equation:\n```\nV(s) = R(s) + γ * Σ P(s'|s) * V(s')\n```\nWhere γ is the discount factor.\n\n### Verdict:\nValue functions are central to RL theory and practice!",
        "chosen": "The simplest way to think about a value function: it's a guess about how good a situation is in the long run, not just right now.\n\nImagine you're playing chess. The 'state' is the current position on the board. The value function tries to answer the question: 'if I'm in this position and I keep playing my usual strategy, how well am I likely to do from here?' A position where you're up a queen has high value. A position where you're about to be checkmated has very low value. A balanced opening position is somewhere in between.\n\nThere are two flavors of this you'll see in textbooks. **V(s)** answers 'how good is this state?' assuming you'll keep playing your usual strategy. **Q(s, a)** answers a more specific question: 'how good is this state if I take this particular action right now, and then go back to my usual strategy?' Q is more directly useful because it tells you which action to actually pick — just pick the one with the highest Q value.\n\nThe whole point of having value functions is that immediate rewards aren't enough to make good decisions. In chess, taking a pawn right now might feel good, but if it loses you the queen on the next move, the action had high immediate reward and low long-term value. Value functions let the agent see past the next move.\n\nMost RL algorithms are essentially trying to learn a good value function from experience — they play a lot of games, see how things turned out, and adjust their estimates of how valuable various states are."
    },
    {
        "context": "concept_explain", "topic_area": "ml",
        "prompt": "What's the difference between fine-tuning and prompt engineering? I keep using them interchangeably and I think I'm wrong.",
        "rejected": "## Fine-Tuning vs Prompt Engineering 🔧 vs 🗣️\n\n### Quick Distinction:\n- **Fine-tuning** modifies the model weights\n- **Prompt engineering** modifies the input to the model\n\n### Fine-Tuning:\n\n**What:**\n- Update model parameters on task-specific data\n- Changes the model itself\n- Persistent change\n\n**When to use:**\n- ✅ Need specialized behavior\n- ✅ Have labeled training data\n- ✅ Required output format/style\n\n**Cost:** High (compute, data, expertise)\n\n### Prompt Engineering:\n\n**What:**\n- Crafting better inputs to existing model\n- No weight changes\n- Per-query optimization\n\n**When to use:**\n- ✅ Rapid prototyping\n- ✅ Limited data/compute\n- ✅ General-purpose tasks\n\n**Cost:** Low (just iteration)\n\n### Comparison Table:\n| Factor | Fine-tuning | Prompt eng |\n|--------|-------------|------------|\n| Cost | High | Low |\n| Skills | ML engineering | Writing/iteration |\n| Persistence | Permanent | Per-call |\n| Use cases | Specialized | General |\n| Time to test | Hours-days | Seconds |\n\n### Hybrid Approaches:\n- Few-shot prompting (in-context learning)\n- RAG (retrieval + prompt)\n- Fine-tuned model + prompt engineering\n\n### Verdict:\nStart with prompt engineering. Fine-tune only if needed!",
        "chosen": "You're right that they're often confused, but they're actually pretty different things.\n\nPrompt engineering means changing what you *say* to the model. You don't touch the model itself — you just experiment with how you phrase your request, what examples you include, what role you ask it to play, and so on. 'Write me a poem' might give you a mediocre poem; 'Write me a melancholy poem in the style of Mary Oliver about an empty train station at dawn' will give you something much better. Same model, different input, different output. That's prompt engineering.\n\nFine-tuning means changing the model itself — actually updating its internal weights by training it on a new dataset. The model permanently learns to behave differently. If you fine-tune GPT on a thousand examples of medical advice, the resulting model will be measurably better at medical questions than the original, even on prompts you've never shown it before. The change sticks.\n\nThe practical guidance: prompt engineering is fast, cheap, and surprisingly powerful — you can solve a huge number of problems just by crafting better prompts. Fine-tuning is expensive (you need data, compute, and ML expertise) and only worth it when prompt engineering hits its limits. Most people should start with prompt engineering and only fine-tune when they have a clear, specific reason.\n\nYour RL project is actually a form of fine-tuning — specifically, you're fine-tuning the model so it produces less over-formatted output, in a way that no amount of prompt engineering would reliably achieve."
    },
    {
        "context": "concept_explain", "topic_area": "ml",
        "prompt": "What's a loss function and why does it matter? I'm new to ML and the term keeps coming up.",
        "rejected": "## Loss Functions Explained 📉\n\n### Definition:\nA loss function (also called a cost function or objective function) measures how wrong a model's predictions are.\n\n### Role in Training:\n- Quantifies prediction error\n- Provides signal for optimization\n- Guides weight updates\n\n### Common Loss Functions:\n\n**Regression:**\n- **MSE (Mean Squared Error):** Average squared difference\n- **MAE (Mean Absolute Error):** Average absolute difference\n\n**Classification:**\n- **Cross-Entropy:** Standard for multi-class\n- **Binary Cross-Entropy:** For binary classification\n- **Hinge Loss:** SVMs\n\n**Other:**\n- **Triplet Loss:** Similarity learning\n- **Contrastive Loss:** Representation learning\n- **Custom losses:** Domain-specific\n\n### Mathematical Form:\nFor MSE: L = (1/n) Σ (y_true - y_pred)²\n\n### How It's Used:\n1. Forward pass → predictions\n2. Compute loss vs. ground truth\n3. Backprop → gradients\n4. Update weights to reduce loss\n5. Repeat\n\n### Key Properties:\n| Property | Importance |\n|----------|-----------|\n| Differentiable | Required for gradient descent |\n| Convex | Easier to optimize |\n| Bounded | Numerical stability |\n\n### Verdict:\nThe loss function defines what 'good' means for your model!",
        "chosen": "A loss function is just a way of measuring how wrong your model is. That's the whole concept.\n\nThink about teaching a kid to throw darts at a target. After each throw, you tell them how far they missed — 'two inches to the left,' 'six inches high,' whatever. That distance from the bullseye is the 'loss.' The kid adjusts their aim based on the feedback and tries again, with the goal of making the loss smaller over time.\n\nML training works the same way. You show the model an example, it makes a prediction, and you compare the prediction to the right answer. The loss function tells you how badly the model missed. Then the training algorithm nudges the model's weights to reduce that loss, the same way the kid nudges their aim. Do this a million times and the model gets good at the task.\n\nThe reason it matters which loss function you pick: it defines what 'good' actually means for your task. For predicting house prices, you probably want a loss that penalizes being off by more dollars more heavily — Mean Squared Error does that. For classifying email as spam or not, you want a loss that penalizes confident wrong answers more than uncertain wrong answers — that's what cross-entropy does. Pick the wrong loss and you'll train a model that optimizes for the wrong thing.\n\nFor your RL project specifically, the 'loss' is the DPO loss — a clever formulation that pushes up the probability of preferred responses and down the probability of rejected ones relative to a reference model."
    },
    {
        "context": "concept_explain", "topic_area": "ml",
        "prompt": "What's a 'gradient' in machine learning context? I get the calculus definition but I don't see how it connects to training.",
        "rejected": "## Gradients in ML 📈\n\n### Mathematical Definition:\nThe gradient is the vector of partial derivatives of a function with respect to its variables.\n\n### In ML Context:\nFor a loss function L with parameters θ, the gradient ∇_θ L tells us:\n- **Direction** of steepest increase in loss\n- **Magnitude** of that rate of change\n\n### Why It's Used in Training:\n\n**1. Direction of Update:**\n- Negative gradient = direction of steepest decrease\n- We update weights in this direction\n\n**2. Magnitude Information:**\n- Larger gradient = larger update\n- Smaller gradient = smaller update\n\n**3. Local Information:**\n- Gradient tells us about the loss surface locally\n- We move in tiny steps to follow the slope\n\n### How It's Computed:\n- **Backpropagation:** Efficient algorithm for neural networks\n- Uses chain rule to propagate gradients backward\n\n### Common Issues:\n- **Vanishing gradients:** Too small to learn (deep networks)\n- **Exploding gradients:** Too large, training unstable\n- **Gradient noise:** From mini-batch sampling\n\n### Verdict:\nGradients are how neural networks 'feel' their way toward better weights!",
        "chosen": "You already have the right calculus intuition — the gradient tells you the direction in which a function is increasing fastest. The connection to training is just: that's exactly the information we need to make a model better.\n\nHere's the picture. The model has a bunch of weights — millions of them — and a loss function that measures how wrong the model is. You can imagine those weights as coordinates in a hugely high-dimensional space, and the loss as a 'height' at each point in that space. Lower height = better model.\n\nYour goal is to find a low spot in this landscape. But you can't see the whole landscape; the only information you have at your current spot is the gradient of the loss with respect to the weights. That gradient is a vector that points in the direction the loss is *increasing* the fastest — and therefore, the *opposite* direction points to where the loss is decreasing fastest. So you take a small step in that opposite direction, recompute the gradient, take another step, and so on. That's gradient descent.\n\nThe practical magic is that we can compute these gradients efficiently even for models with millions or billions of parameters, using backpropagation. Without an efficient gradient computation, none of modern deep learning would be feasible.\n\nSo when people say 'the model is learning' during training, what they literally mean is 'we're computing gradients of the loss with respect to the weights, and adjusting the weights in the opposite direction.' That's the entire engine."
    },

    # ============ DECISION_ADVICE (4) ============
    {
        "context": "decision_advice", "topic_area": "career",
        "prompt": "Should I take a remote job at half pay or stay at my current onsite job? I'm burnt out from commuting.",
        "rejected": "## Remote at Half Pay vs Onsite Status Quo 🏠 vs 🏢\n\n### Quick Take:\nDepends heavily on financial reality and burnout severity.\n\n### Remote at Half Pay:\n\n**Pros:**\n- ✅ No commute\n- ✅ Better quality of life\n- ✅ Time for health, family, hobbies\n- ✅ Lower burnout risk\n- ✅ Geographic flexibility\n\n**Cons:**\n- 🔴 Significant pay cut\n- 🔴 May limit career growth\n- 🔴 Remote-only career risks\n- 🔴 Lifestyle adjustment\n\n### Stay at Current Job:\n\n**Pros:**\n- ✅ Stable income\n- ✅ Career momentum\n- ✅ Existing benefits\n- ✅ Avoid risk\n\n**Cons:**\n- 🔴 Continued burnout\n- 🔴 Long-term health impact\n- 🔴 Quality of life cost\n- 🔴 May leave anyway later\n\n### Financial Considerations:\n| Factor | Impact |\n|--------|--------|\n| Monthly bills | Critical |\n| Savings buffer | Critical |\n| Dependents | High |\n| Healthcare | High |\n| Debt | High |\n\n### Decision Framework:\n1. Can you survive on half pay?\n2. How severe is burnout?\n3. What does your 1-year self want?\n4. What does your 5-year self want?\n\n### Verdict:\nIf finances allow and burnout is severe, take the remote job!",
        "chosen": "Honestly? I'd be cautious here, and not for the reasons you might think.\n\nHalf pay is a big cut. The first question I'd want answered before considering this is: can you actually afford half pay? Not 'will I survive' — but, after rent, basic expenses, and any debt, will you have enough left to handle a sudden medical bill, a car repair, or six months of unemployment if the remote job doesn't work out? If the answer is no, taking the job puts you in a financially precarious position that can create its own kind of stress. Trading commute-burnout for money-anxiety isn't necessarily a win.\n\nThe second question: have you really exhausted the alternatives at your current job? Talked to your manager about a hybrid arrangement, working from home a few days a week, shifted hours to avoid rush hour, moved closer to the office? A pay cut is a permanent solution; commute fixes are often more available than people realize.\n\nThat said — if the burnout is severe (we're talking 'affecting my health, my relationships, my sleep' not 'I'm tired'), and you can financially absorb the cut, then yes, take the job. Health doesn't have a salary equivalent, and there's nothing to optimize about your career if you burn out.\n\nWhat's the burnout actually looking like for you right now, and what's the financial picture honestly?"
    },
    {
        "context": "decision_advice", "topic_area": "ml_tools",
        "prompt": "Should I learn HuggingFace transformers or build everything from scratch with PyTorch? I want to actually understand things.",
        "rejected": "## HuggingFace vs PyTorch From Scratch 🤗 vs 🔥\n\n### Quick Take:\nDo both, in the right order.\n\n### HuggingFace Transformers:\n\n**Pros:**\n- ✅ Industry standard\n- ✅ Fast prototyping\n- ✅ Massive model zoo\n- ✅ Production-ready\n- ✅ Active community\n\n**Cons:**\n- 🔴 Abstracts away internals\n- 🔴 Can become 'API thinking'\n- 🔴 Less deep understanding\n\n### PyTorch From Scratch:\n\n**Pros:**\n- ✅ Deep understanding\n- ✅ Full control\n- ✅ Better for research\n- ✅ Foundational skills\n\n**Cons:**\n- 🔴 Slow to ship\n- 🔴 Reinventing wheel\n- 🔴 Easy to get stuck\n\n### Recommended Path:\n1. **Phase 1:** Build a small transformer from scratch in PyTorch\n2. **Phase 2:** Move to HuggingFace for real projects\n3. **Phase 3:** Dive into HuggingFace internals as needed\n\n### Comparison Matrix:\n| Goal | Pick |\n|------|------|\n| Learn deeply | Scratch |\n| Ship fast | HuggingFace |\n| Research | Both |\n| Industry job | Both |\n| Beginner | Scratch first, then HF |\n\n### Verdict:\nStart with scratch for understanding, then HuggingFace for productivity. Both matter!",
        "chosen": "Do both, but in this order: build one thing from scratch in pure PyTorch first, then move to HuggingFace for everything after.\n\nThe value of building from scratch isn't that you'll keep doing it — you won't, and shouldn't. It's that doing it once, end to end, takes the magic out of the library calls you'll use later. When you build a small transformer yourself — the attention mechanism, the positional encodings, the training loop — and you watch it learn something simple, you stop seeing HuggingFace as a black box and start seeing it as exactly what it is: convenient wrappers around things you understand. That changes how you use the library and how you debug it when things go wrong.\n\nKarpathy's 'Let's build GPT' YouTube series is the classic recommendation here — a few hours of work and you'll have implemented a small language model from scratch. Worth doing once.\n\nAfter that, switch to HuggingFace for everything real. Their library is industry standard for good reasons: huge model zoo, robust training utilities, the entire ecosystem speaks its conventions. Trying to do production-scale work from scratch is reinventing the wheel badly.\n\nFor your RL project specifically, you'll be using HuggingFace's TRL library for the DPO training — there's no good reason to reimplement it. But the from-scratch foundation will pay off when something inevitably breaks and you have to dig into what's actually happening under the hood."
    },
    {
        "context": "decision_advice", "topic_area": "courses",
        "prompt": "Should I do an in-person bootcamp or a self-paced online course for learning data science?",
        "rejected": "## Bootcamp vs Self-Paced Online Course 🏫 vs 💻\n\n### Quick Take:\nBootcamp for structure, online for flexibility.\n\n### Bootcamp:\n\n**Pros:**\n- ✅ Structured curriculum\n- ✅ Peer learning\n- ✅ Career services\n- ✅ Network building\n- ✅ Forces commitment\n\n**Cons:**\n- 🔴 Expensive ($10k–$20k)\n- 🔴 Fixed schedule\n- 🔴 Quality varies\n- 🔴 No guarantees\n\n### Self-Paced Online:\n\n**Pros:**\n- ✅ Cheap or free\n- ✅ Flexible schedule\n- ✅ Repeatable content\n- ✅ Self-directed depth\n\n**Cons:**\n- 🔴 Easy to quit\n- 🔴 No peer support\n- 🔴 No accountability\n- 🔴 No structured path\n\n### Decision Matrix:\n| Factor | Bootcamp | Online |\n|--------|----------|--------|\n| Cost | High | Low |\n| Time | 3–6 months full-time | Flexible |\n| Structure | High | Low |\n| Network | Strong | Weak |\n| Discipline needed | Low | High |\n| Career help | Yes | No |\n\n### Verdict:\nBootcamp if you can afford it and need structure. Online if you're disciplined and budget-conscious!",
        "chosen": "Depends way more on you than on the courses, honestly.\n\nThe brutal truth about self-paced online courses: most people who start them don't finish. The completion rates for MOOCs are genuinely depressing — somewhere around 5–10%. It's not because the content is bad; it's because without a deadline, a peer group, and someone expecting you to show up, learning hard things is really hard. If you've ever started a Coursera course and let it slide, you already know this.\n\nBootcamps work largely because they remove that problem. You paid a lot of money, you're showing up every day, your peers are around you, and there's a clear endpoint. That structure does a lot of the work of getting you to the finish line, even if the actual content isn't dramatically better than what's online for free.\n\nSo the real question is honest self-assessment: are you the kind of person who finishes online courses on your own? Some people genuinely are — they're rare but they exist. If you are, save the money and do online. If you're being honest with yourself and you know you'll drift, the bootcamp's structure is what you're really paying for, and it's worth it.\n\nThe one option worth considering that's neither: a structured online course with a real cohort, deadlines, and live sessions (something like Fast.ai's course, or some of the more rigorous cohort-based programs). Cheaper than a bootcamp, more structured than self-paced. Best of both for some people.\n\nWhat's your honest track record with self-directed learning so far?"
    },
    {
        "context": "decision_advice", "topic_area": "career",
        "prompt": "Should I take a job at a small consulting firm or a position at a tech product company? Both offer similar comp.",
        "rejected": "## Consulting vs Tech Product Company 💼 vs 💻\n\n### Quick Take:\nProduct for depth, consulting for breadth.\n\n### Small Consulting Firm:\n\n**Pros:**\n- ✅ Variety of clients\n- ✅ Exposure to different industries\n- ✅ Faster business skill development\n- ✅ Network with diverse companies\n- ✅ Often faster promotions\n\n**Cons:**\n- 🔴 Less technical depth\n- 🔴 Client-driven hours\n- 🔴 Travel demands\n- 🔴 Output-focused (vs craft)\n\n### Tech Product Company:\n\n**Pros:**\n- ✅ Deep ownership of product\n- ✅ Long-term thinking\n- ✅ Technical depth\n- ✅ Stable focus\n- ✅ Build vs. ship-and-leave\n\n**Cons:**\n- 🔴 Narrower exposure\n- 🔴 Slower pace\n- 🔴 Single industry\n- 🔴 Politics in larger orgs\n\n### Match by Goal:\n| Goal | Better |\n|------|--------|\n| Technical depth | Product |\n| Industry breadth | Consulting |\n| Founder ambitions | Either |\n| Stability | Product |\n| Fast learning | Consulting |\n| Quality of life | Product (usually) |\n\n### Verdict:\nPick based on what you want to be in 5 years!",
        "chosen": "The honest difference isn't pay or prestige — it's what you'll actually do day-to-day, and what you'll be like in five years.\n\nConsulting (even at a small firm) tends to give you broad exposure: you'll see how lots of different companies operate, you'll get good at quickly understanding new problems, and you'll build a wide network across industries. The downside is that you rarely build deep technical mastery in any one thing, and the work is structurally output-focused — you do the project, you hand it off, you move on. Some people thrive on the variety; others find it shallow over time.\n\nProduct companies are the opposite. You're inside one thing, you watch it evolve over years, and you develop deep ownership and technical depth. You'll know your product, your codebase, your users, and your domain at a level a consultant rarely will. The trade-off is narrower exposure and slower pace, plus the politics that come with longer tenures in one place.\n\nThe choice often comes down to which of these matters more to you: 'I want to see a lot' or 'I want to build something well.' Neither is right; they produce very different careers.\n\nFor what it's worth, the people I've seen burn out fastest are the ones who chose consulting because it sounded prestigious but actually wanted to build deep things. And the people who got stuck were the ones who chose product because it sounded safe but actually craved variety.\n\nWhich one pulls at you more, honestly?"
    },

    # ============ CASUAL_REPLY (2) ============
    {
        "context": "casual_reply",
        "prompt": "Reply to a Slack from a coworker who just shipped a big launch: 'we did it!! 🎉'",
        "rejected": "Here are some response options:\n\n**Celebratory:**\n- WE DID IT!! 🎉🎉 Massive congrats team!\n\n**Specific & warm:**\n- 🎊 Such a great milestone. So proud of what we built.\n\n**Brief but enthusiastic:**\n- HUGE!! Take a victory lap.\n\n**Reflective:**\n- After everything that went into this — congratulations all around.\n\n**Tone tips:**\n- Match the energy\n- Use emoji if they did\n- Acknowledge the work behind it",
        "chosen": "WE DID IT 🎉 honestly didn't think we'd pull it off two weeks ago. Take the rest of the day."
    },
    {
        "context": "casual_reply",
        "prompt": "Reply to a friend who just texted: 'i bombed the interview today, feel terrible'",
        "rejected": "Here are some response options:\n\n**Empathic & supportive:**\n- Oh no, I'm so sorry. That's the worst feeling. Want to vent?\n\n**Practical reassurance:**\n- One interview doesn't define you. Want to talk it through?\n\n**Brief acknowledgment + offer:**\n- That sucks. Coffee? Or just call me whenever.\n\n**With perspective:**\n- I've been there. It feels permanent but it isn't.\n\n**Best practice:**\n- Don't minimize\n- Offer presence\n- Be available, not preachy",
        "chosen": "Oh no, I'm sorry. Want to talk it through tonight? I'll bring snacks."
    },

    # ============ SHORT_EXPLAIN (2) ============
    {
        "context": "short_explain",
        "prompt": "A coworker asked why we keep our PR descriptions detailed even for tiny changes. Quick explanation?",
        "rejected": "Here's the reasoning:\n\n**Why detailed PRs:**\n- **Audit trail:** Why was X changed?\n- **Reviewer context:** Faster review\n- **Future debugging:** Helps when bug reappears in 6 months\n- **Knowledge transfer:** New team members learn from history\n\n**For tiny changes specifically:**\n- Future-you won't remember why\n- Bisecting becomes easier\n- Forces moment of reflection\n\n**Trade-offs:**\n- Slight overhead\n- Can feel ceremonial for one-liners",
        "chosen": "Mostly because six months from now, when someone's bisecting through commits to find when a bug was introduced, they'll need to understand each change quickly without re-reading the code. A one-line PR description that just says 'fix bug' is useless at that point. The extra two minutes to write a real description pays for itself the first time it saves someone an hour of code archaeology."
    },
    {
        "context": "short_explain",
        "prompt": "A junior asked why we use linters in our codebase. How do I explain in a couple of lines?",
        "rejected": "Here's the reasoning:\n\n**Why linters:**\n- **Consistency:** Whole codebase looks like one author wrote it\n- **Catch bugs early:** Common mistakes flagged before review\n- **Reduce review noise:** Style debates handled automatically\n- **Onboarding:** New devs learn standards fast\n\n**Common linters:**\n- ESLint (JS/TS)\n- Pylint, ruff (Python)\n- gofmt (Go)\n\n**Trade-offs:**\n- Initial setup cost\n- Occasionally annoying rules\n- Need team agreement",
        "chosen": "Mostly to keep the codebase looking like one consistent author wrote it, instead of 50 different people with 50 different styles. Linters also catch a class of small bugs (unused variables, wrong comparisons, missing returns) before they ever reach code review, which means reviewers can focus on the actual logic instead of arguing about formatting. The whole team agrees on the rules once, the linter enforces them forever."
    },
]


def main() -> None:
    path = Path("data/formatting_pairs_v1.jsonl")
    assert path.exists()
    existing = set()
    with path.open() as f:
        for line in f:
            existing.add(json.loads(line)["prompt"])
    new = [r for r in ROWS if r["prompt"] not in existing]
    with path.open("a") as f:
        for row in new:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    counts = Counter()
    with path.open() as f:
        all_rows = [json.loads(line) for line in f]
    for r in all_rows:
        counts[r["context"]] += 1
    print(f"Appended: {len(new)} new (skipped {len(ROWS)-len(new)} dupes)")
    print(f"Total: {len(all_rows)}\n")
    for c, n in sorted(counts.items()):
        print(f"  {c:18} {n}")


if __name__ == "__main__":
    main()
