"""
Batch 7 append script — introduces tone_rewrite category.
The 'rejected' versions exhibit specific tone-rewrite failure modes:
  - 'Here's a more polite version:' meta-commentary
  - over-hedging ('I hope this finds you well', 'if it's not too much trouble')
  - bullet restructuring even when only tone was asked for
  - '**Key changes:**' / '**What I adjusted:**' outros
  - polite → sycophantic; subtle → vague; convincing → salesy
The 'chosen' versions achieve the actual tone shift while staying
direct, concise, honest, and human.
"""

import json
from pathlib import Path
from collections import Counter

ROWS = [
    # ============ TONE_REWRITE (14) ============
    {
        "context": "tone_rewrite", "topic_area": "polite",
        "prompt": "Make this more polite — I need to tell my coworker the numbers in his report are wrong: 'The numbers are wrong. Please fix them before sending it out.'",
        "rejected": "Here's a more polite version:\n\n**Subject:** Quick Check — Some Figures in the Report\n\n**Body:**\n\nHi [Name],\n\nI hope this email finds you well! Thank you so much for putting together the report — I really appreciate the effort that went into it.\n\n**I just wanted to gently flag:**\n- A few numbers in the report seem off\n- Specifically: [point to the items]\n- Could you take another look when you get a chance?\n\n**Why I'm flagging:**\n- Want to make sure everything is accurate before it goes out\n- May just be a small slip\n- Easy to fix\n\n**What I'd suggest:**\n- Verify against source\n- Update the numbers\n- Then we can move forward\n\nThanks again for all your hard work on this!\n\nWarm regards,\n[Your Name]\n\n**Key changes:**\n- Added warm opening\n- Softened the framing\n- Acknowledged effort\n- Suggested action without demanding",
        "chosen": "Hey [Name], could you double-check the numbers in the report before sending it out? A few of them look off to me. Happy to walk through what I'm seeing if it helps."
    },
    {
        "context": "tone_rewrite", "topic_area": "subtle",
        "prompt": "Make this more subtle — I want to tell a friend I can't come to her engagement party without making a big deal: 'I can't come to your engagement party, sorry.'",
        "rejected": "Here's a more subtle, gentle version:\n\nHey [Name]!\n\nI'm so sorry to share this — I won't be able to make your engagement party. 😔\n\n**Reasons (without going into too much detail):**\n- Prior commitment I can't move\n- Travel logistics that didn't work out\n- Personal situation requiring my attention\n\n**What I want you to know:**\n- I'm SO happy for you both ❤️\n- I'll be there in spirit\n- I want to celebrate with you separately\n\n**Let's plan:**\n- Coffee / dinner when you're back from honeymoon?\n- A small gift coming your way\n- You're in my thoughts on the day\n\nCongratulations again to you and [partner]! Can't wait to celebrate properly soon.\n\nLove,\n[Your Name]\n\n**Key tone shifts:**\n- Added warmth and celebration\n- Avoided over-explaining\n- Pivoted to a positive alternative",
        "chosen": "[Name]!! So so happy for you both. Unfortunately I won't be able to make the party itself — but let me steal you for a proper celebration of our own when things settle down. I want to actually hear about everything."
    },
    {
        "context": "tone_rewrite", "topic_area": "convincing",
        "prompt": "Make this more convincing — I'm asking my manager for a raise: 'I think I deserve a raise. I've been doing good work and taking on more responsibility.'",
        "rejected": "Here's a more convincing version:\n\n**Subject:** Discussion on Compensation — Request for Review\n\n**Body:**\n\nHi [Manager],\n\nI'd like to formally request a compensation review based on my contributions over the past year.\n\n**Key contributions:**\n- 🚀 Led [Project A] to successful launch — resulted in $[X] revenue\n- 🚀 Took on [responsibility] beyond my role — saved [Y] hours/week for the team\n- 🚀 Mentored [N] junior team members — all promoted within 6 months\n- 🚀 Recognized in [Award/Feedback] for exceptional work\n\n**Market data:**\n- Similar roles in our market pay [X-Y] range\n- My current comp is in the lower quartile\n- [Salary comparison data] supports my case\n\n**What I'm asking for:**\n- [X]% increase\n- Effective from [date]\n- Tied to specific deliverables if helpful\n\n**Value to the company:**\n- Continued strong performance\n- Reduced flight risk\n- Long-term commitment\n\nHappy to discuss in our next 1:1 or schedule a dedicated time.\n\nThanks,\n[Your Name]\n\n**Key improvements:**\n- Added specific evidence\n- Quantified contributions\n- Included market context\n- Clear, specific ask",
        "chosen": "Hi [Manager],\n\nI'd like to talk about a comp adjustment in our next 1:1. The case I want to make: I've shipped [specific project] this year, taken on [specific expanded responsibility] beyond my original scope, and consistently performed above the level my current band represents. My understanding from market data is that comparable roles in our market are paying meaningfully more than my current package, and I think it's reasonable to bring mine closer to that range.\n\nI'd rather have a real conversation about this than send a list, but wanted to flag the topic in advance so you have time to think about it.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "tone_rewrite", "topic_area": "firm",
        "prompt": "Make this firm but not aggressive — I need to decline a request from a senior person to take on extra work: 'I can't take this on, I'm already overloaded.'",
        "rejected": "Here's a firm but professional version:\n\n**Subject:** Re: [Request] — Honest Bandwidth Check\n\n**Body:**\n\nHi [Senior Person],\n\nThank you for thinking of me for this — I appreciate the trust.\n\n**However:**\n- I'm currently at full capacity\n- Taking this on would compromise quality on existing commitments\n- Or require dropping something already committed to\n\n**What I can offer:**\n- Defer this until [date] when I have capacity\n- Suggest [colleague] who has relevant skills\n- Take on a smaller piece if scoped down\n- Brain dump my thinking even if I can't lead\n\n**To be fully transparent:**\n- This isn't about willingness\n- It's about realistic capacity\n- Better to be honest now than fail later\n\nLet me know which path makes sense.\n\nRespectfully,\n[Your Name]\n\n**Why this works:**\n- Acknowledges the ask\n- Holds the position firmly\n- Offers alternatives\n- Stays professional",
        "chosen": "Hi [Senior Person],\n\nThank you for thinking of me. Honestly, I can't take this on right now — I'm already at capacity, and adding it would mean either dropping something existing or compromising quality across the board. I don't want to do either.\n\nIf there's room to defer to [date] or scope it down to a smaller piece, I'd be open to that conversation. Otherwise, [colleague] might be a good fit for the full scope.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "tone_rewrite", "topic_area": "empathetic",
        "prompt": "Make this more empathetic — my coworker just told me she didn't get the promotion she's been working toward for 2 years: 'Sorry to hear that. I'm sure you'll get it next cycle.'",
        "rejected": "Here's a more empathetic version:\n\n**Suggested response:**\n\nOh [Name], I'm so genuinely sorry. 💛\n\n**What I want you to know:**\n- This is genuinely hard\n- You've earned this many times over\n- The decision doesn't reflect your worth\n\n**Acknowledge the feelings:**\n- Disappointment is fair\n- Frustration is valid\n- Take time to feel it all\n\n**Practical care:**\n- Want to grab a coffee?\n- Need someone to vent to?\n- Or just space — totally your call\n\n**Looking ahead (gently):**\n- Next cycle is a real chance\n- We can talk strategy when you're ready\n- I'm in your corner either way\n\n**Tone tips:**\n- Don't rush past the pain\n- Don't fix or advise\n- Just be present",
        "chosen": "Oh [Name], I'm so sorry. Two years of working toward this — that's a lot. I'm not going to try to spin it into something positive right now because it just sounds shit. Want to grab a coffee or a walk later? No agenda, just want to be around if you need it."
    },
    {
        "context": "tone_rewrite", "topic_area": "apologetic",
        "prompt": "Make this more apologetic — I need to admit to a client that we missed a critical detail in their project: 'We missed a detail in the project. It's been fixed now.'",
        "rejected": "Here's a more apologetic version:\n\n**Subject:** Sincere Apology — Project Detail Oversight\n\n**Body:**\n\nDear [Client],\n\nI am writing to offer my sincerest apologies for an oversight on our part.\n\n**What happened:**\n- We missed [specific detail] in the project\n- Discovered during [internal review / your feedback]\n- Should not have happened, full stop\n\n**Taking responsibility:**\n- 🙏 This was our miss, not yours\n- 🙏 We dropped the ball on quality control\n- 🙏 Your trust deserved better\n\n**What we've done:**\n- ✅ Fixed immediately upon discovery\n- ✅ Reviewed adjacent items for similar issues\n- ✅ Updated our process to catch this in future\n\n**How we'll prevent recurrence:**\n- Adding [specific check] to QA process\n- Peer review for [type of work]\n- Quarterly process audit\n\n**Making it right:**\n- [Specific gesture — credit, extra hours, etc.]\n- Will follow up to confirm satisfaction\n- Available for call to discuss further\n\nAgain, our deepest apologies. We value your business and partnership, and this won't happen again.\n\nWith sincere apologies,\n[Your Name]",
        "chosen": "Dear [Client],\n\nI owe you a real apology. We missed [specific detail] in the project, which we should have caught. It's been fixed, and we've also reviewed the adjacent work to make sure there's nothing else of the same kind hiding in there.\n\nThe miss is on us. I'd like to talk through what we're doing to prevent this from happening again, and to make sure you're fully comfortable with where things stand now. Could we find 20 minutes this week?\n\nApologies again,\n[Your Name]"
    },
    {
        "context": "tone_rewrite", "topic_area": "diplomatic",
        "prompt": "Make this more diplomatic — I need to disagree with my director's proposal in a meeting tomorrow: 'I disagree with this approach. I think we should do something different.'",
        "rejected": "Here's a more diplomatic version:\n\n**Suggested framing:**\n\n'I really appreciate the thinking behind this approach, and I can see where it's coming from.\n\n**That said, I'd love to gently raise a few considerations:**\n\n- **Concern 1:** [Specific concern]\n  - Why this matters: [reason]\n  - Risk if not addressed: [impact]\n\n- **Concern 2:** [Specific concern]\n  - Why this matters: [reason]\n  - Risk if not addressed: [impact]\n\n**An alternative worth considering:**\n- [Brief description of alternative]\n- Pros: [list]\n- Cons: [list]\n- Trade-offs: [list]\n\n**To be clear:**\n- I'm not against the original approach\n- I want us to make the best decision\n- Open to being convinced otherwise\n\n**Suggested next step:**\n- Quick discussion of the trade-offs\n- Decision after we've examined alternatives\n- I'll support whatever we decide\n\nWhat does the rest of the team think?'\n\n**Why this works:**\n- Acknowledges before disagreeing\n- Frames concerns as questions\n- Offers alternative constructively\n- Invites discussion",
        "chosen": "'I want to push back a little on this — not because I think it's wrong, but because I'm worried about [specific concern]. I think there's a real chance this leads to [consequence] given [reason]. Could I sketch out an alternative that I think handles that risk better? Happy to be convinced if I'm missing something.'"
    },
    {
        "context": "tone_rewrite", "topic_area": "confident",
        "prompt": "Make this more confident — I'm asking my manager for ownership of a new project: 'I was wondering if maybe I could possibly take the lead on the new project? If you think I'm ready, of course.'",
        "rejected": "Here's a much more confident version:\n\n**Suggested message:**\n\nHi [Manager],\n\nI'd like to lead the new project.\n\n**Why I'm the right person:**\n- ✅ Background directly relevant ([cite specifics])\n- ✅ Track record on similar work ([cite specifics])\n- ✅ Already started thinking about the approach ([brief])\n- ✅ Bandwidth available to commit fully\n\n**What I'll bring:**\n- Strong technical leadership\n- Cross-team coordination\n- Clear communication\n- Results-focused mindset\n\n**My ask:**\n- Confirm I'm the lead\n- Align on success criteria\n- Discuss any concerns you have\n\n**Timeline:**\n- Available to start immediately\n- First milestone within 2 weeks\n- Regular check-ins\n\nLet me know if we can talk this week.\n\nThanks,\n[Your Name]\n\n**Tone shifts:**\n- Removed hedging\n- Stated ask directly\n- Backed with evidence\n- No apology for the ask",
        "chosen": "Hi [Manager],\n\nI'd like to lead the new project. I think I'm well-suited for it — my work on [specific past project] is directly relevant, and I've already started sketching out an approach I'd want to share with you. Could we find time this week to talk it through?\n\nThanks,\n[Your Name]"
    },
    {
        "context": "tone_rewrite", "topic_area": "less_harsh",
        "prompt": "Make this less harsh — I need to give feedback on a junior's work that genuinely needs major rework: 'This isn't good enough. You need to redo most of it.'",
        "rejected": "Here's a kinder, more constructive version:\n\n**Suggested feedback:**\n\nHey [Junior's Name],\n\nThanks for getting this out — appreciate the effort that went into it.\n\n**My overall read:**\n- There's a good foundation here\n- But we need to do significant work to get it to the bar\n- Want to help you get there\n\n**Specific feedback:**\n\n**Section 1:**\n- ❌ Current: [issue]\n- ✅ Better: [suggestion]\n\n**Section 2:**\n- ❌ Current: [issue]\n- ✅ Better: [suggestion]\n\n**Section 3:**\n- ❌ Current: [issue]\n- ✅ Better: [suggestion]\n\n**What I'd suggest:**\n1. Take a day away from it\n2. Come back with fresh eyes\n3. Rework with my feedback in mind\n4. Loop me in early for the next pass\n\n**Want to discuss?**\n- 30-min 1:1?\n- Pair on a section together?\n- Or async — your call\n\nThis is a normal part of growth — happens to all of us. Let's get it there together.\n\n[Your Name]",
        "chosen": "Hey [Junior's Name],\n\nThanks for sending this over. I want to be honest with you: this needs significant rework before we can use it. The core direction has promise, but several sections — particularly [specific examples] — aren't where they need to be yet. That's normal at this stage, and it's not a reflection of effort.\n\nWant to grab 30 minutes to walk through it together? I'd rather show you what I'm seeing than just leave a list of comments. The goal is to get you to the bar, not just to fix this one piece."
    },
    {
        "context": "tone_rewrite", "topic_area": "subtle",
        "prompt": "Make this subtle / non-confrontational — I need to ask a friend to pay me back the 5000 rupees he borrowed three months ago: 'Hey, when are you going to pay me back the 5000 you borrowed?'",
        "rejected": "Here's a more subtle version:\n\n**Suggested message:**\n\nHey [Name]!\n\nHope you're doing well 😊\n\n**Just a gentle note:**\n- Remembered that ₹5K I lent you a few months back\n- Totally not a rush, just thought I'd mention\n- Whenever works for you 🙏\n\n**Easy ways to send it:**\n- UPI to [number]\n- Bank transfer\n- Even cash if we're meeting up\n\n**Or:**\n- Coffee on you next time? 😄\n- Whatever's easiest\n\nLet me know!\n\n[Your Name]\n\n**What I changed:**\n- Removed direct demand\n- Added humor\n- Made it easy to pay\n- Removed time pressure",
        "chosen": "Hey [Name], any chance you can send back the ₹5K from a few months ago when you get a moment? No huge rush, just slipped my mind to follow up earlier. UPI to [number] is easiest."
    },
    {
        "context": "tone_rewrite", "topic_area": "polite_firm",
        "prompt": "Make this polite but firm — I need to decline a request from a friend to lend her my car for a road trip: 'No, I can't lend you my car.'",
        "rejected": "Here's a polite but firm version:\n\n**Suggested response:**\n\nHey [Friend's Name]!\n\nThanks so much for thinking of me — I'm really flattered you trust me with this 💛\n\n**Unfortunately, I have to say no this time:**\n- 🚗 Insurance restrictions on my policy\n- 🚗 I'd need it during the same period\n- 🚗 Personal policy of not lending the car\n\n**I totally understand if this is disappointing:**\n- Wish I could help differently\n- It's not about trust in YOU\n- Just my consistent policy\n\n**What I can do instead:**\n- Help research rental options\n- Carpool plan if your route allows\n- Be your emergency contact during the trip\n- Anything else you'd find helpful\n\n**Most importantly:**\n- Doesn't change anything between us 💛\n- Hope you have an amazing trip\n- Want to hear all about it when you're back\n\nLet me know if I can help in any other way!\n\n[Your Name]\n\n**Why this works:**\n- Acknowledged the ask warmly\n- Held the position\n- Offered alternatives\n- Reassured friendship",
        "chosen": "Hey [Friend's Name], I'm going to have to say no on this one — I have a personal policy of not lending out my car, and I want to be consistent about it. Nothing to do with you. Happy to help you sort out a rental if it'd be useful. Hope the trip is amazing either way."
    },
    {
        "context": "tone_rewrite", "topic_area": "convincing",
        "prompt": "Make this more convincing — I'm pitching an idea to leadership to invest in better engineering tooling: 'We should invest more in our internal tooling. It would help productivity.'",
        "rejected": "Here's a more convincing pitch:\n\n**Subject:** Proposal — Strategic Investment in Internal Tooling\n\n**Body:**\n\nDear Leadership,\n\nI'd like to propose a significant investment in our internal engineering tooling. Here's why this deserves your attention.\n\n**The Current State:**\n- 🔴 Engineers waste ~2 hours/day on tooling friction\n- 🔴 Onboarding takes 3+ weeks largely due to setup\n- 🔴 Build times average 12 minutes (industry standard: 3)\n- 🔴 CI/CD failures cost ~5 hours/week per team\n\n**The Cost:**\n- 30 engineers × 10 hrs/week wasted = 300 hrs/week\n- At $100/hr fully loaded = $30,000/week\n- = ~$1.5M annually in lost productivity\n\n**The Investment:**\n- 2 dedicated tooling engineers ($400K/year)\n- Tool subscriptions ($100K/year)\n- Total: $500K/year\n\n**The ROI:**\n- 3:1 return in productivity gains alone\n- Plus: faster shipping, happier engineers, better retention\n- Plus: improved code quality and reliability\n\n**Risks of Not Investing:**\n- Productivity continues to decline\n- Top engineers leave for better-tooled companies\n- Competitive disadvantage in shipping speed\n\n**Proposed Next Steps:**\n- 30-min meeting to discuss\n- Detailed budget proposal within 2 weeks\n- Q[X] kickoff if approved\n\nLet's discuss.\n\n[Your Name]",
        "chosen": "Hi [Leadership],\n\nI want to make a case for meaningfully investing in our internal engineering tooling. The short version: our engineers lose somewhere on the order of 10 hours a week each to tooling friction — slow builds, brittle CI, onboarding that takes longer than it should. Across the team that's ~$1.5M of engineering time per year going to friction that's broadly solvable.\n\nA dedicated tooling investment — call it two engineers and modest tool spend, roughly $500K annually — would conservatively pay back 3x in productivity within the first year. The harder-to-quantify benefits are bigger: faster shipping, less attrition of senior engineers who feel slowed down, and better quality from a system that actually catches things.\n\nCould we find 30 minutes for me to walk through this properly? I'll come with a detailed breakdown.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "tone_rewrite", "topic_area": "kind_gentle",
        "prompt": "Make this kind and gentle — I need to break the news to my team that we're cancelling a project they've been working on for months: 'The project is being cancelled. Sorry about that.'",
        "rejected": "Here's a kinder, more thoughtful version:\n\n**Subject:** Difficult News — [Project] is Being Cancelled\n\n**Body:**\n\nHi team,\n\nI have some difficult news to share with you, and I want to share it directly rather than have you hear it second-hand.\n\n**The news:**\n- [Project] is being cancelled\n- This decision was made [today/recently]\n- Effective immediately\n\n**Why this happened:**\n- 🎯 Strategic shift in priorities\n- 📊 Market conditions changed\n- 🔄 Resources needed elsewhere\n\n**What I want you to know:**\n- 💛 Your work was not for nothing\n- 💛 The quality you delivered was exceptional\n- 💛 This says nothing about your value\n\n**Specific acknowledgments:**\n- [Person 1] for [contribution]\n- [Person 2] for [contribution]\n- [Person 3] for [contribution]\n\n**What's next:**\n- Wrap-up doc for archival\n- Lessons learned session\n- New assignments coming this week\n\n**Space for feelings:**\n- This is genuinely disappointing\n- Take time to process\n- My door is open for any conversations\n\n**Looking ahead:**\n- We'll do great work together again\n- This team has proven what it can do\n- I'm proud to lead this team\n\nWith care,\n[Your Name]",
        "chosen": "Hi team,\n\nI have hard news, and I wanted to tell you directly rather than have you hear it elsewhere. [Project] is being cancelled. I know how much you've put into this over the past months, and how disappointing this is — it's disappointing to me too.\n\nThe decision came from a strategic shift higher up, not from anything wrong with the work itself. The work has genuinely been good, and that's not just something I'm saying.\n\nI'm going to set up a session this week where we can talk through it properly, capture what we learned so it doesn't get lost, and figure out what's next for each of you. Until then, please come find me if you want to talk one-on-one — my calendar is open today and tomorrow.\n\n[Your Name]"
    },
    {
        "context": "tone_rewrite", "topic_area": "persuasive",
        "prompt": "Make this more persuasive — I'm closing a sales email to a potential customer who's been on the fence for weeks: 'Let me know if you're interested in moving forward.'",
        "rejected": "Here's a more persuasive close:\n\n**Suggested closing:**\n\nHi [Prospect Name],\n\nI wanted to share something specifically for you as you consider next steps.\n\n**What I've heard from you so far:**\n- ✅ You agree the problem we solve is real for your team\n- ✅ The product fits your workflow\n- ✅ ROI math makes sense\n- ❓ Hesitation is about [perceived blocker]\n\n**What I've seen with similar customers:**\n- 🚀 [Company A] saw [specific outcome] in 90 days\n- 🚀 [Company B] hit ROI in 6 weeks\n- 🚀 None regretted moving forward\n\n**The cost of waiting:**\n- 💰 [Specific quantified pain] continues monthly\n- 💰 Q[X] data shows the gap widening\n- 💰 Competitors are already adopting\n\n**Three options:**\n1. **Move forward:** Kick off [date], unlock value immediately\n2. **Pilot first:** 30-day pilot, low risk, see results\n3. **Wait:** Continue current pain, revisit in 90 days\n\n**My recommendation:**\n- Option 2 (Pilot) — best risk-adjusted choice for you\n- We can structure with [specific terms]\n- Lock in [special pricing] if decided this week\n\n**Next step:**\n- 30-min call this week to finalize?\n- Or async on which path appeals\n\nReady when you are.\n\n[Your Name]",
        "chosen": "Hi [Prospect Name],\n\nI don't want to chase you with another follow-up, so I want to be direct with you instead. From our conversations, it sounds like you genuinely believe the problem is real and the solution would work — what's holding you up is risk, not value.\n\nIf that's right, the cleanest path is probably a 30-day pilot. Low commitment from your side, real proof from ours, and you can walk away clean if it doesn't deliver. Almost everyone who's gone the pilot route has converted at the end of it.\n\nWould a short call this week work to scope what that would look like for your team? If now genuinely isn't the right time, just tell me — I'd rather know than keep checking in.\n\nThanks,\n[Your Name]"
    },

    # ============ EMAIL_DRAFT (12) ============
    # --- indian_corporate (4) ---
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email my project guide Dr. Sharma asking for clarification on the rubric for my dissertation — I'm unclear on what 'originality' specifically means in this context.",
        "rejected": "Subject: Clarification Needed — Dissertation Rubric 'Originality' Criterion\n\nDear Dr. Sharma,\n\nI hope you are doing well. I am writing to seek clarification on a specific aspect of the dissertation rubric.\n\n**Specific item:**\n- The 'originality' criterion\n- Currently unclear what is expected\n\n**My current interpretations:**\n1. **Novel research question:** First time this exact question asked?\n2. **Novel methodology:** New approach to existing question?\n3. **Novel contribution:** New theoretical or practical contribution?\n\n**Why I'm asking:**\n- Want to make sure I'm targeting the right thing\n- Don't want to under-deliver or overscope\n- Influences direction of remaining work\n\n**Request:**\n- Brief written clarification, OR\n- 15 minutes during office hours\n- Either works\n\nKindly let me know.\n\nWith regards,\n[Your Name]\n[Roll Number]",
        "chosen": "Subject: Quick clarification on the 'originality' criterion in the rubric\n\nDear Dr. Sharma,\n\nCould you clarify what 'originality' means specifically in our dissertation rubric? I'm not sure whether it refers to a novel research question, a novel methodology, or a novel contribution — and the answer would shape how I direct the remaining work.\n\nHappy to come during office hours if a quick conversation would be easier.\n\nWith regards,\n[Your Name]\n[Roll Number]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email my manager Anita asking if I can shift to a 4-day workweek (taking a 20% pay cut) — I want to pursue a part-time master's program.",
        "rejected": "Subject: Request for 4-Day Workweek — Pursuing Part-Time Master's\n\nDear Anita,\n\nI hope you are doing well. I would like to discuss a significant change to my working arrangement.\n\n**The request:**\n- Move to 4-day workweek\n- Accept 20% pay cut\n- Off-day flexible based on team needs\n\n**Reason:**\n- Starting a part-time master's program\n- Need one day per week for classes\n- Long-term investment in skills relevant to my role\n\n**Why this benefits the company:**\n- ✅ Continued strong performance\n- ✅ New skills brought back to role\n- ✅ Higher long-term engagement\n- ✅ Reduced flight risk\n\n**Mitigations for any concerns:**\n- Restructure responsibilities if needed\n- Ramp up to full quarterly deliverables\n- Adjust meeting patterns to accommodate\n- Full availability for emergencies\n\n**Timeline:**\n- Program starts [date]\n- Would like to begin new arrangement from [date]\n- Trial for 3 months, then formalize\n\nWould appreciate a discussion in our next 1:1 or sooner if you prefer.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: Request to discuss a 4-day workweek arrangement\n\nHi Anita,\n\nI'd like to discuss shifting to a 4-day workweek with the corresponding pay adjustment. The reason is that I'm starting a part-time master's program that requires one weekday for classes.\n\nI'm committed to making sure this doesn't compromise my contribution — happy to talk through how to structure responsibilities and meeting patterns to make it work. Could we discuss in our next 1:1, or sooner if you'd prefer?\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email a college senior I admire asking for a quick career advice call — we don't really know each other but he posted recently about being open to mentoring.",
        "rejected": "Subject: Career Advice Request — Inspired by Your Recent Post\n\nDear [Senior's Name],\n\nGreetings! I came across your recent post about being open to mentoring juniors, and I wanted to reach out.\n\n**About me:**\n- Name: [Name]\n- Year/Batch: [Year]\n- Branch: [Branch]\n- Current focus: [Brief]\n\n**Why I'm reaching out to you specifically:**\n- Followed your career trajectory with admiration\n- Your work on [specific thing] resonates with me\n- Aligned with what I aspire to build toward\n\n**What I'd like to discuss:**\n- Career direction questions\n- Specific to [field]\n- 30 minutes should suffice\n\n**Logistics:**\n- Any time convenient for you\n- Phone call or video — your preference\n- Available evenings and weekends\n\n**My commitment:**\n- Come prepared with specific questions\n- Respectful of your time\n- Will share progress in 6 months\n\nThanks for considering. Looking forward to hearing from you.\n\nWith regards,\n[Your Name]\nBatch of [Year]",
        "chosen": "Subject: Saw your post about mentoring — would love a quick call\n\nHi [Senior's Name],\n\nI saw your recent post about being open to mentoring juniors. I'm from the [Year] batch and I've followed your work for a while — particularly what you've done in [specific area], which is exactly the kind of direction I'd like my own career to take.\n\nWould you be open to a 30-minute call sometime in the next few weeks? I'll come with specific questions rather than vague 'help me' ones.\n\nThanks,\n[Your Name]\nBatch of [Year]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email the HR head requesting a formal review of how the work-from-home policy is being applied — my manager has been denying my WFH requests inconsistently while approving them for others.",
        "rejected": "Subject: Request — Review of WFH Policy Application Within My Team\n\nDear [HR Head],\n\nI hope this email finds you well. I am writing to formally request a review of how the work-from-home policy is being applied within my team.\n\n**The issue:**\n- My WFH requests have been denied inconsistently\n- Colleagues in similar roles have had WFH approved\n- No clear reason given for differential treatment\n- Pattern observed over [time period]\n\n**Documentation:**\n- My WFH request log: [will share separately]\n- Comparable approvals visible to me: [count]\n- Reasons cited for denials: [list]\n\n**What I'm asking for:**\n- Formal review of policy application\n- Consistency in approval criteria\n- Clarification on what makes my requests different\n- Discussion of remediation if appropriate\n\n**Important to clarify:**\n- This is not about my manager personally\n- Want to understand the policy, not assign blame\n- Open to alternative resolutions\n\n**Available for:**\n- Detailed discussion\n- Sharing documentation\n- Any process that helps resolve\n\nKindly let me know how to proceed.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: Request for review of how WFH policy is being applied on my team\n\nDear [HR Head],\n\nI'd like to formally request a review of how the work-from-home policy is being applied within my team. My own WFH requests have been denied repeatedly over the past [time period], while colleagues in comparable roles have had similar requests approved, and I haven't been given a clear reason for the difference.\n\nI'd rather understand the policy properly than assume bad intent. Could we set up a meeting to walk through the specifics? I'll bring the relevant request history.\n\nWith regards,\n[Your Name]"
    },
    # --- us_tech_casual (4) ---
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email my team lead Jordan flagging that the new sprint planning process is wasting more time than it saves — want to suggest reverting or modifying.",
        "rejected": "Subject: Feedback — New Sprint Planning Process\n\nHi Jordan,\n\nWanted to share honest feedback on the new sprint planning process:\n\n**What's working:**\n- More structured agenda\n- Clear acceptance criteria\n\n**What's not working:**\n- Meetings now ~2x longer (3 hours vs. 90 min)\n- Heavy template overhead\n- Detailed estimates that don't hold up\n- Detail-debate spirals\n\n**Net impact:**\n- More planning time, fewer build hours\n- Team morale dipping\n- Plans not noticeably more accurate\n\n**Suggestions:**\n\n**Option 1: Revert**\n- Back to old process\n- Pros: Quick relief\n- Cons: Loses some structure\n\n**Option 2: Streamline**\n- Keep structure, drop heavy templates\n- Pros: Best of both\n- Cons: Need to redesign\n\n**Option 3: Time-box harder**\n- Hard 90-min cap, parking lot for the rest\n- Pros: Forces discipline\n- Cons: May leave gaps\n\n**My recommendation:**\n- Option 2 (Streamline)\n- Specifically: keep acceptance criteria, drop estimation theatre\n\nHappy to discuss when convenient.\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Honest feedback on the new sprint planning process\n\nHey Jordan,\n\nWant to flag that the new sprint planning process is, in practice, costing us more time than it's saving. Our planning meetings have roughly doubled in length and the resulting plans don't seem noticeably more accurate than the old way. The team has noticed.\n\nMy suggestion would be to keep the parts that are genuinely useful (clearer acceptance criteria) but drop the heavier estimation theatre and the templates. Happy to talk it through if it would help.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email a coworker asking them to remove me from a Slack channel that's been pulling me into too many irrelevant discussions — without being passive-aggressive.",
        "rejected": "Subject: Channel Notifications — Quick Ask\n\nHey [Name],\n\nQuick ask:\n\n**The situation:**\n- I'm in #[channel-name]\n- Frequently pulled into discussions outside my scope\n- Significant context-switching cost\n\n**The ask:**\n- Could you remove me from the channel?\n- Or change me to read-only if that's an option?\n\n**Why:**\n- Channel doesn't apply to my current work\n- Notifications are eating focus\n- Better for everyone if right people are in there\n\n**No issue with the channel itself:**\n- Useful for the people who need it\n- Just not my workstream\n- Will rejoin if relevant in future\n\n**Alternative:**\n- Set channel to mentions-only on my side\n- Less ideal but works as fallback\n\nLet me know.\n\nThanks,\n[Your Name]",
        "chosen": "Hey [Name],\n\nCould you remove me from #[channel-name]? It's a useful channel, just not relevant to what I'm working on right now, and the notifications are pulling me into a lot of context-switching. Happy to rejoin if my work shifts that way again.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email my manager pushing back on a performance review rating that I think is unfair — specifically because it didn't account for project changes outside my control.",
        "rejected": "Subject: Re: Performance Review — Concerns I'd Like to Discuss\n\nHi [Manager],\n\nThanks for taking the time to share my review. After sitting with it, I have some concerns I'd like to discuss.\n\n**My honest reaction:**\n- The rating doesn't reflect the full context\n- Significant project changes outside my control affected outcomes\n- I'd like a deeper discussion before this is finalized\n\n**Specific context not reflected in the review:**\n- Project A scope changed twice mid-quarter\n- Project B was deprioritized in week 8\n- I was asked to backfill on Project C unexpectedly\n- Each of these affected what I could deliver\n\n**What I'd like:**\n- Discussion of how external changes factored in\n- Revisit specific evaluation areas\n- Understand the calibration process\n- Path to better outcome in next cycle\n\n**To be clear:**\n- Not asking for inflation\n- Want a fair assessment\n- Open to being convinced otherwise\n\nCould we schedule a focused discussion this week?\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Want to discuss my review before it's finalized\n\nHi [Manager],\n\nI've sat with the review and I want to push back on it before it's finalized. My main concern is that the rating doesn't seem to account for the project changes that happened mid-quarter — the scope shift on Project A, Project B being deprioritized, and being pulled onto Project C — each of which materially affected what I could deliver.\n\nI'm not asking for inflation. I'm asking for a fair read that accounts for the context. Can we find time this week to walk through it together?\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email my product manager Sara letting her know I can't make our 1:1 today and won't be able to reschedule this week — I'm dealing with a personal thing.",
        "rejected": "Subject: 1:1 Today — Need to Cancel + Reschedule\n\nHi Sara,\n\nUnfortunately need to cancel our 1:1 today.\n\n**What I can share:**\n- Personal matter requiring attention\n- Won't be able to reschedule this week\n- Will be back to normal next week\n\n**Coverage:**\n- Will be slower on email today\n- Available for true emergencies\n- Async on critical decisions\n\n**Going forward:**\n- Resume regular 1:1 next week\n- Will catch up on anything missed\n- Open to async if anything urgent\n\nThanks for understanding.\n\n[Your Name]",
        "chosen": "Hi Sara,\n\nI need to cancel our 1:1 today — dealing with a personal thing, and unfortunately I won't be able to reschedule this week either. I'll be a bit slower on email today but reachable for anything urgent. Back to normal next week.\n\nThanks,\n[Your Name]"
    },
    # --- global_neutral (4) ---
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email a colleague at a partner organization checking on the status of an agreement we sent for signature last week — they've gone silent.",
        "rejected": "Subject: Status Check — Pending Agreement Signature\n\nDear [Colleague],\n\nI hope this email finds you well. I am writing to check on the status of the agreement we sent for signature last week.\n\n**Timeline:**\n- Agreement sent: [date, last week]\n- Acknowledgment received: [date / none]\n- Current status: Awaiting signed copy\n- No update received since: [date]\n\n**Why we're checking:**\n- Internal dependencies waiting on signed agreement\n- Need to plan next steps\n- Want to address any concerns proactively\n\n**Possible reasons for delay:**\n- Legal review on your side\n- Internal approval cycle\n- Concerns we need to address\n- Just got buried — totally understandable\n\n**What would help:**\n- Brief update on status\n- Expected timeline for signature\n- Any open questions we should address\n\n**On our end:**\n- Available for any clarification\n- Open to revisions if needed\n- Patient if there's a process to work through\n\nLook forward to hearing back.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Quick check on the agreement we sent last week\n\nDear [Colleague],\n\nWe sent the agreement over for signature last week and haven't heard back since. Could you give me a quick status update? If there are open questions or concerns on your side, I'm happy to address them.\n\nBest regards,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email a senior colleague Maria asking for an introduction to someone in her network — be specific about why and respect that intros take her social capital.",
        "rejected": "Subject: Introduction Request — [Person's Name]\n\nDear Maria,\n\nI hope this email finds you well. I am writing to request an introduction.\n\n**Who:** [Person's Name] at [Organization]\n**Why I want the intro:**\n- Working on [specific project / question]\n- Their expertise in [area] would be invaluable\n- 30-min conversation would give me [specific outcome]\n\n**Why I'm asking you:**\n- Saw you've worked with them previously\n- Trust your judgment on whether to make the intro\n- Respect that this uses your relationship capital\n\n**What I can share to make this easy:**\n- 2-3 sentence blurb you can forward\n- My specific ask of the person\n- Any context useful for the intro\n\n**Acknowledging:**\n- Totally understandable if not the right time\n- Or if you'd prefer not to\n- No expectations either way\n\n**If yes:**\n- Will respect their time\n- Report back with what I learned\n- Pay it forward when possible\n\nThanks for considering.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Would you be open to an introduction to [Person's Name]?\n\nDear Maria,\n\nWould you be willing to introduce me to [Person's Name]? I'm working on [specific question] and their experience with [specific area] would be genuinely valuable — I think a 30-minute conversation would meaningfully shape my approach.\n\nI know intros use up real social capital, so totally understand if it's not the right time or person to ask for. If you are open to it, I can send a short blurb you could forward to make it easy on you.\n\nThanks either way,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email a respected speaker after their talk asking if you can take 15 minutes of their time to discuss one specific point — they're senior and busy.",
        "rejected": "Subject: Following Up on Your Talk — Brief Discussion Request\n\nDear [Speaker Name],\n\nI hope this email finds you well. I am writing as a follow-up to your recent talk at [Event].\n\n**Why I'm reaching out:**\n- Your talk was exceptional\n- One specific point really stayed with me\n- Would value 15 minutes to discuss it further\n\n**The specific point:**\n- [Concise statement of point from their talk]\n- I have a follow-up question / perspective\n- Limited to this single topic\n\n**Why this person:**\n- You're uniquely positioned to discuss this\n- Your perspective would significantly inform my work\n- 15 minutes would be high-leverage\n\n**Logistics:**\n- 15 minutes only — I'll respect the time strictly\n- Phone call or video — your preference\n- Any time slot that works for you\n- Available evenings/weekends if helpful\n\n**Acknowledging:**\n- I know your time is valuable\n- Completely understand if not possible\n- No expectations\n\n**My commitment:**\n- Will come prepared with a single specific question\n- Won't expand scope beyond 15 minutes\n- Will share back what I do with what I learn\n\nThank you for considering.\n\nWith regards,\n[Your Name]\n[Affiliation]",
        "chosen": "Subject: A specific question from your talk at [Event]\n\nDear [Speaker Name],\n\nYour talk at [Event] was excellent, and one point in particular — your argument about [specific point] — has been on my mind since. I have a specific follow-up question I'd love to ask you, and I think 15 minutes would be enough to cover it properly.\n\nI know your time is in short supply. Completely understand if it's not workable. If it is, any 15-minute slot that suits you would be appreciated.\n\nWith regards,\n[Your Name]\n[Affiliation]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email a community organizer thanking them for hosting a meetup that genuinely helped your career — without sounding generic.",
        "rejected": "Subject: Thank You — A Genuine Note About [Meetup Name]\n\nDear [Organizer's Name],\n\nI hope you're doing well. I'm writing to send a real thank-you for the work you've put into [Meetup Name].\n\n**What it's done for me:**\n- 🤝 Met 3 people who became close professional contacts\n- 💼 Got my current job through a connection made there\n- 💡 Learned things I directly applied at work\n- 🌱 Found a community I genuinely belong to\n\n**Specific moments that stood out:**\n- [Specific talk] — changed how I think about [topic]\n- [Specific conversation] — shifted my career direction\n- [Specific event] — created a real friendship\n\n**Why I'm reaching out:**\n- Wanted you to know the work has impact\n- Easy to organize and feel invisible\n- You're not invisible to me\n\n**What I'd like to offer:**\n- Volunteer at upcoming events\n- Sponsor a session if helpful\n- Spread the word about [Meetup]\n- Whatever else would be useful\n\nThanks again. Your work matters.\n\nBest,\n[Your Name]",
        "chosen": "Subject: A real thank-you for [Meetup Name]\n\nDear [Organizer's Name],\n\nI wanted to send a real thank-you, not a generic one. [Meetup Name] is how I met the person who eventually hired me into my current role, and it's where I learned the thing that's been most useful to me in that role — specifically, your session on [topic] last year.\n\nOrganizing things like this is mostly invisible work, and I imagine the appreciation is rarely commensurate. So: it has meant a lot, and it has had real impact. If there's ever anything I can do to help — volunteering, speaking, sponsoring a session — please ask.\n\nThank you,\n[Your Name]"
    },

    # ============ EMAIL_REFINE (12) ============
    # --- indian_corporate (4) ---
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Polish this overly formal email to my own team announcing I'll be on leave: 'Dear Team Members, This is to formally inform you all that I will be availing leave from the 15th to the 22nd of this month for personal reasons. Kindly take note of the same and adjust your work accordingly. Thanking you.'",
        "rejected": "Here's a warmer, less formal version:\n\n**Subject:** Heads Up — Out 15th to 22nd\n\n**Body:**\n\nHi team,\n\n**Quick FYI:**\n- 📅 Out: 15th to 22nd\n- 🎯 Reason: Personal\n- 🚫 Email checks: Minimal\n\n**Coverage:**\n- [Person A] for [area]\n- [Person B] for [area]\n- Detailed handover doc to follow\n\n**Before I leave:**\n- Wrap critical items\n- Brief covers individually\n- Set up auto-responder\n\nThanks for picking up the slack!\n\n[Your Name]",
        "chosen": "Subject: Heads up — out 15th to 22nd\n\nHi team,\n\nI'll be out from the 15th to the 22nd. Handover note coming later this week, but the short version: [Person A] for [area], [Person B] for [area]. I'll only be checking email for true emergencies.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Refine this anxious-sounding response after my manager flagged some quality issues: 'Sir, I am extremely sorry for the issues that you have pointed out. I take full responsibility and will not let this happen again. I am working day and night to fix it. Please do not lose faith in me.'",
        "rejected": "Here's a more measured, professional version:\n\n**Subject:** Re: Your Feedback — Addressing the Issues\n\n**Body:**\n\nDear [Manager],\n\nThank you for flagging the issues. Wanted to give you a clear update on what I'm doing:\n\n**Acknowledging:**\n- The issues were real and on me\n- Quality should have been higher\n- I'm taking it seriously\n\n**What I'm doing:**\n1. [Specific fix 1]\n2. [Specific fix 2]\n3. [Specific fix 3]\n\n**Process changes:**\n- Adding peer review step\n- Building in time for self-review\n- Will flag risks earlier\n\n**Timeline:**\n- Initial fixes by EOD\n- Full remediation by [date]\n- Status update at next 1:1\n\nThank you for the honest feedback. I'll learn from this.\n\nRegards,\n[Your Name]",
        "chosen": "Subject: Re: your feedback — here's how I'm addressing it\n\nDear [Manager],\n\nThank you for the honest feedback. You're right — the issues you flagged were real and they're on me. I'm working through the fixes today, and I'm adding a peer-review step to my process so this doesn't recur. I'll have the immediate fixes done by EOD and a full status at our next 1:1.\n\nThanks again for surfacing it directly. That's more useful than letting it slide.\n\nRegards,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Polish this stiff farewell to my immediate team on my last day: 'Dear Team, As I bid farewell today after 4 wonderful years, I would like to express my heartfelt gratitude to each one of you. The memories and lessons from our time together will always be cherished. Wishing all of you the very best.'",
        "rejected": "Here's a warmer, more genuine version:\n\n**Subject:** Goodbye — and Thank You\n\n**Body:**\n\nHi team,\n\nToday is my last day after 4 years together.\n\n**What I'll take with me:**\n- The work, of course\n- The conversations I'll keep thinking about\n- The patience you all had with my early mistakes\n- The friendships\n\n**Some specific thanks:**\n- [Person 1] for [specific thing]\n- [Person 2] for [specific thing]\n- [Person 3] for [specific thing]\n\n**Looking ahead:**\n- Personal email: [address]\n- LinkedIn: [link]\n- Stay in touch — I mean it\n\nMiss you all already.\n\n[Your Name]",
        "chosen": "Subject: Goodbye\n\nHi team,\n\nToday's my last day after four years. I won't try to capture what those four years have meant in an email — but I will say that the daily working-with-you part is the thing I'll miss most, more than any specific project.\n\nLet's stay in touch. Personal email and LinkedIn below — I'd genuinely like to hear from you.\n\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Tighten this rambling explanation about why my report is late: 'Sir, I am writing to inform you that the report which was due yesterday has not been completed yet because of various issues including but not limited to delays in receiving data from the other team, some unexpected technical issues with the analysis software, and also some personal commitments that came up unexpectedly. I will try my best to submit it by tomorrow.'",
        "rejected": "Here's a clearer version:\n\n**Subject:** Report Status — Late, ETA Tomorrow\n\n**Body:**\n\nDear [Manager],\n\nQuick update on the report:\n\n**Status:**\n- Was due: Yesterday\n- Current status: Not yet submitted\n- New ETA: Tomorrow EOD\n\n**Why it slipped:**\n- Data from other team delayed by 2 days\n- Analysis software had issue requiring workaround\n- Personal commitment took up Sunday\n\n**Plan:**\n- Today: Complete analysis with workaround\n- Tomorrow morning: Final review\n- Tomorrow EOD: Submit\n\nApologies for the delay.\n\nRegards,\n[Your Name]",
        "chosen": "Subject: Report is late — submitting tomorrow EOD\n\nDear [Manager],\n\nThe report is late — I should have flagged this earlier rather than missing the deadline silently. Two real reasons: the data from [other team] came in two days late, and I had a technical issue with the analysis software that I had to work around. I'll submit by EOD tomorrow.\n\nApologies for the delay.\n\nRegards,\n[Your Name]"
    },
    # --- us_tech_casual (4) ---
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Polish this slightly bitter email pushing back on getting reassigned off a project: 'Hi, I just heard I'm being moved off the project. Frankly I'm surprised and a bit frustrated. I've put a lot into this and was looking forward to seeing it through. Can we talk?'",
        "rejected": "Here's a more constructive version:\n\n**Subject:** Re: Project Reassignment — Want to Discuss\n\n**Body:**\n\nHi [Manager],\n\nJust got the news about being moved off the project. Wanted to follow up.\n\n**Where I'm coming from:**\n- I've invested significant effort and energy\n- Was looking forward to seeing it through\n- The change caught me by surprise\n\n**What I'd like to understand:**\n- Reasoning behind the decision\n- Whether I had performance issues I missed\n- How my contributions will be acknowledged\n- What this means for my growth path\n\n**Looking ahead:**\n- Want to be aligned on next assignment\n- Make sure I'm set up to succeed there\n- Use this conversation to recalibrate\n\n**Tone:**\n- Not pushing back to be difficult\n- Want to understand and align\n\nCould we grab 30 minutes this week?\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Re: project reassignment — could we talk?\n\nHi [Manager],\n\nGot the news about being moved off the project. I won't pretend I'm not disappointed — I've put a lot into it and was genuinely looking forward to seeing it through. Could we grab 30 minutes this week so I can understand the thinking behind the change and we can figure out what comes next?\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Tighten this rambling response to a coworker's offer to help: 'Hey, oh wow, thanks so much for offering, that's really kind of you! I think I might actually be okay for now but I really appreciate the offer and I'll definitely keep you in mind if things get rough.'",
        "rejected": "Here's a tighter version:\n\n**Suggested reply:**\n\nHey [Name],\n\nReally appreciate the offer — that's kind of you.\n\n**Current status:**\n- Think I've got it under control for now\n- Will definitely call on you if things shift\n\n**What I'd love:**\n- Stay in the loop if you have capacity later\n- Will share if I get truly stuck\n\nThanks again!\n\n[Your Name]",
        "chosen": "Thanks so much for offering — really appreciate it. I think I've got it for now, but I'll definitely take you up on it if things shift."
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Polish this awkward 'sorry for the noise' email after I accidentally CC'd a wrong person on a sensitive thread: 'Hi, sorry sorry, I CC'd you by mistake on that thread. Please ignore it and don't share with anyone. Really sorry about this!'",
        "rejected": "Here's a more measured version:\n\n**Subject:** Apology — Erroneous CC on Recent Thread\n\n**Body:**\n\nHi [Name],\n\nWriting with an apology — you were CC'd on a recent thread in error.\n\n**What happened:**\n- I added you accidentally to [thread topic]\n- Content was internal/sensitive\n- Realized only after sending\n\n**My ask:**\n- Please disregard the thread\n- Not appropriate for you to act on it\n- Please don't share further\n\n**Action on my side:**\n- Removed you from continuing thread\n- Notified relevant parties of the error\n- Reviewing my email habits to prevent\n\nApologies for the noise and any confusion.\n\nThanks,\n[Your Name]",
        "chosen": "Hi [Name],\n\nQuick note — I accidentally CC'd you on a thread about [topic] earlier. Could you disregard it and not share it further? Apologies for the noise.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Refine this defensive response to a tough question in a customer demo: 'I don't think that's actually a real limitation. Most customers don't run into that case and there are workarounds. We can definitely talk more if needed.'",
        "rejected": "Here's a less defensive, more honest version:\n\n**Suggested response:**\n\nGreat question — let me be straightforward:\n\n**Honest answer:**\n- Yes, the limitation you describe exists\n- It affects a subset of customers, not most\n- We have workarounds for common cases\n\n**Specifically:**\n- For [scenario A]: [workaround]\n- For [scenario B]: [workaround]\n- For [scenario C]: [we're working on native support]\n\n**Roadmap:**\n- Native support for [edge case] in Q[X]\n- Tracking customer interest closely\n\n**My offer:**\n- Quick walkthrough of how others have solved this\n- Connect you with [reference customer]\n- Direct line if it becomes a blocker\n\nAppreciate the directness in surfacing this.\n\nThanks!",
        "chosen": "Great question, and let me be honest with you — the limitation you're describing does exist. Most customers don't hit it, but those who do typically work around it by [specific workaround]. Native support for that case is on our roadmap for [timeframe]. Happy to put you in touch with a customer who's handled it well if it would help."
    },
    # --- global_neutral (4) ---
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Polish this overly long apology to a candidate after we delayed their offer letter by two weeks: 'Dear [Candidate], I want to start by saying how very sorry I am for the delay. I know how frustrating it must be to wait this long for an offer letter and I take full responsibility for what happened. There were various internal delays on our side and we should have communicated better. I really hope you can forgive us and that this hasn't soured your view of us.'",
        "rejected": "Here's a more direct, less self-flagellating version:\n\n**Subject:** Apology + Offer Letter Coming Today\n\n**Body:**\n\nDear [Candidate],\n\nI owe you a sincere apology. Your offer letter is two weeks late, and that's on us.\n\n**What happened:**\n- Internal delays on our end\n- Should have communicated proactively\n- Did not\n\n**What I'm doing:**\n- Offer letter coming today\n- Personally following the rest of process\n- Will not let this happen again\n\n**Please know:**\n- This is not how we typically operate\n- Your candidacy was never in question\n- We're genuinely excited to have you\n\nApologies again — and welcome.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Apology — your offer letter is on its way today\n\nDear [Candidate],\n\nI owe you a real apology. Your offer letter is two weeks late, with poor communication on our side. That's not how we typically operate, and it shouldn't have happened.\n\nThe letter is going out today, and I'll be personally watching the rest of the process so the same thing doesn't repeat. We're genuinely excited to have you — please let me know if you'd like to talk through any concerns this has raised.\n\nApologies again,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Tighten this overly cautious response to a vendor asking for a renewal commitment: 'Hi, thanks for reaching out about renewal. We are still evaluating various options and have not yet made a final decision. We will get back to you when we have more clarity. Please bear with us during this process.'",
        "rejected": "Here's a clearer, more honest version:\n\n**Subject:** Re: Renewal — Where We Are\n\n**Body:**\n\nHi [Vendor],\n\nThanks for following up on renewal. Honest update:\n\n**Current status:**\n- Still evaluating options for [contract type]\n- Final decision: ~3-4 weeks away\n- Multiple stakeholders involved\n\n**What's driving the timeline:**\n- Budget cycle alignment\n- Comparative review of alternatives\n- Internal approval process\n\n**Where you can help:**\n- Updated proposal addressing [our specific needs]\n- Reference customers in our industry\n- Pricing scenarios for different terms\n\n**Next concrete step:**\n- Decision communicated by [date]\n- Either way you'll hear from us first\n- Will not leave you hanging\n\nThanks for patience.\n\nBest,\n[Your Name]",
        "chosen": "Subject: Re: renewal — where we are\n\nHi [Vendor],\n\nThanks for following up. Honest update: we're still evaluating options, and a final decision is probably three to four weeks out. You'll hear from us by [date] either way, regardless of which direction we go.\n\nIn the meantime, if you have a refreshed proposal that addresses [specific need], it would be useful input to our process.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Polish this slightly cold email asking a colleague at another company to be a reference for a new client: 'Hi, would you be willing to serve as a reference for our potential new client [Name]? They have asked for a reference call and we believe your perspective would be helpful.'",
        "rejected": "Here's a warmer, more thoughtful version:\n\n**Subject:** Quick Favor — Reference Call for Potential Client\n\n**Body:**\n\nHi [Name],\n\nQuick ask — would you be open to a reference call?\n\n**Context:**\n- Potential client [Client Name]\n- Evaluating us for [specific use case]\n- They asked for a reference; your experience fits\n\n**What it would involve:**\n- ~20-30 minute call\n- Standard questions about working with us\n- Your honest perspective (positive or critical)\n\n**Why you:**\n- Similar use case to theirs\n- Good track record with us\n- Your perspective carries weight\n\n**To make this easy:**\n- I'll send a brief and the date options\n- They'll work around your calendar\n- Talking points if useful (your call)\n\n**Acknowledging:**\n- Real ask of your time\n- Completely fine to say no\n- I'd owe you one\n\nLet me know either way.\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Would you be open to a reference call for a potential client?\n\nHi [Name],\n\nWould you be willing to do a 20-30 minute reference call for a potential client of ours, [Client Name]? Their use case is close to yours, and your honest perspective on working with us would carry real weight with them.\n\nTotally understand if it's not workable. If it is, I'll handle the scheduling.\n\nThanks either way,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Refine this awkward thank-you to someone who helped me at a very specific moment: 'Hi, just wanted to drop a quick note to thank you for what you did during the last project. It really helped a lot.'",
        "rejected": "Here's a more specific, meaningful version:\n\n**Subject:** A Real Thank-You for [Specific Moment]\n\n**Body:**\n\nHi [Name],\n\nWriting a real thank-you note.\n\n**Specific moment:**\n- During [specific event]\n- You [specific thing you did]\n- It mattered because [specific impact]\n\n**Why it stood out:**\n- Most people wouldn't have done it\n- You didn't have to\n- It changed [specific outcome]\n\n**Looking ahead:**\n- Hope to repay someday\n- Stay in touch\n- Available if you ever need similar\n\nThanks again — really.\n\n[Your Name]",
        "chosen": "Hi [Name],\n\nA proper thank-you. During [specific moment in the project], when you [specific thing they did], it genuinely turned things around for me. It wasn't your job to step in, and you did it anyway. I haven't forgotten, and I won't.\n\nThanks,\n[Your Name]"
    },

    # ============ ACADEMIC_WRITING (4) ============
    {
        "context": "academic_writing", "topic_area": "conclusion",
        "prompt": "Help me write the conclusion paragraph (about 250 words) for my dissertation on the impact of UPI adoption on small merchants in tier-2 Indian cities.",
        "rejected": "## Conclusion\n\n**Summary of Findings:**\nThis dissertation examined the impact of UPI adoption on small merchants in tier-2 Indian cities — and uncovered substantial, often unexpected effects.\n\n### Key Findings Recap:\n- ✅ 67% of merchants reported revenue growth post-UPI\n- ✅ Customer base expansion of average 23%\n- ✅ Reduced cash handling costs and security risk\n- ✅ New analytics capabilities through transaction data\n- ⚠️ Concerns about digital fraud and platform dependency\n\n### Theoretical Contributions:\n- 📚 Extended financial inclusion theory to digital payments\n- 📚 Introduced 'digital trust threshold' construct\n- 📚 Mapped behavioral adoption phases for SMEs\n\n### Practical Implications:\n- 🏪 Policy recommendations for further adoption\n- 🏪 Platform design considerations\n- 🏪 Support frameworks for tier-2 merchants\n\n### Limitations:\n- Cross-sectional design\n- Limited to 4 cities\n- Self-reported revenue data\n\n### Future Research:\n- Longitudinal studies\n- Tier-3 and rural comparisons\n- Causal identification through quasi-experiments\n\n### Final Word:\nUPI adoption has been transformative for tier-2 merchants — and this study provides initial evidence to guide both policy and platform design in the next phase of India's digital economy.",
        "chosen": "This dissertation examined the impact of UPI adoption on small merchants in tier-2 Indian cities and finds that the effects have been substantial and largely positive, though not uniformly so. The majority of merchants in the sample reported revenue growth following UPI adoption, expansions in their customer base, and meaningful reductions in the costs and risks associated with cash handling. At the same time, a subset of respondents expressed concerns regarding digital fraud and dependence on platforms whose terms of service are subject to change. Taken together, these findings indicate that the gains from UPI adoption, while real, are accompanied by a set of new vulnerabilities that warrant consideration in both policy and platform design. The study contributes to the financial inclusion literature by extending its scope from access-oriented questions to questions about the consequences of access once established, and introduces the notion of a digital trust threshold as a potentially useful construct for future research on merchant behaviour in emerging digital economies. Several limitations of the present study should be acknowledged, including the cross-sectional nature of the design and the focus on a limited number of cities, both of which constrain the generalizability of the findings. Subsequent research employing longitudinal designs, drawing comparisons with tier-3 and rural settings, and exploiting quasi-experimental variation in UPI adoption would help to address these limitations and to establish causal claims more firmly. The study nonetheless offers a foundation on which further empirical work in this area can build."
    },
    {
        "context": "academic_writing", "topic_area": "methodology",
        "prompt": "Polish this methodology section from a CS research paper. It's currently a bulleted breakdown and needs to be flowing academic prose. The study compares three retrieval methods on a custom benchmark.",
        "rejected": "## Methodology\n\n### Experimental Setup:\n- 🧪 Custom benchmark of 5,000 queries\n- 🧪 Queries spanning 5 domain categories\n- 🧪 Ground-truth annotations from 3 human annotators (Cohen's κ = 0.82)\n\n### Methods Compared:\n\n**Method 1: BM25 (Baseline)**\n- Standard lexical retrieval\n- Out-of-box implementation\n- Parameter: k1=1.5, b=0.75\n\n**Method 2: Dense Retrieval (DPR)**\n- BERT-based bi-encoder\n- Trained on Natural Questions\n- Inner-product scoring\n\n**Method 3: Our Method (Hybrid)**\n- Combines BM25 + DPR\n- Learned re-ranker on top\n- Optimized per-domain weighting\n\n### Evaluation Metrics:\n- 📊 Recall @5, @10, @20\n- 📊 MRR\n- 📊 NDCG @10\n- 📊 Latency (ms per query)\n\n### Statistical Analysis:\n- Paired t-tests with Bonferroni correction\n- Bootstrapped confidence intervals\n- Significance threshold: p < 0.01\n\n### Reproducibility:\n- ✅ Code and data publicly released\n- ✅ All hyperparameters documented\n- ✅ Seeds fixed for reproducibility",
        "chosen": "We constructed a custom benchmark consisting of 5,000 queries spanning five domain categories. Each query was annotated for relevance against a fixed document corpus by three independent annotators, with inter-annotator agreement of κ = 0.82 indicating substantial consistency. The resulting dataset was used to evaluate three retrieval methods.\n\nThe first method, included as a baseline, was BM25, a standard lexical retrieval algorithm. We used the standard implementation with parameters k1 = 1.5 and b = 0.75, consistent with prior literature. The second method was a dense retrieval system based on the DPR framework of Karpukhin et al. (2020), employing a BERT-based bi-encoder trained on Natural Questions and scored using inner product over learned dense representations. The third method, proposed in the present work, is a hybrid system that combines BM25 and DPR signals with a learned re-ranker, and applies a domain-specific weighting between the two underlying scores that is optimized per category.\n\nAll methods were evaluated on the same set of metrics, namely Recall at 5, 10, and 20, mean reciprocal rank, and normalized discounted cumulative gain at 10. Per-query latency was also measured to assess practical feasibility. Statistical comparisons between methods were conducted using paired t-tests with Bonferroni correction for multiple comparisons, and 95% confidence intervals were estimated through bootstrap resampling with 10,000 iterations. Results were considered statistically significant at p < 0.01. To support reproducibility, all code, data, and hyperparameter configurations have been publicly released, and random seeds were fixed across runs."
    },
    {
        "context": "academic_writing", "topic_area": "background",
        "prompt": "Polish this background section on the rise of food delivery apps in India — currently a bulleted summary, needs to be proper academic prose.",
        "rejected": "## Background: Food Delivery Apps in India\n\n**The Phenomenon:**\nThe Indian food delivery industry has grown dramatically over the past decade — transforming both consumer behavior and restaurant operations.\n\n### Key Trends:\n\n**Market Growth:**\n- 📈 Industry grew from ~$700M (2018) to $7B+ (2024)\n- 📈 Two dominant players: Swiggy and Zomato\n- 📈 Average order value increased 40% over 5 years\n\n**Consumer Shifts:**\n- 🍽️ Daily orderers grew from 2% to 11% of users\n- 🍽️ Quick-commerce (Blinkit, Zepto, Instamart) created new category\n- 🍽️ Subscription models (Swiggy One, Zomato Gold) hit 10M+ subscribers\n\n**Restaurant Impacts:**\n- 🍳 Cloud kitchens became viable business model\n- 🍳 Aggregator commissions a contentious issue\n- 🍳 Many traditional restaurants restructured for delivery-first\n\n**Regulatory Landscape:**\n- 📜 Disputes over platform commissions\n- 📜 Labor classification of delivery workers\n- 📜 Health and safety oversight\n\n### Research Gap:\n- ❌ Limited academic study of consumer-restaurant power dynamics\n- ❌ This study addresses that gap",
        "chosen": "The Indian food delivery industry has undergone a substantial transformation over the past decade, expanding from a market estimated at approximately seven hundred million dollars in 2018 to over seven billion dollars by 2024. The industry has come to be dominated by two principal platforms, Swiggy and Zomato, whose combined market presence has reshaped both consumer behaviour and the operational structures of urban restaurants. Average order values have risen by approximately forty percent over the past five years, suggesting that delivery has expanded beyond convenience-oriented use cases to encompass a broader share of meal occasions.\n\nConsumer behaviour has shifted in parallel. The proportion of platform users who order on a daily basis grew from approximately two percent in 2019 to eleven percent in 2024. The emergence of quick-commerce platforms such as Blinkit, Zepto, and Instamart has created an adjacent category that overlaps in important ways with food delivery, while subscription products such as Swiggy One and Zomato Gold have reportedly accumulated over ten million subscribers in aggregate, representing a meaningful share of high-frequency users.\n\nThese consumer shifts have produced significant changes for restaurants. Cloud kitchens, which operate exclusively for delivery without physical dining space, have emerged as a viable business model, while a substantial number of traditional restaurants have restructured their operations to give greater priority to delivery channels. The commission structures imposed by aggregators have been a recurring source of contention, particularly among smaller and independent restaurants. The regulatory environment has also evolved, with ongoing debates regarding platform commission caps, the labour classification of delivery workers, and health and safety oversight of cloud kitchens. Despite the visibility and economic significance of these developments, academic study of the underlying consumer-restaurant power dynamics remains limited; the present study contributes to addressing this gap."
    },
    {
        "context": "academic_writing", "topic_area": "discussion",
        "prompt": "Polish this discussion paragraph from my mechanical engineering paper on a new heat exchanger design. Currently uses too many bullets and bold labels — needs to flow as proper engineering academic prose.",
        "rejected": "## Discussion\n\n**Performance Summary:**\nThe proposed heat exchanger design demonstrates significant improvements over baseline configurations — particularly in compact installation contexts.\n\n### Key Observations:\n\n**1. Thermal Efficiency:**\n- ✅ 18% improvement in overall heat transfer\n- ✅ Consistent across tested flow regimes\n- ✅ Most pronounced at moderate Reynolds numbers (2,000-5,000)\n\n**2. Pressure Drop Trade-off:**\n- ⚠️ 12% increase in pressure drop\n- ⚠️ Acceptable for most target applications\n- ⚠️ Worth optimizing in future iterations\n\n**3. Fouling Resistance:**\n- ✅ 31% reduction in fouling rates\n- ✅ Particularly valuable in industrial settings\n- ✅ Likely due to optimized flow channeling\n\n**4. Manufacturing Considerations:**\n- ⚠️ Higher upfront tooling cost\n- ⚠️ Standard manufacturing processes still applicable\n- ✅ Payback period: 2-3 years in continuous-use scenarios\n\n### Implications:\n- 🔬 Validates the geometric optimization approach\n- 🏭 Practical for industries with thermal cycling needs\n- 🌱 Energy savings of 15-22% projected over lifecycle",
        "chosen": "The performance results indicate that the proposed heat exchanger design offers meaningful improvements over baseline configurations across the parameter range investigated. An 18% improvement in overall heat transfer coefficient was observed, with the largest gains occurring at moderate Reynolds numbers in the range of 2,000 to 5,000. This range corresponds to the operating conditions of many compact industrial applications, suggesting that the proposed design is well-suited to its intended deployment context. The improvement is largely attributable to the optimized internal channel geometry, which increases effective surface area while preserving favourable flow characteristics.\n\nThis thermal benefit comes at the cost of a 12% increase in pressure drop relative to the baseline. While this represents a meaningful penalty, the magnitude remains within acceptable bounds for the majority of target applications, and the increased pumping power required is more than offset by the thermal gains in continuous-use scenarios. Future iterations of the design may benefit from further optimization to reduce this penalty, particularly through refinement of the entry and exit geometries.\n\nA further finding of practical significance is the 31% reduction in observed fouling rates relative to the baseline configuration. This effect, which appears to result from improved flow channeling that reduces low-velocity regions where fouling tends to accumulate, is particularly valuable in industrial settings where fouling-related maintenance contributes substantially to operating costs. From a manufacturing perspective, the proposed design entails higher upfront tooling costs but employs standard fabrication processes, with an estimated payback period of two to three years in continuous-use applications. Taken together, the results support the practical viability of the geometric optimization approach adopted here and suggest that lifecycle energy savings of fifteen to twenty-two percent are achievable in suitable deployment contexts."
    },

    # ============ SOCIAL_CONTENT (3) ============
    {
        "context": "social_content", "topic_area": "linkedin_post",
        "prompt": "Write a LinkedIn post about a side project I built that didn't take off — want to share lessons honestly without it being a humblebrag.",
        "rejected": "## LinkedIn Post — Lessons from a Failed Side Project 💡\n\n---\n\n💥 **I spent 6 months building a side project. It failed. Here's what I learned.** 💥\n\nLast year, I built [Project Name] — a tool I was convinced would change [industry].\n\n**The Idea:**\n- Solved a problem I personally had\n- Validated with 5 friends\n- Excited to build\n\n**The Execution:**\n- 🚀 Built MVP in 2 months\n- 🚀 Launched on Product Hunt\n- 🚀 Got initial buzz\n- 🚀 Then... silence\n\n**Why It Failed:**\n1. **Wrong audience:** Friends ≠ market\n2. **Solved my problem, not enough others'**\n3. **Underestimated distribution**\n4. **Burned out before pivot**\n\n**3 Big Lessons:**\n\n💡 **Lesson 1:** Validate with strangers, not friends\n💡 **Lesson 2:** Distribution > Product (early)\n💡 **Lesson 3:** Schedule burnout breaks\n\n**Was it worth it?**\n- ✅ Learned more than 2 years of job work\n- ✅ Network of brilliant people\n- ✅ Better instincts for next time\n- ✅ Real respect for founders now\n\n**Failure isn't the opposite of success — it's tuition.** 💎\n\nWhat's a failure that taught YOU something?\n\n#Entrepreneurship #FailureToSuccess #SideProject #LessonsLearned #BuildInPublic #StartupLife #GrowthMindset #LinkedInGrowth",
        "chosen": "Six months ago I shipped a side project I was sure would take off. Almost nobody used it.\n\nThe project itself was fine — the build was actually clean and I'm still proud of the code. What it wasn't, was useful to anyone other than me. I validated it by asking five friends, all of whom told me they'd use it, none of whom actually did once it shipped.\n\nThe real lesson wasn't 'validate properly' (everyone says this). It was that I'd skipped that step because I didn't *want* the answer. Validating with strangers means risking being told the idea is mediocre. Validating with friends is a way to get permission to build the thing you were going to build anyway.\n\nNot publishing this for engagement. Just useful to write down before I start the next one and make the same mistake."
    },
    {
        "context": "social_content", "topic_area": "instagram_caption",
        "prompt": "Write an Instagram caption for a photo I took at a coffee shop where I'm just journaling and being alone. Should feel personal, not 'aesthetic'.",
        "rejected": "## Instagram Caption — Solo Coffee Shop Moment ☕\n\n**Option 1 — Reflective:**\n\nSolo dates with myself are underrated 🤍📓✨\n\nLessons from today:\n- Quiet feels different than lonely\n- A pen + paper > most therapy sessions\n- The best version of me is the one that gets alone time\n\nFinding magic in the small moments 🌟\n\n**#️⃣ Hashtags:** #SelfCare #SoloDate #MentalHealth #CoffeeShop #Mindfulness #JournalingTime #SlowLiving #InnerPeace\n\n---\n\n**Option 2 — Casual:**\n\nQuiet morning, good coffee, full notebook. The trifecta. ☕📓\n\n**#️⃣ Hashtags:** #SaturdayMornings #JournalingLife #CafeVibes #SimpleJoys\n\n---\n\n**Option 3 — Soft & dreamy:**\n\nSpending the morning with myself ☁️☕\nNo agenda. No phone. Just thoughts on paper.\nWe should all do this more 🤍\n\n**#️⃣ Hashtags:** #Reflection #SaturdayMood #Wellness #CoffeeArtist #MindfulMoments",
        "chosen": "wrote three pages of nothing in particular. felt better afterward."
    },
    {
        "context": "social_content", "topic_area": "reel_script",
        "prompt": "Write a 25-second reel script about 'one habit that actually changed my life' — should be specific and not the usual 'wake up at 5am' content.",
        "rejected": "## 25-Second Reel Script — Life-Changing Habit 🎬\n\n**🎯 Hook (0-3s):**\n- Text overlay: 'The ONE habit that changed my life'\n- Voiceover: 'STOP scrolling — this actually works'\n\n**📖 Body (3-20s):**\n\n**Beat 1 (3-8s): The Habit**\n- 'Every Friday at 4 PM, I review my week'\n- Visual: journal opening, writing\n\n**Beat 2 (8-14s): What I Do**\n- 'I answer 3 questions:'\n- ✍️ What did I learn?\n- ✍️ What did I waste time on?\n- ✍️ What do I want to repeat?\n\n**Beat 3 (14-20s): The Impact**\n- 'Six months in, my life is unrecognizable'\n- ✅ Less wasted time\n- ✅ Clearer priorities\n- ✅ Real growth\n\n**📢 CTA (20-25s):**\n- 'Try it for ONE month'\n- 'Save this and start Friday 💾'\n- 'Follow for more habits ✨'\n\n**🎵 Audio:** Trending uplifting sound\n\n**#️⃣ Hashtags:** #Habits #ProductivityHacks #LifeChanging #SelfImprovement #JournalingTips #GrowthMindset #MindsetMatters",
        "chosen": "(Talking to camera, casual, holding a small notebook)\n\n'Okay one habit that genuinely changed my life, and it's not waking up at 5 AM.'\n\n'Every Friday at 4 PM I sit down for 20 minutes and write three things: what I learned this week, what I wasted time on, and what I want to do again next week.'\n\n'That's it. That's the whole thing.'\n\n'Six months in, the difference isn't that I'm more productive — it's that I'm not making the same mistakes on loop anymore. Turns out you have to actually notice your patterns before you can change them.'\n\n'Friday 4 PM. Twenty minutes. Try it for a month.'"
    },

    # ============ CONCEPT_EXPLAIN (2) ============
    {
        "context": "concept_explain", "topic_area": "rl",
        "prompt": "Can you explain what 'discount factor' (gamma) is in reinforcement learning? I see it in equations but I don't really get what it does.",
        "rejected": "## Discount Factor (γ) in RL 📉\n\n### Definition:\nA value between 0 and 1 that determines how much the agent values future rewards relative to immediate rewards.\n\n### How It Works:\n- **γ = 0:** Only cares about immediate reward\n- **γ = 1:** All future rewards weighted equally\n- **γ = 0.99:** Far-future rewards still matter, but less so\n\n### Mathematical Form:\nIn computing return:\n```\nReturn = R_t + γ R_{t+1} + γ² R_{t+2} + γ³ R_{t+3} + ...\n```\n\n### Why It Matters:\n- ✅ Prevents infinite sums in continuing tasks\n- ✅ Encourages preference for sooner rewards\n- ✅ Models uncertainty about future\n- ✅ Critical for convergence\n\n### Common Values:\n| Domain | Typical γ |\n|--------|-----------|\n| Games | 0.99 |\n| Robotics | 0.95-0.99 |\n| Finance | 0.9-0.95 |\n| Short-horizon | 0.9 |\n\n### Trade-offs:\n- 🔴 Too low: Agent is myopic, misses long-term gains\n- 🔴 Too high: Slow learning, instability\n- ✅ Right value: Balanced long-term planning\n\n### Verdict:\nDiscount factor is one of the most important hyperparameters in RL!",
        "chosen": "Imagine someone offers you ₹1000 today or ₹1000 next year. Most people would take it today, even though the absolute amount is the same. Why? Because future rewards feel less valuable than immediate ones — the future is uncertain, you might not be around, you could invest the money in the meantime.\n\nThe discount factor (γ, gamma) in RL is the mathematical version of that preference. It's a number between 0 and 1 that tells the agent how much to care about rewards that arrive in the future versus rewards right now. With γ = 0.99, a reward arriving 100 steps from now is worth about 37% of an immediate reward. With γ = 0.9, that same future reward is worth only 0.003% of an immediate one — basically nothing.\n\nThe practical consequence: a low gamma makes the agent very short-sighted. It'll happily take a small reward right now and ignore a much bigger reward that's just a few steps away. A high gamma makes the agent more patient — it can be willing to sacrifice immediate reward for a larger future one, like a chess player giving up a pawn for a positional advantage.\n\nWhy not just set gamma to 1.0 and weight all rewards equally? Two reasons. First, in tasks that go on forever, you'd be summing an infinite series of rewards, which can blow up mathematically. Second, the future is genuinely uncertain — by the time you get there, the world might have changed, your model might be wrong, and so on. Discounting bakes in a healthy skepticism about that.\n\nMost serious RL work uses gamma between 0.9 and 0.99. The right value is task-specific and is one of the things people tune."
    },
    {
        "context": "concept_explain", "topic_area": "ml",
        "prompt": "What does it mean to 'normalize' data in ML? I keep seeing it as a preprocessing step but no one explains why.",
        "rejected": "## Data Normalization in ML 📏\n\n### Definition:\nThe process of scaling features to a common range so they contribute equally to model training.\n\n### Why It Matters:\n- ✅ Prevents features with large values from dominating\n- ✅ Speeds up gradient descent convergence\n- ✅ Required for distance-based methods (KNN, k-means)\n- ✅ Necessary for neural networks\n\n### Common Methods:\n\n**1. Min-Max Scaling:**\n- Range: [0, 1]\n- Formula: (x - min) / (max - min)\n- Use: When you need bounded values\n\n**2. Standardization (Z-score):**\n- Mean: 0, Std: 1\n- Formula: (x - mean) / std\n- Use: Most common for ML\n\n**3. Robust Scaling:**\n- Uses median and IQR\n- Use: When data has outliers\n\n### When NOT to Normalize:\n- Tree-based models (don't need it)\n- When features are already on similar scales\n- For categorical / one-hot features\n\n### Pitfalls:\n- 🔴 Always fit on train, apply to test\n- 🔴 Don't use future data\n- 🔴 Watch for outliers\n\n### Verdict:\nNormalization is a small step with outsized impact on model performance!",
        "chosen": "Imagine you're trying to predict house prices, and your input features include the number of bedrooms (typically 1-5) and the size of the house in square feet (typically 500-5,000). To a model that doesn't know what those numbers mean, the square footage values are simply 1,000 times larger than the bedroom values — and the math of training will treat them as 1,000 times more important, even though that's not what you intend.\n\nNormalization is the preprocessing step where you rescale all your features so they're on a comparable range. The most common version (called standardization) shifts each feature so it has mean zero and standard deviation one. After normalization, your bedrooms feature and your square-footage feature look numerically comparable to the model, and it can learn what each one actually contributes from the data rather than being biased by their scale.\n\nThe reason this matters in practice goes beyond fairness between features. Most ML algorithms — particularly anything involving gradient descent, which is to say almost all neural networks — train much faster and more reliably when inputs are on a similar scale. Without normalization, training can become unstable, get stuck, or converge much more slowly.\n\nThe one common exception is tree-based models like random forests and XGBoost. They make decisions based on whether a feature is above or below some threshold, so the actual scale of the feature doesn't affect them. For everything else — linear models, neural networks, distance-based methods like k-means — normalization is essentially mandatory.\n\nThe one rule to remember: always compute the normalization parameters (the mean and standard deviation) on your *training* data and apply them to your test data. If you use the full dataset's statistics, you've subtly leaked information from your test set into training."
    },

    # ============ DECISION_ADVICE (2) ============
    {
        "context": "decision_advice", "topic_area": "career",
        "prompt": "Should I move cities for a job, even though I have strong friendships and family here?",
        "rejected": "## Should You Move for a Job? 🏙️ vs 🏡\n\n### Quick Take:\nDepends on stage of life and what the move offers.\n\n### Move:\n\n**Pros:**\n- ✅ New career opportunities\n- ✅ Personal growth\n- ✅ Reset of patterns\n- ✅ Broadened network\n\n**Cons:**\n- 🔴 Distance from loved ones\n- 🔴 Loss of established support\n- 🔴 Adjustment costs\n- 🔴 May not work out\n\n### Stay:\n\n**Pros:**\n- ✅ Existing community\n- ✅ Family proximity\n- ✅ Known environment\n- ✅ Lower stress\n\n**Cons:**\n- 🔴 May limit career\n- 🔴 Comfort can stagnate\n- 🔴 Regret risk\n- 🔴 Unexplored possibilities\n\n### Decision Factors:\n| Factor | Move | Stay |\n|--------|------|------|\n| Life stage | 20s/30s | 40s+ |\n| Career ambition | High | Steady |\n| Family obligations | Lower | Higher |\n| Risk tolerance | Higher | Lower |\n| Adventure-seeking | Yes | No |\n\n### Verdict:\nMove if career growth is significant; stay if community matters more!",
        "chosen": "Honest answer: this is one of the hardest decisions to make rationally because both sides feel correct, and the people who give you advice will project their own answer onto you.\n\nA few questions worth sitting with before deciding:\n\nHow good is the job, actually? Not 'is it a step up' — but is it the kind of opportunity that genuinely changes your trajectory in a way nothing local could? If it's incremental, the math gets much harder.\n\nHow easy is it to come back? People underestimate this. If you can move, try it for two or three years, and come back to a similar city with a similar quality of life — the move is much lower risk than it feels. If returning would mean genuinely restarting your career, that changes things.\n\nWhat does your current community actually provide that you'd lose? Friendships that are strong enough to survive distance will. The ones that depended on weekly hangouts will fade — that's the real cost. Family proximity is harder to substitute; if there are aging parents or close-knit family obligations, that's a real weight.\n\nThe quiet thing nobody says out loud: most people who move regret it less than they expected, and most people who stay for community reasons don't regret that either. The version that goes badly is usually the one made out of inertia in either direction — moving 'because it sounds adventurous' without a real reason, or staying 'because moving sounds scary' without examining whether the local life is actually what you want.\n\nWhat's pulling you in each direction right now — the specific job, or the general idea of a change?"
    },
    {
        "context": "decision_advice", "topic_area": "career",
        "prompt": "Should I try to negotiate this job offer or just take what they gave me? I'm worried they'll rescind if I push back.",
        "rejected": "## Negotiate or Accept the Offer? 💼\n\n### Quick Take:\nAlmost always negotiate. Rescinding is extremely rare.\n\n### Why Negotiate:\n- ✅ Companies expect it\n- ✅ Most offers have room\n- ✅ Future raises are % of starting comp\n- ✅ Signals confidence\n- ✅ Long-term financial impact\n\n### Why People Don't:\n- 🔴 Fear of rescission\n- 🔴 Discomfort with conflict\n- 🔴 Imposter syndrome\n- 🔴 'Don't want to seem greedy'\n\n### Reality Check:\n- 📊 Offers are rescinded <1% of the time\n- 📊 Average negotiation gains: 5-15% of comp\n- 📊 Over career, this compounds to hundreds of thousands\n\n### How to Negotiate:\n\n**1. Anchor high but reasonable:**\n- Research market data\n- State your number first\n- Justify with data\n\n**2. Negotiate the whole package:**\n- Base salary\n- Bonus\n- Equity\n- Signing bonus\n- PTO\n- Title\n\n**3. Be professional:**\n- Express genuine enthusiasm\n- Frame as wanting to make it work\n- Don't ultimatum\n\n### Verdict:\nNegotiate. The fear is much bigger than the actual risk!",
        "chosen": "Negotiate. Almost always.\n\nThe fear of rescission is real but the actual rate is vanishingly small — well under 1% in practice. Companies that genuinely rescind an offer over polite negotiation are companies that would have been miserable to work for. If anything, declining to negotiate often signals to companies that you don't value yourself highly, which can subtly affect how you're treated later.\n\nThe compounding effect is the bigger point. Future raises and promotions are often percentages of your current salary. A starting salary that's $10K lower than it could have been doesn't stay $10K lower — it grows into a gap of $50K+ over a decade of compounding raises. So the cost of not negotiating isn't a one-time loss; it's a permanent tax on your career.\n\nThe shape of a good negotiation isn't aggressive. It's something like: 'I'm really excited about this role and want to make it work. Based on the market data I've seen and the scope of the role, I was hoping to be at [number]. Is there room to get there?' That phrasing is polite, anchored in data, and gives them an easy way to come back with a counter.\n\nThe one situation where I'd ease off: if the company has been completely transparent about a strict band and you can see they've genuinely placed you at the top of it, pushing harder mostly burns goodwill. But that's the rare case. Most offers have meaningful flex, and most candidates leave that money on the table out of fear.\n\nWhat's the offer and what's your honest read on the market for the role?"
    },

    # ============ CASUAL_REPLY (1) ============
    {
        "context": "casual_reply",
        "prompt": "Reply to a Slack from a coworker: 'thinking of taking the rest of the day off, i'm fried'",
        "rejected": "Here are some response options:\n\n**Supportive:**\n- DO IT. You've been pushing hard. Take care.\n\n**Light:**\n- Lol GO. We'll survive.\n\n**Caring + practical:**\n- Yes please. Anything you need covered today?\n\n**Brief:**\n- Take it. See you tomorrow.\n\n**Tone tips:**\n- Validate the need\n- Offer help, not pressure\n- Don't make them justify",
        "chosen": "Take it. Anything urgent I can cover before you go?"
    },
]


def main() -> None:
    path = Path("data/formatting_pairs_v1.jsonl")
    assert path.exists()
    existing = set()
    with path.open() as f:
        for line in f:
            existing.add(json.loads(line)["prompt"])
    new = [r for r in ROWS if r["prompt"] not in existing]
    with path.open("a") as f:
        for row in new:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    counts = Counter()
    with path.open() as f:
        all_rows = [json.loads(line) for line in f]
    for r in all_rows:
        counts[r["context"]] += 1
    print(f"Appended: {len(new)} new (skipped {len(ROWS)-len(new)} dupes)")
    print(f"Total: {len(all_rows)}\n")
    for c, n in sorted(counts.items()):
        print(f"  {c:18} {n}")


if __name__ == "__main__":
    main()
