"""
Batch 6 append script — introduces social_content category.
The 'rejected' versions for social_content use the platform-specific LLM tells:
  - emoji-as-section-marker
  - 'Hook/Body/CTA' templated structure with bold labels
  - 'Hashtag suggestions:' blocks
  - 'Caption variants: Option 1/2/3'
  - Bulleted dating bios with 'Looking for:' headers
The 'chosen' versions sound like actual humans who know the platform.
"""

import json
from pathlib import Path
from collections import Counter

ROWS = [
    # ============ SOCIAL_CONTENT (14) ============
    {
        "context": "social_content", "topic_area": "reel_script",
        "prompt": "Write me a 30-second Instagram reel script for 'a day in the life of a tech intern at a startup' — should feel authentic, not over-produced.",
        "rejected": "## 30-Second Reel Script — Day in the Life: Tech Intern at a Startup 🎬\n\n**🎯 Hook (0-3s):**\n- Quick text overlay: 'POV: First week as a tech intern 💻'\n- Cut to phone alarm at 8 AM\n\n**📖 Story (3-25s):**\n\n*Beat 1 (3-7s): Morning routine*\n- ☕ Coffee shot\n- 🚶 Walking into office\n- 👥 Greeting team\n\n*Beat 2 (7-15s): Work day montage*\n- 💻 Coding shots\n- 📝 Standup meeting\n- 🤔 Confused face debugging\n- 🎉 Reaction when code works\n\n*Beat 3 (15-25s): Wrap-up*\n- 🍽️ Lunch with team\n- 💡 Learning moment\n- 🚪 Walking out\n\n**📢 CTA (25-30s):**\n- Text: 'Day 1 of 90 — follow for more!'\n- Voiceover: 'Subscribe for the full journey'\n\n**🎵 Suggested audio:**\n- Trending upbeat song\n- Or original voiceover\n\n**#️⃣ Hashtag suggestions:**\n#TechIntern #DayInTheLife #SoftwareEngineer #StartupLife #InternLife #CodingLife #TechCareer #FirstJob #Programming #CareerJourney",
        "chosen": "(Voiceover, casual, while filming the actions)\n\n'Okay so this is day one of being a tech intern at a startup and I have absolutely no idea what I'm doing.'\n\n[Walking into the office holding coffee]\n\n'Everyone's already here. Apparently 9 AM is late?'\n\n[Sitting at desk, opening laptop, screen shows error message]\n\n'My setup doesn't work. The setup that the onboarding doc said takes 20 minutes has now taken three hours.'\n\n[Quick cut to standup meeting, looking lost]\n\n'I just said 'I'm still onboarding' for the fifth day in a row.'\n\n[Coding at desk, then sudden look of joy]\n\n'IT WORKED. I wrote one line of code that did one thing and I have never been prouder.'\n\n[Walking out of office]\n\n'Tomorrow I have to do it all again. Why am I excited?'"
    },
    {
        "context": "social_content", "topic_area": "reel_script",
        "prompt": "Write a 45-second LinkedIn video script for '3 things I wish I knew before starting my master's' — should sound like genuine reflection, not a motivational poster.",
        "rejected": "## 3 Things I Wish I Knew Before My Master's — LinkedIn Video 🎓\n\n**🎯 Hook (0-5s):**\n- 'If you're starting your master's this fall, watch this.'\n- Text overlay: 3 lessons from a recent grad\n\n**📖 Body (5-40s):**\n\n**Lesson 1: Network Beyond Your Cohort (5-15s)**\n- 🔑 Most people stick to their program\n- ✨ Real opportunities come from breadth\n- 💡 Attend other departments' events\n\n**Lesson 2: Your Advisor Matters Most (15-25s)**\n- 🎓 Brand of school < advisor relationship\n- 🤝 Choose someone who'll invest in you\n- 📈 This shapes your career trajectory\n\n**Lesson 3: Side Projects > GPA (25-40s)**\n- 💻 Employers care about what you've built\n- 🚀 Publish, deploy, share publicly\n- 🌟 GPA opens few doors that projects don't\n\n**📢 CTA (40-45s):**\n- 'What would YOU add to this list?'\n- 'Drop in the comments 👇'\n\n**#️⃣ Hashtags:**\n#GradSchool #MastersLife #CareerAdvice #HigherEducation #STEM #LinkedInLearning",
        "chosen": "Three things I wish someone had told me before I started my master's.\n\nOne. Your advisor matters way more than the name of the school. I spent months chasing rankings and almost zero time researching who I'd actually be working with. The people in my program who had bad advisor fits had a much harder time than people who picked a less prestigious school but ended up with someone genuinely invested in them.\n\nTwo. Network outside your own department. The most useful conversations I had in two years happened at events I almost didn't go to — in totally different fields. Your cohort is the easy network. The harder one is more valuable.\n\nThree. Nobody is going to ask you your GPA. They will absolutely ask what you built. Spend time on real projects, even if they hurt your grades a little. The trade is worth it almost every time.\n\nIf you're starting this fall — good luck. It's harder than you think but better than you expect."
    },
    {
        "context": "social_content", "topic_area": "instagram_caption",
        "prompt": "Write an Instagram caption for a photo of me holding my thesis after defending — should feel personal, not influencer-y.",
        "rejected": "## Instagram Caption — Thesis Defense Day 🎓\n\n**Option 1 — Inspirational:**\nFrom the late nights to the early mornings — it was all worth it. Officially DONE with my thesis! ✨📚 Grateful beyond words for everyone who supported me on this journey. Bigger things ahead! 🚀💫\n\n**#️⃣ Hashtags:** #ThesisDefense #MastersDegree #ProudGraduate #AcademicJourney #BigDay #Grateful #DreamsComeTrue\n\n---\n\n**Option 2 — Casual:**\n2 years, 200 pages, and approximately 1,000 cups of coffee later — I did it! 🎉☕📖 Thanks to everyone who put up with me during this 😅\n\n**#️⃣ Hashtags:** #ThesisLife #GradSchool #SurvivedIt #Coffee\n\n---\n\n**Option 3 — Reflective:**\nLooking at this thing in my hands and not really believing it's done. Months of doubt, late nights, breakthroughs, breakdowns — all of it led here. To everyone who reminded me to keep going: thank you. ❤️📚🙏\n\n**#️⃣ Hashtags:** #Reflection #ThesisDone #Gratitude #Journey",
        "chosen": "200 pages. Two years. Approximately one minor existential crisis per week.\n\nDefended this morning. Still don't fully believe it's over.\n\nThank you to everyone who put up with me — especially [advisor name], who somehow always knew when to push and when to stop pushing."
    },
    {
        "context": "social_content", "topic_area": "linkedin_post",
        "prompt": "Write me a LinkedIn post announcing I got promoted to Senior Software Engineer at my company. Should feel genuine, not humble-braggy.",
        "rejected": "## LinkedIn Post — Promotion Announcement 🎉\n\n---\n\n🚀 Excited to share some big news! 🚀\n\nI'm absolutely thrilled to announce that I've been promoted to **Senior Software Engineer** at [Company]! 🎊✨\n\n**A few reflections on the journey:**\n\n📌 **Lesson 1:** Hard work truly pays off when paired with the right team\n📌 **Lesson 2:** Mentorship is the cheat code I wish I'd discovered earlier\n📌 **Lesson 3:** Saying yes to scary opportunities accelerates growth\n\n**Special thanks to:**\n- 🙏 My manager [Name] for believing in me\n- 🙏 My incredible team for the daily collaboration\n- 🙏 My mentors who shaped my thinking\n- 🙏 My family for the endless support\n\nLooking forward to the next chapter of impact, learning, and growth! 💼💡🚀\n\n**What's next:**\n- ✅ Bigger technical challenges\n- ✅ Mentoring junior engineers\n- ✅ Continued learning\n\nGrateful and excited for what's ahead!\n\n#Promotion #SoftwareEngineering #CareerGrowth #SeniorEngineer #Grateful #Tech #LinkedIn #CareerDevelopment #NewChapter #BlessedAndGrateful",
        "chosen": "Promoted to Senior Software Engineer this week.\n\nI almost didn't apply for the promo cycle last year because I didn't feel ready. My manager talked me into it anyway. I didn't get it that time, and the feedback I got was honestly the most useful thing that's happened to my career — it gave me a concrete list of what was missing.\n\nThis time around, I came in genuinely prepared. Still felt like impostor syndrome on the day of the panel.\n\nGrateful to the people who pushed me to try the first time when I didn't think I should, and to the people who gave me the honest feedback that made the second time work. You know who you are.\n\nOn to the next thing."
    },
    {
        "context": "social_content", "topic_area": "twitter_thread",
        "prompt": "Help me redraft this Twitter thread about a debugging story — make it more engaging without being clickbaity. Original draft: 'I spent 3 days debugging a problem. Turns out it was a single character. Here is what I learned.'",
        "rejected": "## Engaging Twitter Thread — Debugging Story 🔥\n\n**Tweet 1 (Hook):**\n🚨 I just spent 72 hours debugging a single character. Here's the story 🧵👇\n\n**Tweet 2:**\nIt started innocently. A simple API call that worked locally but failed in production. ⚠️\n\n**Tweet 3:**\nI checked everything:\n✅ Network\n✅ Auth\n✅ Permissions\n✅ Environment variables\n✅ Database connection\n\nAll fine. 🤔\n\n**Tweet 4:**\nDay 2: Added logging EVERYWHERE. Stared at logs until my eyes hurt. 👀\n\n**Tweet 5:**\nDay 3: Found it. A single trailing whitespace character in a config file. ONE SPACE. 🤯\n\n**Tweet 6 (Lesson):**\nThe lesson: NEVER trust your inputs. Always validate. Always log raw values. Always check whitespace. 💡\n\n**Tweet 7 (CTA):**\nWhat's the dumbest bug YOU'VE chased? Drop it below 👇\n\n**📊 Engagement tips:**\n- Add screenshots\n- Include a meme\n- Ask question at end",
        "chosen": "A thread about losing three days of my life to a single character.\n\n---\n\nIt started with a Slack message from QA saying the staging environment was returning 401s on a specific endpoint. Locally? Worked. Dev environment? Worked. Only staging.\n\n---\n\nI checked the obvious things first. Auth tokens, environment variables, network rules, the deploy logs. All fine. Spent the rest of the day adding more logging and convincing myself it was somehow intermittent.\n\n---\n\nDay two I started doubting reality. Pulled up two terminals side by side, ran the exact same curl command in both. Local: 200. Staging: 401. I sat there for twenty minutes wondering if I was dreaming.\n\n---\n\nDay three, on a hunch, I copied the auth token from staging and pasted it into a hex viewer. There was a trailing newline character that bash had been silently stripping in my local terminal but the staging deploy script wasn't. \\n. One character.\n\n---\n\nThe fix was three lines. The lesson — that I keep re-learning — is that 'looks identical' is not the same as 'is identical' and the first thing I should reach for when something is mysteriously broken is the bytes, not the strings."
    },
    {
        "context": "social_content", "topic_area": "linkedin_profile",
        "prompt": "Redraft my LinkedIn 'About' section — should sound like a real person, not a template. Original: 'Results-driven Software Engineer with 4+ years of experience in building scalable solutions. Passionate about leveraging cutting-edge technologies to drive business outcomes. Proven track record of delivering high-impact projects.'",
        "rejected": "## Redrafted LinkedIn About Section 💼\n\n**Option 1 — Polished Professional:**\n\n👋 Hi, I'm [Name]!\n\n💻 **What I do:** Software engineer with 4+ years of experience building scalable, user-focused products.\n\n🎯 **My specialties:**\n- Full-stack development (React, Node.js, Python)\n- System design & architecture\n- Cross-functional collaboration\n- Mentorship & technical leadership\n\n🚀 **Impact at my current role:**\n- Led 3 major product launches\n- Reduced infrastructure costs by 30%\n- Mentored 5 junior engineers\n\n💡 **What drives me:**\n- Solving complex problems\n- Building products people love\n- Continuous learning\n\n🌱 **Currently exploring:** ML/AI applications in [domain]\n\n📬 **Let's connect** if you're working on something interesting!\n\n---\n\n#SoftwareEngineering #TechCareers #FullStack #OpenToOpportunities",
        "chosen": "I've been a software engineer for four years, mostly building backend systems that people don't think about until they break. I'm at my best when a problem looks small from the outside and has surprising depth once you dig in — those are the bugs I remember a year later.\n\nMy work has spanned full-stack web development, infrastructure, and most recently some applied ML work that I'm finding I really enjoy. I care a lot about code that other people will read, which means I spend more time than is strictly necessary on naming things and writing PR descriptions.\n\nOutside work I read more than I should, take long walks to debug my brain, and am slowly getting better at chess.\n\nIf you're working on something interesting, I'd love to hear about it."
    },
    {
        "context": "social_content", "topic_area": "dating_profile",
        "prompt": "Help me redraft my Hinge prompts. Current ones are: 'I'll fall for you if... you have a sense of humor', 'My simple pleasures... coffee and books', 'Two truths and a lie... I've been skydiving, I speak three languages, I hate cilantro'. They feel generic.",
        "rejected": "## Hinge Profile Redraft — Punchier & More Engaging 💕\n\n---\n\n**Prompt 1: 'I'll fall for you if...'**\n\n*Original:* You have a sense of humor\n\n*Redrafted Options:*\n\n**Option A:** You can match my energy in a 2am philosophical debate AND a 9am coffee run ☕💭\n\n**Option B:** You laugh at your own jokes before getting to the punchline 😄\n\n**Option C:** You think 'just one more chapter' counts as a personality trait 📖\n\n---\n\n**Prompt 2: 'My simple pleasures...'**\n\n*Original:* Coffee and books\n\n*Redrafted Options:*\n\n**Option A:** ✨ A perfectly brewed pour-over, a book that ruins my sleep, and rain hitting the window ✨\n\n**Option B:** Finishing a book, starting a new one, and the brief existential crisis in between 📚\n\n---\n\n**Prompt 3: 'Two truths and a lie...'**\n\n*Original:* I've been skydiving, I speak three languages, I hate cilantro\n\n*Redrafted:*\n\n💫 **The Three:**\n- ✈️ I've been to 23 countries\n- 🎸 I can play guitar but only one Coldplay song\n- 🥑 I genuinely think cilantro tastes like soap\n\n*Comment below with your guess!* 👇\n\n---\n\n**💡 Pro tips:**\n- Be specific over generic\n- Show personality, not statements\n- Leave conversation hooks",
        "chosen": "**Prompt 1 — I'll fall for you if...**\n\nyou have strong opinions about breakfast.\n\n**Prompt 2 — My simple pleasures...**\n\nbeing the first person at a coffee shop when it opens. the smell of an old bookshop. starting a new notebook.\n\n**Prompt 3 — Two truths and a lie...**\n\nI've been skydiving once and immediately regretted it. I learned to drive at 27. I genuinely cannot taste the difference between Pepsi and Coke.\n\n---\n\n(Notes on the redraft: cut the 'sense of humor' line — everyone says that. The new one is small and odd and gives someone an actual thing to message you about. 'Coffee and books' is also generic; the redraft gives texture without trying too hard. Two truths swapped the cilantro one because the soap-taste line is overused on dating apps. The new lie about not being able to taste Pepsi vs Coke is more interesting and easier for people to bite on.)"
    },
    {
        "context": "social_content", "topic_area": "linkedin_post",
        "prompt": "Write a LinkedIn post announcing I'm leaving my current job (where I was for 3 years) for a new role. Want it to be genuine, not performatively grateful.",
        "rejected": "## LinkedIn Post — Job Transition 🎉\n\n---\n\n💼 **Big News!** 💼\n\nAfter 3 incredible years at [Company A], I'm thrilled to announce that I'm starting a new chapter at [Company B] next month! 🚀✨\n\n**A look back at 3 amazing years:**\n\n📌 Joined as a [Junior Role] in 2022\n📌 Promoted to [Mid Role] in 2023\n📌 Led [Project] launches\n📌 Mentored amazing teammates\n📌 Made lifelong friends 💖\n\n**My deepest gratitude to:**\n- 🙏 My manager [Name] for trusting me with big problems\n- 🙏 My team — best people I've worked with\n- 🙏 Cross-functional partners who taught me so much\n- 🙏 Mentors near and far\n- 🙏 My family for the unwavering support\n\n**What's next:**\n- 🌟 New role: [Role] at [Company B]\n- 🌟 Focus: [Domain]\n- 🌟 Excited for: [Specific thing]\n\nThank you, [Company A]. You will always be a special place to me. 💼❤️\n\nOnward and upward! 🚀\n\n#NewBeginnings #CareerChange #Grateful #Transition #NextChapter #Blessed #LinkedInFamily",
        "chosen": "After three years, today is my last day at [Company A].\n\nI joined as an over-confident junior who thought I knew more than I did. I'm leaving with a slightly more accurate picture of how much I don't know, which I count as the most important thing I learned.\n\nA few people specifically taught me how to think — [Name 1] about how to disagree without making it personal, [Name 2] about how to write a real PR description, [Name 3] about how to actually listen in a 1:1. I'll be borrowing from all of you for the rest of my career.\n\nNext month I'm joining [Company B] as a [role]. Different problem space, similar kind of work. Genuinely excited, also a little nervous.\n\nIf we worked together at [Company A] and we haven't connected here, please send me a request. I'd like to keep in touch."
    },
    {
        "context": "social_content", "topic_area": "instagram_caption",
        "prompt": "Redraft this travel photo caption from Goa — make it feel less like every other travel post. Original: 'Found paradise in Goa! ✈️🌴 Sun, sand, and the best vibes. So grateful for this experience. Already planning the next trip!'",
        "rejected": "## Redrafted Instagram Travel Caption — Goa 🌴\n\n**Option 1 — Reflective:**\n\nThere's something about Goa at sunset that makes you question every life choice that doesn't involve moving here 🌅\n\nLessons learned this week:\n- ☀️ The sun rises whether you sleep or not\n- 🌊 The ocean is a better therapist than most therapists\n- 🥥 Coconut water hits different when you crack it yourself\n- 🌴 Doing nothing is a skill\n\n**Option 2 — Punchy:**\n\nGoa edit 🌴✨\n\nThings I did:\n- Watched 5 sunsets\n- Ate too many prawns\n- Forgot what day it was\n- Read 2.5 books\n\nWould recommend 10/10\n\n**Option 3 — Sentimental:**\n\nGoa reminded me what slow feels like 🌊\n\n**#️⃣ Suggested hashtags:** #Goa #TravelDiaries #BeachVibes #IndiaTravel #Wanderlust #SunsetLover #IncredibleIndia #VacationMode #BlessedTraveler",
        "chosen": "Spent a week in Goa doing absolutely nothing of consequence and remembering that this is a thing you're allowed to do."
    },
    {
        "context": "social_content", "topic_area": "reel_script",
        "prompt": "Write a 20-second reel script with the hook 'you're using ChatGPT wrong' — should give one genuine useful tip, not be clickbaity.",
        "rejected": "## 20-Second Reel Script — 'You're Using ChatGPT Wrong' 🎬\n\n**🎯 Hook (0-3s):**\n- 📱 Camera close-up\n- Text overlay: 'You're using ChatGPT wrong'\n- Voiceover: 'STOP doing this'\n\n**📖 Body (3-17s):**\n\n**The mistake (3-8s):**\n- Show typing: 'Write a blog post about marketing'\n- ❌ Big red X\n- Voiceover: 'Most people just ask vaguely'\n\n**The fix (8-17s):**\n- Show typing: 'You're a B2B SaaS marketer. Write a 600-word blog post for CFOs about reducing software spend. Use a conversational tone. Include 3 specific examples.'\n- ✅ Big green checkmark\n- Voiceover: 'Add role, audience, length, tone, examples'\n\n**📢 CTA (17-20s):**\n- Text: 'Save this! 💾'\n- 'Follow for more AI tips ✨'\n\n**🎵 Audio:** Trending tutorial-style sound\n\n**#️⃣ Hashtags:** #ChatGPT #AITips #Productivity #AIHacks #TechTips #ChatGPTTutorial",
        "chosen": "(Talking to camera, casual)\n\n'You're using ChatGPT wrong, but probably not for the reason you think.'\n\n'Everyone tells you to write better prompts. Sure. But here's the actual fix:'\n\n[Pulls up phone, types]\n\n'When ChatGPT gives you something mid, don't start over. Just reply 'this is too generic, get more specific' or 'this sounds like AI wrote it, make it sound human' — and watch what it does.'\n\n'Conversation, not commands. Like talking to a smart intern. The first answer is almost never the one you want.'"
    },
    {
        "context": "social_content", "topic_area": "youtube_description",
        "prompt": "Redraft this YouTube video description for a 20-minute ML tutorial. Original: 'In this video, I will teach you everything you need to know about transformers. We will cover the basics, the math, and a coding example. Make sure to like and subscribe!'",
        "rejected": "## Redrafted YouTube Description — Transformer Tutorial 🎥\n\n---\n\n🚀 **TRANSFORMERS EXPLAINED: From Zero to Coding Your First One!** 🚀\n\n📚 In this comprehensive 20-minute tutorial, you'll learn:\n- ✅ What transformers are and why they matter\n- ✅ The math behind attention mechanisms\n- ✅ How to code a transformer from scratch\n- ✅ Practical examples and use cases\n\n⏰ **Timestamps:**\n00:00 - Introduction\n02:30 - What is a transformer?\n05:00 - The attention mechanism\n10:00 - Math walkthrough\n14:00 - Coding example\n19:00 - Recap & next steps\n\n💻 **Resources:**\n- 📂 Code: github.com/.../...\n- 📖 Slides: bit.ly/...\n- 📚 Recommended reading: 'Attention Is All You Need'\n\n📌 **What you'll need:**\n- Basic Python\n- High school math\n- A coffee ☕\n\n🔔 **If this helped you:**\n- 👍 Like\n- 💬 Comment your questions\n- 🔔 Subscribe for more ML content\n- 🤝 Share with someone learning ML\n\n💖 Thanks for watching!\n\n**#️⃣ Tags:**\n#MachineLearning #Transformers #DeepLearning #NeuralNetworks #AI #PyTorch #MLTutorial #DataScience #Coding #Python",
        "chosen": "A 20-minute introduction to transformers, aimed at people who've done some ML but found the original paper hard to read. We start from why RNNs weren't cutting it, walk through attention conceptually before touching the math, and finish by coding up a small attention layer in PyTorch.\n\nTimestamps:\n00:00 — Why transformers happened\n02:30 — Attention, the intuition\n07:00 — Attention, the math\n12:00 — Coding it from scratch\n18:00 — Where this fits in the bigger picture\n\nCode and slides: github.com/[link]\n\nReading I'd recommend after this: the original 'Attention Is All You Need' paper, then Karpathy's 'Let's build GPT' video.\n\nQuestions in the comments — I read all of them."
    },
    {
        "context": "social_content", "topic_area": "linkedin_post",
        "prompt": "Write me a LinkedIn post sharing a thoughtful reflection after attending a conference (NeurIPS) — should not sound like every other 'grateful to be here' post.",
        "rejected": "## LinkedIn Conference Reflection Post — NeurIPS 🌟\n\n---\n\n🎉 **Just wrapped up NeurIPS 2025!** 🎉\n\nWhat an incredible week of learning, networking, and inspiration! 🤩\n\n**My top takeaways:**\n\n💡 **1. The pace of ML innovation is staggering**\nFrom multimodal models to RL breakthroughs, every session blew my mind.\n\n💡 **2. The community is so welcoming**\nMet brilliant researchers from around the world.\n\n💡 **3. Implementation matters as much as ideas**\nGreat papers + great engineering = breakthroughs.\n\n💡 **4. Diversity makes us stronger**\nLoved hearing perspectives from underrepresented groups.\n\n**Highlights:**\n- 🎤 Inspiring keynote by [Speaker]\n- 🤝 Networking lunch with industry leaders\n- 📊 Poster session full of innovation\n- 🍷 Reception with old and new friends\n\n**Massive thanks to:**\n- 🙏 The organizers for an amazing event\n- 🙏 My team for sending me\n- 🙏 The speakers who shared so generously\n- 🙏 Everyone I met for the great conversations\n\n**What's next:**\n- 📚 Reading the papers I missed\n- 💻 Implementing key ideas in our work\n- 🔬 Following up with new connections\n\nLooking forward to NeurIPS 2026! 🚀✨\n\n#NeurIPS #MachineLearning #AI #Networking #Research #DeepLearning #ConferenceReflections #Grateful",
        "chosen": "Back from NeurIPS. A few honest reactions instead of the usual highlights reel.\n\nThe most interesting work I saw was almost never in the headline talks. The plenary speakers were polished and largely focused on results we'd all already read about. The actual new ideas were tucked away in the poster sessions, where you could spend twenty minutes with the author of a paper that maybe sixty people read and walk away thinking about it for weeks.\n\nThe scale of the conference is overwhelming in a way that's both energizing and slightly disorienting. There's no way to actually 'do' NeurIPS — you can only do a small slice of it and make peace with the rest. I made the mistake of trying to optimize too hard on day one and was burnt out by day three.\n\nThe most valuable conversations were almost always at hallway distance from the official events. Lunch with two strangers I had nothing in common with academically turned into a forty-minute discussion of how to write a paper that people will actually read.\n\nNo profound takeaway. Just glad I went. Already thinking about what to submit next year."
    },
    {
        "context": "social_content", "topic_area": "instagram_caption",
        "prompt": "Write me an Instagram caption for a photo of dinner I cooked for my parents — first time cooking for them in months since I moved out.",
        "rejected": "## Instagram Caption — First Home-Cooked Meal for Parents 🍽️\n\n**Option 1 — Heartfelt:**\nThere's something special about cooking for the people who fed you your whole life 💛🍛 First meal back home in months and it tasted like everything I've missed. ✨\n\n**#️⃣ Hashtags:** #HomeCooked #FamilyTime #Foodie #Grateful #ParentsLove #HomeIsWhereTheHeartIs\n\n---\n\n**Option 2 — Reflective:**\nMoved out 6 months ago. Came back to cook for the people who cooked for me my entire life. The kitchen felt smaller, the food less perfect, but somehow it was the best meal I've made. 🥲💖\n\n**#️⃣ Hashtags:** #Family #FirstHomeCooking #ParentsAreEverything #Memories\n\n---\n\n**Option 3 — Casual:**\nFinally returned the favor 👩‍🍳❤️ It wasn't quite Amma's standard but they said it was great (parents are biased that way) 🍛✨\n\n**#️⃣ Hashtags:** #HomeCooking #FamilyDinner #DesiKitchen #FoodLove",
        "chosen": "First time cooking for my parents in eight months. They told me it was great, which is what they would have said either way."
    },
    {
        "context": "social_content", "topic_area": "linkedin_post",
        "prompt": "Help me write a LinkedIn post sharing a small mistake I made at work and what I learned — without it being one of those cringe 'I got fired and here's what success taught me' posts.",
        "rejected": "## LinkedIn Reflection Post — Lessons from a Mistake 💡\n\n---\n\n🎯 **Yesterday I made a mistake at work. Here's what I learned.** 🎯\n\nLast week, I [briefly describe mistake]. It was embarrassing, costly, and entirely my fault. 😅\n\n**What happened:**\n📌 I [action that led to mistake]\n📌 It [consequence]\n📌 I had to [resolution]\n\n**3 Lessons I'm taking with me:**\n\n🔑 **Lesson 1: Slow down to speed up**\nRushing led to the mistake. Quality > speed.\n\n🔑 **Lesson 2: Ask for a second pair of eyes**\nA peer review would have caught it.\n\n🔑 **Lesson 3: Own it fast**\nThe moment I admitted it, solutions appeared.\n\n**The real takeaway:**\nFailure isn't the opposite of success — it's part of it. 💎✨\n\n**Your turn:**\nWhat's a mistake that taught you something valuable? Share below 👇\n\n#GrowthMindset #LessonsLearned #Leadership #Vulnerability #ProfessionalDevelopment #CareerWisdom #Authenticity #SelfImprovement",
        "chosen": "Small thing from this week: I sent out a report with a chart that had the y-axis cut off, making a 2% difference look like a 20% one. Three people had reviewed it. None of us caught it. A stakeholder did, in a meeting, in front of everyone.\n\nThe useful lesson wasn't 'check your charts.' It was that I'd been treating chart review as a final polish step instead of a real verification step. The fix isn't a longer checklist; it's reviewing charts the way I review code — with someone whose actual job is to try to break it.\n\nNo arc of redemption. No 'and that's why failure is a gift.' Just a reminder that the small reviewable steps are reviewable for a reason."
    },

    # ============ EMAIL_DRAFT (12) ============
    # --- indian_corporate (4) ---
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email asking my college coordinator if I can change my elective choice for next semester — I want to switch from one I already opted for.",
        "rejected": "Subject: Request for Elective Change — Next Semester\n\nDear Sir/Madam,\n\nI hope you are doing well. I am writing to request a change in my elective for the upcoming semester.\n\n**Current elective:**\n- [Course code and name]\n\n**Requested elective:**\n- [Course code and name]\n\n**Reason for change:**\n- Better alignment with career interests\n- More relevant to thesis direction\n- Pre-requisites in line with my background\n\n**Implications:**\n- No conflict with timetable\n- Workload manageable\n- Both courses have available seats (to be confirmed)\n\n**Action requested:**\n- Approval for elective change\n- Update in academic records\n- Confirmation of new schedule\n\nKindly let me know if any additional documentation is required.\n\nWith regards,\n[Your Name]\n[Roll Number]",
        "chosen": "Subject: Request to change my elective for next semester\n\nDear Sir/Madam,\n\nI'd like to request a change in my elective for next semester — from [current course] to [new course]. The new course aligns much better with the direction I want my thesis to take, and there's no timetable conflict.\n\nPlease let me know if there's any documentation I need to submit.\n\nWith regards,\n[Your Name]\n[Roll Number]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email my reporting manager requesting permission to attend a 2-day technical training program scheduled during work hours — company sponsors most of the fees.",
        "rejected": "Subject: Request — Permission to Attend Technical Training Program\n\nDear [Manager],\n\nI hope you are well. I would like to request your permission to attend an upcoming technical training program.\n\n**Program details:**\n- **Title:** [Training program name]\n- **Dates:** [Date 1] and [Date 2]\n- **Duration:** 2 full working days\n- **Format:** [In-person / online]\n- **Total fees:** [Amount]\n- **Company-sponsored portion:** [Amount]\n- **Personal contribution:** [Amount]\n\n**Why I'd like to attend:**\n1. Directly relevant to [current project]\n2. Builds skills in [specific area]\n3. Will benefit team in upcoming work\n4. Aligns with my development plan\n\n**Coverage during my absence:**\n- Pending items will be wrapped before training\n- [Colleague] briefed for any urgent matters\n- Reachable on email for true emergencies\n\n**Post-training:**\n- Brief team on key learnings\n- Apply concepts to ongoing work\n- Available to discuss further\n\nKindly approve and let me know any next steps.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: Permission to attend a 2-day training program\n\nHi [Manager],\n\nThere's a 2-day technical training program on [dates] that I'd like to attend. It's directly relevant to the [project] work, and the company sponsors most of the fee. I'd take ownership of wrapping up open items before then and brief [colleague] for anything that might come up.\n\nHappy to share more details if helpful. Could you let me know if I'm clear to sign up?\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email my HR business partner requesting clarification on the new performance review process — it's confusing and I want to make sure I'm preparing correctly.",
        "rejected": "Subject: Clarification Needed — New Performance Review Process\n\nDear [HRBP Name],\n\nI hope you are doing well. I am writing to request clarification on certain aspects of the new performance review process.\n\n**Specific questions:**\n\n**1. Self-evaluation format:**\n- Are we to use the new template only?\n- Word limits or page limits?\n- Examples of past good self-evaluations available?\n\n**2. 360-degree feedback:**\n- How are feedback providers selected?\n- Anonymous or attributed?\n- Number of feedback providers expected?\n\n**3. Goal setting for next cycle:**\n- New format vs. old?\n- Required vs. optional sections?\n- Manager alignment required upfront?\n\n**4. Calibration timing:**\n- When does calibration happen?\n- Are individual outcomes visible before or after?\n\n**Why I'm asking:**\n- Want to prepare thoroughly\n- Avoid last-minute scramble\n- Make the process useful for my development\n\nWould appreciate either a written response or a brief call.\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Few questions about the new performance review process\n\nHi [HRBP Name],\n\nI'd appreciate some clarification on the new performance review process — a few things aren't clear and I want to prepare properly. Specifically: what's the expected format and length of the self-evaluation, how are 360-feedback providers selected (and is feedback anonymous?), and when does calibration actually happen relative to the rest of the process?\n\nHappy to get this over email or jump on a quick call — whichever is easier for you.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "indian_corporate",
        "prompt": "Email a vendor we've been working with for years thanking them for their support during a difficult quarter — without being over-the-top.",
        "rejected": "Subject: Appreciation — Your Outstanding Partnership This Quarter\n\nDear [Vendor Contact],\n\nI hope this email finds you and your team in good health and spirits. I am writing to formally express our gratitude for your exceptional support over the past quarter.\n\n**Context:**\nThis past quarter has been particularly challenging for our team due to:\n- 📈 Aggressive product launch timeline\n- 🔄 Unexpected scope expansion\n- 💻 Multiple system migrations\n- 👥 Team capacity constraints\n\n**Your contributions:**\n- ✅ Always responded within hours, often within minutes\n- ✅ Went above and beyond on multiple occasions\n- ✅ Flexible with scope adjustments\n- ✅ Solved problems we didn't even raise yet\n- ✅ Treated our team like extended family\n\n**Specific examples:**\n- [Example 1]\n- [Example 2]\n- [Example 3]\n\n**Looking forward:**\n- Even stronger partnership in Q[X]\n- Open to expanding scope\n- Will be advocating for you internally\n\nOur team is genuinely grateful for the partnership. Please pass our thanks to your entire team as well.\n\nWith warmest regards,\n[Your Name]\n[Company]",
        "chosen": "Subject: A real thank-you for this past quarter\n\nDear [Vendor Contact],\n\nA proper thank-you for your team's support this past quarter. It wasn't a normal one for us — too many things compressed into too short a window — and at multiple points your responsiveness is what kept us from missing commitments to our own customers.\n\nPlease pass our thanks to your team as well. Looking forward to working together in the next quarter.\n\nWith regards,\n[Your Name]\n[Company]"
    },
    # --- us_tech_casual (4) ---
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email asking my manager Alex if I can drop one of my current projects — I'm overcommitted and quality is suffering.",
        "rejected": "Subject: Conversation Needed — Project Load\n\nHi Alex,\n\nWanted to flag a real concern about my current project load:\n\n**Current commitments:**\n- 📊 Project A: [status]\n- 🔄 Project B: [status]\n- 🚀 Project C: [status]\n- 📈 Project D: [status]\n\n**The honest reality:**\n- I'm overcommitted\n- Quality is dropping across all of them\n- I'm working unsustainable hours just to keep up\n- Better to drop one well than fail all four\n\n**Proposal:**\n- Drop [Project X]\n- Reasons: lowest strategic value / can be reassigned\n- Implications: minimal — handover would be light\n\n**Alternative:**\n- Defer [Project Y] to next quarter\n- Maintains all current commitments\n- Reduces immediate pressure\n\n**What I need from you:**\n- Decision on which to drop / defer\n- Backing if stakeholders push back\n- Honest read on whether I'm reading this right\n\nLet's discuss in our next 1:1?\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Need to drop a project — let's talk?\n\nHi Alex,\n\nI'm overcommitted right now and the quality of my work is starting to suffer across the board. I'd rather flag it now than wait until something visibly breaks. I think the cleanest fix is dropping [project X] — it's the lowest-leverage one and the handover would be light.\n\nCan we make this our first topic in the next 1:1? Happy to talk through it sooner if needed.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email a coworker I haven't met yet (just joined the team) introducing myself, since we'll be working on the same project.",
        "rejected": "Subject: Hi from [Your Name] — Looking Forward to Working Together!\n\nHey [Coworker Name]!\n\nWelcome to the team! 🎉 So glad to have you onboard!\n\n**About me:**\n- 👋 Name: [Your Name]\n- 💻 Role: [Your role]\n- 📅 On the team: [Time]\n- 🎯 Currently focused on: [Areas]\n\n**My take on [Project]:**\n- We're at [stage]\n- Recent wins: [items]\n- Active challenges: [items]\n- My piece: [scope]\n\n**Suggested next steps:**\n- ☕ Coffee chat (in-person or virtual)?\n- 📅 30-min sync to align on project?\n- 📁 I can share docs/context?\n\n**My working style (FYI):**\n- Async-first communication\n- Slack > email for quick things\n- Heads-down mornings, meetings afternoons\n- Always open to feedback\n\nLet me know how you'd like to start. Excited to work together!\n\nCheers,\n[Your Name]",
        "chosen": "Subject: Hi! Looking forward to working together on [project]\n\nHey [Name],\n\nWelcome to the team. I'm [Your Name] — I'll be working with you on [project], so I figured a quick hello couldn't hurt.\n\nWant to grab a coffee (or coffee-on-video) sometime in your first couple of weeks? I'll fill you in on where things stand on our side of the work and answer whatever questions you've collected by then.\n\nNo rush — just ping me when you've got bandwidth.\n\nCheers,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email pushing back on a design review meeting that was scheduled with no agenda or pre-read — politely asking for context first.",
        "rejected": "Subject: Re: Design Review — Can We Get an Agenda First?\n\nHi [Organizer],\n\nThanks for sending the design review invite. Wanted to ask a quick question before the meeting:\n\n**What I'm missing:**\n- 📝 No agenda in the invite\n- 📄 No pre-read materials\n- 🎯 Unclear what we're reviewing or deciding\n\n**Why this matters:**\n- Effective design reviews need prep time\n- Reviewers can give better feedback with context\n- Cold reviews tend to be less productive\n- Respect for everyone's time on the call\n\n**Could you share:**\n- Brief agenda (even bullet points)\n- The design / docs we'll be reviewing\n- Specific decisions or feedback you want\n- Any constraints / context\n\n**Logistics:**\n- Happy to attend either way\n- Would just be more useful with prep\n- Even 24 hours notice helps\n\nLet me know!\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Re: design review — could you send context before the meeting?\n\nHi [Organizer],\n\nGot the invite for the design review, thanks. Could you send an agenda and any pre-read materials before then? I'd give much better feedback if I've had a chance to think about it rather than reacting cold on the call.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "us_tech_casual",
        "prompt": "Email a former coworker who I lost touch with — want to genuinely reconnect, not just network.",
        "rejected": "Subject: Long Time! How Are You?\n\nHey [Name]!\n\nIt's been a while — hope you're doing well! 😊\n\n**Quick update on me:**\n- 💼 Still at [Company] / Moved to [Company]\n- 🏠 Still in [City] / Moved to [City]\n- 📈 Working on [Project / direction]\n- ❤️ Personal life: [brief]\n\n**Wondering about you:**\n- What are you up to these days?\n- Still at [previous company]?\n- Any big life updates?\n\n**What I'm hoping for:**\n- Reconnect properly\n- Catch up on each other's lives\n- Maybe even grab coffee if you're nearby\n\n**Logistics:**\n- ☕ Coffee (in-person if same city)\n- 📞 Video call (if not)\n- 💬 Async chat if easier\n\nWould love to hear from you!\n\nWarm wishes,\n[Your Name]",
        "chosen": "Hey [Name],\n\nLong time. You popped into my head this morning and I realized it's been embarrassingly long since we talked. Wanted to actually reach out instead of just thinking about it again and doing nothing.\n\nHow've you been? Still in [City]? Would love a proper catch-up if you're up for it — happy with coffee, video call, or just an email thread.\n\nLet me know.\n[Your Name]"
    },
    # --- global_neutral (4) ---
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email a journal asking for a copy of the reviewer comments on a paper that was rejected last month — I want to use them to improve before resubmission.",
        "rejected": "Subject: Request — Copy of Reviewer Comments\n\nDear [Editor],\n\nI hope this email finds you well. I am writing to request a copy of the reviewer comments from a recent submission.\n\n**Submission details:**\n- **Manuscript title:** [Title]\n- **Manuscript ID:** [ID]\n- **Submission date:** [Date]\n- **Rejection date:** [Date, last month]\n\n**Why I'm requesting:**\n- Want to improve manuscript before resubmission\n- Reviewer feedback is most valuable input\n- Standard practice in our field\n\n**What I'm hoping for:**\n- Full reviewer comments (even if anonymized)\n- Editor's summary\n- Any specific guidance on improvements\n\n**My commitment:**\n- Substantial revisions before resubmission\n- Will address each comment specifically\n- May target another journal if direction misaligned\n\nThank you for your time.\n\nBest regards,\n[Your Name]\n[Affiliation]",
        "chosen": "Subject: Request for reviewer comments on manuscript [ID]\n\nDear [Editor],\n\nMy manuscript [ID, Title] was rejected last month. Would you be able to share the reviewer comments with me? I'd like to use them to substantially improve the paper before resubmitting elsewhere.\n\nThank you,\n[Your Name]\n[Affiliation]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email to a guest speaker thanking them after their talk at our event — should reference something specific from their talk, not be generic.",
        "rejected": "Subject: Thank You — A Wonderful Talk!\n\nDear [Speaker Name],\n\nOn behalf of [Organization / Event team], I wanted to express our sincere thanks for the wonderful talk you delivered at our event yesterday.\n\n**What stood out:**\n- 🌟 Your perspective on [topic]\n- 🌟 The specific example about [example]\n- 🌟 Your engagement with the audience during Q&A\n- 🌟 The way you handled the difficult question on [topic]\n\n**Impact:**\n- Multiple attendees expressed it was the highlight of the event\n- Several reached out asking for more resources\n- Generated rich discussion afterward\n\n**Practical follow-ups:**\n- Will share recording with attendees (with your permission)\n- Forwarding 3-4 thank you notes that came in\n- Following up on the action items you mentioned\n\n**Looking forward:**\n- Would love to have you back next year\n- Open to other collaboration opportunities\n- Will stay in touch\n\nThank you again for your time, energy, and generosity!\n\nWith deep gratitude,\n[Your Name]",
        "chosen": "Subject: Thank you — yesterday's talk was excellent\n\nDear [Speaker Name],\n\nA real thank-you for the talk yesterday. The point you made about [specific point from the talk] is the one I've kept thinking about since — several attendees mentioned the same in the feedback we collected afterwards. Your willingness to take the harder questions in Q&A was also genuinely appreciated; it set a different tone for the rest of the event.\n\nWe'd love to have you back next year if you're open to it. In the meantime, I'll send the recording over once it's processed (assuming you're comfortable with that).\n\nThanks again,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email asking a service provider to reduce our monthly subscription — usage has dropped and we'd like to downgrade to a lower tier.",
        "rejected": "Subject: Request — Subscription Downgrade\n\nDear [Provider Support],\n\nI hope this email finds you well. I am writing to request a downgrade of our current subscription plan.\n\n**Account details:**\n- **Company:** [Company]\n- **Account email:** [Email]\n- **Current plan:** [Plan name]\n- **Current monthly cost:** [Amount]\n\n**Reason for downgrade:**\n- Significant decrease in usage\n- Current plan provides more than we need\n- Looking to align cost with actual usage\n\n**Requested change:**\n- **Move to:** [Lower tier plan]\n- **New monthly cost:** [Amount]\n- **Effective from:** Next billing cycle\n\n**What we'd like to confirm:**\n- ✅ Process for downgrade\n- ✅ Any prorated refunds\n- ✅ Feature implications\n- ✅ Whether re-upgrade is straightforward\n\n**Open to:**\n- Custom plans if available\n- Annual commitments for further discount\n- Discussion of our needs in more detail\n\nThank you for your help.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Subscription downgrade request\n\nHi,\n\nOur usage has dropped significantly over the past few months and our current plan ([plan name]) is more than we need. Could you move us to [lower tier] starting from the next billing cycle?\n\nIf you have any prorating to do, please let me know. Account is under [account email].\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_draft", "register": "global_neutral",
        "prompt": "Email to a journal editor recommending a colleague as a peer reviewer for a topic the editor reached out about — keep it brief and substantive.",
        "rejected": "Subject: Reviewer Recommendation — [Topic]\n\nDear [Editor],\n\nThank you for reaching out about reviewer suggestions for [topic].\n\n**My recommendation:**\n\n**Name:** [Dr. Name]\n**Affiliation:** [University / Institute]\n**Email:** [Email]\n**Profile/Page:** [Link]\n\n**Why this person:**\n- 🎓 PhD in [relevant field] from [institution]\n- 🔬 Active research on [specific topic]\n- 📚 Recently published in [related journal]\n- ✅ Known for thorough, constructive reviews\n- ⏰ Generally responsive (~2-3 weeks turnaround)\n\n**Relevant work:**\n- [Paper 1] (recent)\n- [Paper 2]\n- [Paper 3]\n\n**Disclosure:**\n- We have collaborated on [X] but not in the last 3 years\n- No current shared projects\n- I am happy to be transparent about our prior connection\n\n**Alternative options:**\n- [Backup Name 1, Affiliation]\n- [Backup Name 2, Affiliation]\n\nThank you for considering. Happy to provide more context if useful.\n\nBest regards,\n[Your Name]",
        "chosen": "Subject: Re: reviewer suggestion for [topic]\n\nDear [Editor],\n\nI'd recommend Dr. [Name] at [Affiliation] — email [email]. Her recent work on [specific area] makes her well-placed to review this paper, and from prior experience she gives thorough and constructive reviews on a reasonable timeline.\n\nDisclosure: we co-authored a paper in [year], but we have not collaborated since.\n\nIf a backup is useful, Dr. [Name 2] at [Affiliation 2] would also be a strong fit.\n\nBest regards,\n[Your Name]"
    },

    # ============ EMAIL_REFINE (12) ============
    # --- indian_corporate (4) ---
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Polish this oddly stiff first email to a new client point of contact: 'Dear Mr. Joshi, I hope this email finds you in good health. I am writing to formally introduce myself as the new account manager for your account. I look forward to a fruitful and long-lasting business relationship with your esteemed organization.'",
        "rejected": "Here's a warmer, more professional version:\n\n**Subject:** Hello — Your New Account Manager from [Company]\n\n**Body:**\n\nHi Mr. Joshi,\n\nA quick intro from your new account manager.\n\n**About me:**\n- 👋 [Your Name], based out of [Location]\n- 💼 [X] years with [Company]\n- 🎯 Your dedicated point of contact going forward\n\n**My priorities:**\n- Smooth transition from previous account manager\n- Understanding your goals\n- Quick wins early on\n\n**Suggested next steps:**\n- 30-min intro call this week or next?\n- I review your account history beforehand\n- We align on priorities for the next quarter\n\n**Available:**\n- [Time slots]\n- Open to in-person if you're nearby\n\nLooking forward to working with you!\n\nBest,\n[Your Name]",
        "chosen": "Subject: Hello from your new account manager\n\nHi Mr. Joshi,\n\nQuick intro — I'm [Your Name], the new account manager for your account at [Company]. I'd love to set up a short intro call in the next couple of weeks so we can align on your priorities and what's most useful from me going forward.\n\nDoes any time next week work? Happy to fit your schedule.\n\nBest regards,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Refine this rambling team-update email that has the actual news buried in the middle: 'Hi team, hope your week is going well! As you all know we have been working very hard on the new product launch. There have been many ups and downs. I am happy to share that the launch date has been confirmed for next month on the 15th. There is still a lot of work to do. Please let me know if you have any questions.'",
        "rejected": "Here's a clearer version with the news up front:\n\n**Subject:** Confirmed Launch Date — 15th Next Month\n\n**Body:**\n\nHi team,\n\n**Headline:** The launch is confirmed for the 15th of next month.\n\n**What this means:**\n- ✅ Hard deadline locked in\n- 📅 ~4 weeks to launch\n- 🚀 All workstreams need to align\n\n**Remaining work (high level):**\n- [Item 1]\n- [Item 2]\n- [Item 3]\n\n**Next steps:**\n- Sync next week to walk through final plan\n- Push for blockers to be raised this week\n- Daily standup starting from week 3\n\n**Questions?**\n- Drop in this thread\n- Or grab time on my calendar\n\nThanks for the work you've put in so far. Big push coming.\n\n[Your Name]",
        "chosen": "Subject: Launch confirmed for the 15th of next month\n\nHi team,\n\nGood news — the launch date is confirmed for the 15th of next month. That gives us about four weeks, and there's still meaningful work to do across workstreams. I'll set up a sync next week to walk through the final plan and surface any blockers.\n\nThanks for the work that's gone in so far. Big push ahead.\n\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Polish this overly humble request for a salary advance: 'Respected Sir, I am writing with utmost humility to request a small salary advance of 50000 due to an unexpected medical emergency in my family. I will completely understand if this is not possible and I apologize for the trouble.'",
        "rejected": "Here's a clearer, more confident version:\n\n**Subject:** Request for Salary Advance — Family Medical Emergency\n\n**Body:**\n\nDear [Manager / HR],\n\nI'm writing to request a salary advance due to a family medical emergency.\n\n**Details:**\n- **Amount requested:** ₹50,000\n- **Reason:** Unexpected medical expense for family member\n- **Repayment:** Standard deduction from next 2-3 salary cycles\n\n**Why I'm asking:**\n- Funds needed within [timeframe]\n- All other options explored\n- Comfortable with company's advance policy\n\n**Documentation:**\n- Hospital records/bills available if required\n- Will follow standard process\n\nI'd appreciate your consideration. Available to discuss any details in person.\n\nWith regards,\n[Your Name]",
        "chosen": "Subject: Request for a salary advance — family medical emergency\n\nDear [Manager / HR],\n\nI'd like to request a salary advance of ₹50,000 due to an unexpected medical emergency in my family. I'm comfortable with the standard repayment structure being deducted from the next 2-3 salary cycles.\n\nHappy to share the required documentation and follow the proper process. Please let me know the next steps.\n\nWith regards,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "indian_corporate",
        "prompt": "Refine this confusing handover email to a colleague: 'Hi, as you may know I will be going on leave starting next week. I have many tasks that are pending and I am not sure how to handover all of them properly. Please can you help me figure out what to do with each one?'",
        "rejected": "Here's a clearer, more action-oriented version:\n\n**Subject:** Handover Help Needed — Going on Leave Next Week\n\n**Body:**\n\nHi [Colleague],\n\nGoing on leave starting next week and need your help on handover.\n\n**My pending items:**\n\n**Project A:**\n- Current status: [brief]\n- What's needed: [brief]\n- Who to ping: [name]\n\n**Project B:**\n- Current status: [brief]\n- What's needed: [brief]\n- Who to ping: [name]\n\n**Project C:**\n- Current status: [brief]\n- What's needed: [brief]\n- Who to ping: [name]\n\n**What I need from you:**\n- 30-min sync this week\n- We walk through each item together\n- Decide together who picks up what\n- Agree on emergency escalation\n\n**Logistics:**\n- Available [time windows]\n- Happy to write it up after\n- Will leave detailed docs in [location]\n\nThanks!\n[Your Name]",
        "chosen": "Subject: Could we sync on my handover before I'm out?\n\nHi [Colleague],\n\nI'm out starting next week and I have several pending items that I'm not sure how to hand over cleanly. Could we grab 30 minutes this week to walk through them together? I'd like to figure out who picks up what, rather than just dump everything on one person.\n\nI'm available [time windows]. I'll come prepared with the list and current status of each.\n\nThanks,\n[Your Name]"
    },
    # --- us_tech_casual (4) ---
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Polish this overly defensive reply to a code review with a lot of feedback: 'Hi, I got your review. I want to clarify that I made these design choices intentionally based on the requirements I was given. I think most of the feedback can be addressed in a follow-up PR. Let me know if you really need all of it in this one.'",
        "rejected": "Here's a more collaborative version:\n\n**Subject:** Re: Code Review — Thoughts on Your Feedback\n\n**Body:**\n\nHi [Reviewer],\n\nThanks for the thorough review. Wanted to share my thinking:\n\n**Where I agree:**\n- [Specific items where you'll address now]\n\n**Where I'd push back gently:**\n- [Specific items] — these were intentional design choices based on [requirements]\n- Happy to discuss if you see it differently\n\n**Proposed split:**\n- ✅ This PR: [items]\n- ⏳ Follow-up PR: [items]\n- ❓ Need alignment: [items]\n\n**Why split:**\n- This PR is already large\n- Follow-up keeps each change reviewable\n- Faster to merge core changes\n\n**Need from you:**\n- Confirm split is OK\n- Or flag what must be in this PR\n- Quick sync if easier\n\nLet me know how you'd like to proceed!\n\nThanks,\n[Your Name]",
        "chosen": "Hey [Reviewer],\n\nThanks for the thorough review. A few of the design choices you flagged were intentional based on the original requirements — happy to walk through my reasoning if it's useful. For the rest, my preference would be to address the smaller refactors in a follow-up PR so this one stays reviewable. Let me know which items you'd want in this PR specifically.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Tighten this hesitant email asking for visibility on something important: 'Hey, hope you're doing well. I was just wondering if maybe at some point I could possibly get some visibility into the strategic planning for next quarter? I think it would help me prioritize my work better but no rush at all if it's not the right time.'",
        "rejected": "Here's a more confident version:\n\n**Subject:** Visibility Request — Next Quarter Strategic Planning\n\n**Body:**\n\nHi [Manager],\n\nWanted to ask for some visibility into next quarter's strategic planning:\n\n**Why I'm asking:**\n- Helps me prioritize current work\n- Lets me prepare for any pivots\n- Better resource planning on my end\n\n**What level of visibility I'm looking for:**\n- Top 3-5 priorities for the org\n- Any major directional shifts\n- Areas I should be ready to support\n\n**Format:**\n- Brief written summary OR\n- 15 minutes in our next 1:1 OR\n- Whatever works for you\n\n**Timing:**\n- Ideally within next 2 weeks\n- Not blocking on it, but the sooner the better\n\nLet me know.\n\nThanks,\n[Your Name]",
        "chosen": "Hey [Manager],\n\nCould I get some visibility into the strategic planning for next quarter? Even a quick overview would help me prioritize my current work better and prepare for any pivots. Happy to discuss in our next 1:1, or get a written summary — whatever's easier for you.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Polish this slightly snippy email about a recurring blocker: 'Hey, this is the third time in 2 weeks I've been blocked on getting access to the database for analysis. Can we PLEASE just give the analytics team standing access already? This is wasting everyone's time.'",
        "rejected": "Here's a less snippy, more constructive version:\n\n**Subject:** Recurring Access Blocker — Worth Solving Structurally\n\n**Body:**\n\nHi [Name],\n\nWanted to raise a recurring issue:\n\n**The pattern:**\n- 3 times in 2 weeks: blocked on database access\n- Each time: filed ticket, waited 1-2 days, work paused\n- Net impact: ~5 days of lost analytics work\n\n**My suggestion:**\n- Provision standing read-only access for the analytics team\n- Audit logged, of course\n- Time-bounded if security prefers\n- Saves cycles for both teams\n\n**What this fixes:**\n- ✅ Eliminates ticket loop\n- ✅ Speeds up analytics work\n- ✅ Reduces admin overhead\n\n**Concerns to address:**\n- Security: read-only + logged should satisfy\n- Audit: standard practice in most orgs\n- Reversibility: easy to revoke if misused\n\nCould we discuss this week?\n\nThanks,\n[Your Name]",
        "chosen": "Subject: Recurring access blocker — worth solving structurally?\n\nHi [Name],\n\nI've been blocked on getting database access for analytics three times in the past two weeks. Each time the ticket gets sorted within a day or two, but it adds up to real lost time. Would it be possible to provision standing read-only access for the analytics team, with audit logging? Happy to talk through any security concerns.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "us_tech_casual",
        "prompt": "Refine this awkward email asking a peer to be a reference for me — we're friendly but haven't worked super closely: 'Hey, hope you're doing well! I'm in the middle of a job search and wanted to ask if you might be open to being a reference for me. I know we haven't worked together super closely but I really respect you and would value having you as a reference.'",
        "rejected": "Here's a more confident, clearer version:\n\n**Subject:** Could You Be a Reference for Me?\n\n**Body:**\n\nHey [Name],\n\nHope you're doing well — wanted to ask a quick favor.\n\n**The ask:**\n- I'm in the middle of a job search\n- Would you be open to being a reference?\n\n**Context:**\n- We've worked together on [briefly cite shared projects]\n- I respect your judgment and trust your perspective\n- Even occasional collaboration shows real character\n\n**What being a reference involves:**\n- 1-2 phone calls with potential employers\n- Each ~15-20 minutes\n- Standard questions about working style, strengths\n\n**Honest disclosure:**\n- Totally fine to say no\n- No hard feelings either way\n- Won't affect our relationship\n\n**If yes:**\n- I'll send you a heads up before each call\n- Provide context on the role\n- Share my updated resume\n\nLet me know either way!\n\nThanks,\n[Your Name]",
        "chosen": "Hey [Name],\n\nI'm in the middle of a job search and wanted to ask if you'd be open to being a reference for me. I know we haven't worked super closely, but your perspective on our [shared project / team] would actually be useful — you'd be speaking to a different angle than my direct manager would.\n\nTotally understand if it's not workable. If you are open to it, I'd give you a heads up before each call so you're not caught cold.\n\nThanks either way,\n[Your Name]"
    },
    # --- global_neutral (4) ---
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Polish this overly long client check-in email: 'Hi [Client], I just wanted to take a moment to reach out and check in on how things are going on your end. I know things have been busy and I want to make sure that we are continuing to provide value and that you are happy with everything. Please let me know if there is anything I can do or any feedback you have for us.'",
        "rejected": "Here's a tighter, more substantive version:\n\n**Subject:** Quick Check-in — How Are We Doing?\n\n**Body:**\n\nHi [Client],\n\nDoing a quick check-in.\n\n**What I want to know:**\n- 📊 Are we delivering the value you expected?\n- 🎯 Is the work we're doing aligned with your priorities?\n- 💬 Any feedback you've been holding?\n\n**Why I'm asking now:**\n- It's been [time] since our last check-in\n- I'd rather catch issues early\n- Better to ask than assume\n\n**Format:**\n- Quick written response works\n- 30-min call also fine\n- Async is great\n\nLooking forward to hearing from you.\n\nBest,\n[Your Name]",
        "chosen": "Subject: Quick check-in — how are we doing?\n\nHi [Client],\n\nWanted to check in. Are we still delivering the value you expected, and is anything not going as well as it should be? I'd rather hear concerns early than have them build up. A quick reply or a 30-minute call — whichever works.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Tighten this rambling cold email asking someone to be on a podcast: 'Hi, I really love your work and I have been following you for a long time. I run a podcast about [topic] and I think you would be an amazing guest. The format is usually about 45 minutes and we cover topics like [list of topics]. Would you be interested in being on the show?'",
        "rejected": "Here's a tighter version:\n\n**Subject:** Podcast Invite — [Topic] Show\n\n**Body:**\n\nHi [Name],\n\nLong-time admirer of your work. Reaching out with a podcast invite.\n\n**About the podcast:**\n- 🎙️ [Show name]\n- 📊 [Audience size / listenership]\n- 📅 [Frequency]\n- 🎯 Focus: [Topic]\n\n**Format:**\n- 45-minute conversation\n- Pre-recorded, lightly edited\n- Topics we'd love to cover with you: [list]\n\n**Why you'd be a great guest:**\n- Your work on [specific area]\n- Recent [specific thing they did]\n- Your perspective on [angle]\n\n**Logistics:**\n- We come prepared with questions and pre-read your work\n- You can suggest topics or off-limits areas\n- Light editing only\n\n**Next steps:**\n- Reply if interested\n- We schedule for next few weeks\n- Pre-call to align on topics\n\nWould love to have you!\n\n[Your Name]",
        "chosen": "Subject: Podcast invite — would love to have you on\n\nHi [Name],\n\nI've followed your work for a while and would love to have you as a guest on my podcast, [Show name]. It's a 45-minute conversation format focused on [topic], and I think a discussion with you on [specific angle from their work] would resonate strongly with the audience.\n\nWould you be open to it? If yes, I can send proposed topics and a few date options.\n\nThanks,\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Polish this slightly cold acceptance of an invitation: 'Hi, thank you for the invitation to the dinner next Friday. I will be attending. Please let me know if any additional information is required.'",
        "rejected": "Here's a warmer version:\n\n**Subject:** Re: Dinner Invitation — Looking Forward!\n\n**Body:**\n\nHi [Host],\n\nThanks for the invitation — happy to accept! 😊\n\n**Confirming:**\n- ✅ Date: Friday, [date]\n- ✅ Time: [time]\n- ✅ Location: [venue]\n- ✅ Attending: just me / +1\n\n**A few questions:**\n- Dress code?\n- Anything I should bring (wine, dessert)?\n- Dietary preferences I should communicate?\n\n**Looking forward to:**\n- Catching up with you\n- Meeting other guests\n- Great food and conversation\n\nSee you Friday!\n\n[Your Name]",
        "chosen": "Subject: Re: dinner invitation — happy to come\n\nHi [Host],\n\nThank you for the invitation — I'd love to come. Should I bring anything? Looking forward to it.\n\n[Your Name]"
    },
    {
        "context": "email_refine", "register": "global_neutral",
        "prompt": "Tighten this corporate-sounding intro to a community of practice: 'Hello, I would like to formally introduce myself to this community of practice. I am [name] from [company] and I am very excited to be joining this group. I look forward to learning from all of you and to making meaningful contributions to our shared body of knowledge.'",
        "rejected": "Here's a friendlier version:\n\n**Subject:** Hello — New Member Intro\n\n**Body:**\n\nHi all!\n\nNew member here. Quick intro:\n\n**About me:**\n- 👋 [Your Name]\n- 💼 [Role] at [Company]\n- 🌍 Based in [Location]\n- 📅 Been doing this work for [Time]\n\n**Why I joined:**\n- Want to learn from others in this space\n- Looking to contribute back\n- Heard great things about this community\n\n**What I'm working on right now:**\n- [Project 1]\n- [Area of interest]\n- [Specific challenge I'm trying to solve]\n\n**Where I might be useful:**\n- [Area of strength]\n- [Type of question I can help with]\n\nLooking forward to getting to know you all!\n\nBest,\n[Your Name]",
        "chosen": "Hi everyone,\n\nNew member here — [Your Name] from [Company]. I'm currently working on [specific project or area], and I joined this community because the conversations I've seen here are exactly the kind I've been missing. Looking forward to learning from you all and chipping in where I can.\n\n[Your Name]"
    },

    # ============ ACADEMIC_WRITING (4) ============
    {
        "context": "academic_writing", "topic_area": "introduction",
        "prompt": "Help me write the introduction paragraph for my undergraduate dissertation on consumer adoption of electric vehicles in India. About 200 words.",
        "rejected": "## Introduction Paragraph\n\n**The Context:**\nThe global transition toward electric vehicles (EVs) is one of the defining shifts of our generation — driven by climate concerns, regulatory pressure, and rapid technological progress.\n\n**India's Position:**\n- 🇮🇳 World's third-largest automobile market\n- 🌱 Significant pollution challenges in major cities\n- 📈 Government's aggressive EV adoption targets\n\n**The Challenge:**\nDespite this push, consumer adoption of EVs in India remains slow. Several factors contribute:\n\n- ❌ Range anxiety\n- ❌ Limited charging infrastructure\n- ❌ Higher upfront costs\n- ❌ Lack of awareness\n\n**What This Study Examines:**\nThis dissertation investigates the factors driving and hindering EV adoption among Indian consumers. The findings aim to inform both industry strategy and policy design.\n\n**Why It Matters:**\nUnderstanding consumer behavior is critical for achieving India's EV adoption goals — and the lessons may apply to other emerging markets.",
        "chosen": "The global shift toward electric vehicles represents one of the most significant transitions in the automotive industry in recent decades, driven by mounting environmental concerns, evolving regulatory frameworks, and rapid advances in battery technology. India, as the world's third-largest automobile market and a country facing severe urban air quality challenges, has positioned itself as a strategic participant in this transition through ambitious adoption targets and a range of supporting policy measures. Despite these efforts, consumer adoption of electric vehicles in India has remained modest, with passenger EV sales accounting for a small fraction of total automobile sales as of 2024. The reasons for this slow uptake are multiple and interrelated, ranging from concerns about driving range and charging infrastructure to the higher upfront cost of electric vehicles relative to conventional alternatives. The present dissertation investigates the factors that shape consumer decisions regarding electric vehicle adoption in India, with the aim of providing insights that may inform both industry strategy and the design of more effective policy interventions."
    },
    {
        "context": "academic_writing", "topic_area": "results",
        "prompt": "Polish this results section from a CS research paper on a new recommendation algorithm. The current version is too listy and needs to flow as prose.",
        "rejected": "## Results\n\n**Performance Overview:**\nOur proposed algorithm outperforms baseline methods on all key metrics — and demonstrates particular strength on cold-start scenarios.\n\n### Quantitative Results:\n\n**Hit Rate @10:**\n- Baseline (matrix factorization): 0.21\n- Baseline (neural CF): 0.27\n- **Ours: 0.34** ✅ (+26% over best baseline)\n\n**NDCG @10:**\n- MF: 0.18\n- NCF: 0.22\n- **Ours: 0.29** ✅ (+32% over best baseline)\n\n**Cold-start performance (new users):**\n- MF: degraded by 47%\n- NCF: degraded by 38%\n- **Ours: degraded by only 19%** ✅\n\n**Inference latency:**\n- MF: 15ms\n- NCF: 28ms\n- **Ours: 22ms** — slightly slower than MF but much faster than larger neural models\n\n### Qualitative Observations:\n- ✅ Better diversity in recommendations\n- ✅ Smoother degradation with sparse data\n- ✅ More interpretable user representations\n\n### Statistical Significance:\nAll improvements significant at p < 0.01.",
        "chosen": "The proposed algorithm achieved consistent improvements over both baseline methods across all evaluated metrics. On Hit Rate @10, the proposed method achieved 0.34, compared to 0.27 for the neural collaborative filtering baseline and 0.21 for matrix factorization, representing an improvement of 26 percent over the strongest baseline. A similar pattern was observed for NDCG @10, where the proposed method achieved 0.29 against 0.22 for neural collaborative filtering and 0.18 for matrix factorization, an improvement of 32 percent.\n\nThe most pronounced gains were observed in the cold-start setting. While matrix factorization and neural collaborative filtering exhibited performance degradations of 47 percent and 38 percent respectively when evaluated on new users, the proposed method degraded by only 19 percent under the same conditions. This finding is consistent with the design of the model, which incorporates auxiliary features explicitly for the purpose of handling sparse user histories.\n\nInference latency remained competitive. The proposed method achieved an average per-recommendation latency of 22 milliseconds, slightly higher than matrix factorization at 15 milliseconds but substantially lower than several larger neural architectures evaluated as additional baselines. Qualitative inspection of generated recommendations indicated greater diversity than both baselines, with no apparent loss in relevance. All reported improvements were statistically significant at p < 0.01."
    },
    {
        "context": "academic_writing", "topic_area": "abstract",
        "prompt": "Help me write an abstract for my honors thesis on the impact of code review practices on software defect rates. About 180 words.",
        "rejected": "## Abstract\n\n**Background:**\nCode review is a widely practiced quality assurance activity in software development. However, empirical evidence on its impact on defect rates is mixed.\n\n**Research Question:**\nDoes mandatory code review reduce post-deployment defect rates?\n\n**Methodology:**\n- 📊 Analyzed 2 years of commit and defect data\n- 📂 Across 5 open-source projects\n- 🔍 Compared periods with and without mandatory review\n- 📈 Used regression analysis with controls\n\n**Key Findings:**\n- ✅ Mandatory review reduced defects by 28% on average\n- ✅ Effect was stronger for changes touching critical modules\n- ✅ Smaller pull requests benefited more\n- ⚠️ Effect attenuated when reviewers were overloaded\n\n**Implications:**\n- 💡 Code review is effective when properly resourced\n- 💡 Reviewer load matters as much as policy\n- 💡 PR size affects review effectiveness\n\n**Keywords:** Code review, software defects, software engineering, empirical study",
        "chosen": "Code review is among the most widely practiced quality assurance activities in modern software development, yet empirical evidence regarding its actual impact on post-deployment defect rates remains mixed. This thesis investigates the relationship between mandatory code review practices and observed defect rates through an analysis of two years of commit and defect data drawn from five open-source projects. The analysis compared periods during which mandatory review was in place with those during which it was not, using regression methods that controlled for project characteristics, contributor experience, and change volume. The results suggest that mandatory code review is associated with a reduction in post-deployment defects of approximately 28 percent on average, with the effect being more pronounced for changes that touched critical modules. The benefits of review were found to be substantially greater for smaller pull requests, and to attenuate noticeably when reviewers were operating under high load. These findings indicate that code review is effective when adequately resourced, and that the size of changes submitted for review and the workload of reviewers are both meaningful moderating factors that warrant attention in software engineering practice.\n\nKeywords: code review; software defects; empirical software engineering; pull requests"
    },
    {
        "context": "academic_writing", "topic_area": "limitations",
        "prompt": "Help me write the 'limitations' section of my master's thesis on RL-based recommendation systems. Should acknowledge real limitations without being defeatist. About 200 words.",
        "rejected": "## Limitations\n\nThis study has several limitations that should be acknowledged:\n\n### 1. Dataset Limitations:\n- 📂 Single domain (e-commerce)\n- 📊 Synthetic user simulator\n- ⏰ 6-month observation window\n- ❌ No multi-platform data\n\n### 2. Methodological Limitations:\n- 🎯 Reward function relies on proxy signals\n- 🔄 Limited exploration of hyperparameters\n- 🤖 Single RL algorithm (PPO) tested\n- 📈 No comparison with newer methods (e.g., DPO)\n\n### 3. Evaluation Limitations:\n- 📊 Offline evaluation only\n- ❌ No A/B testing in production\n- 🎯 Limited fairness analysis\n- 🌍 Western consumer focus\n\n### 4. Generalizability:\n- ⚠️ Findings may not extend to other domains\n- ⚠️ Specific to chosen architecture\n- ⚠️ Sensitive to reward design choices\n\n### Mitigations:\n- ✅ Validated on held-out data\n- ✅ Robustness checks across hyperparameters\n- ✅ Future work outlined\n\n### Future Work:\nAddressing these limitations in subsequent research is critical for broader applicability.",
        "chosen": "Several limitations of the present study should be acknowledged. First, the analysis was conducted within a single domain, e-commerce recommendation, and the user interaction data was drawn from a six-month observation window on a single platform. The extent to which the findings generalize to other recommendation contexts, such as content streaming or news personalization, remains an open question. Second, evaluation was conducted in an offline setting using a simulator trained on historical interaction data. While this approach is standard in the recommendation systems literature, simulator-based evaluation cannot fully capture the dynamics of live deployment, where user behaviour adapts to the system itself over time. Third, the reward function used in this study relies on proxy signals such as clicks and dwell time, which are imperfect indicators of user satisfaction and may incentivize unintended behaviours. Fourth, the study evaluated a single reinforcement learning algorithm, PPO, and did not include systematic comparisons with more recent approaches such as DPO or other preference optimization methods. Finally, fairness considerations were addressed only in a limited manner; a more thorough analysis of how the proposed system affects recommendation diversity across user subgroups would be a valuable extension. These limitations point to clear directions for future work, several of which are discussed in the concluding chapter."
    },

    # ============ CONCEPT_EXPLAIN (3) ============
    {
        "context": "concept_explain", "topic_area": "ml",
        "prompt": "What's the difference between supervised fine-tuning (SFT) and RLHF? They both involve training on examples but the explanations I've read are confusing.",
        "rejected": "## SFT vs RLHF Explained 🤖\n\n### Core Distinction:\n- **SFT:** Learns to imitate good examples\n- **RLHF:** Learns from preference comparisons\n\n### Supervised Fine-Tuning (SFT):\n- 📚 **Data:** Pairs of (prompt, ideal response)\n- 🎯 **Objective:** Maximize likelihood of ideal responses\n- 💪 **Strength:** Simple, stable\n- 🔴 **Weakness:** Quality limited by demonstrations\n\n### RLHF:\n- 📚 **Data:** Pairs of (response A, response B, preference)\n- 🎯 **Objective:** Maximize reward model score (which approximates human preference)\n- 💪 **Strength:** Can exceed demonstration quality\n- 🔴 **Weakness:** Complex, reward hacking risks\n\n### Visual Pipeline:\n```\nSFT: Prompt + Ideal Response → MLE Training → Model\nRLHF: Pretrained Model → SFT → Reward Model → PPO → Aligned Model\n```\n\n### When to Use:\n| Goal | Pick |\n|------|------|\n| Teach a new format | SFT |\n| Align with preferences | RLHF |\n| Quick prototype | SFT |\n| Best possible alignment | RLHF |\n\n### Verdict:\nSFT teaches WHAT to say; RLHF teaches WHICH response is better!",
        "chosen": "The cleanest way to see the difference: SFT teaches the model to *imitate*, RLHF teaches it to *compare*.\n\nIn supervised fine-tuning, you give the model pairs of (prompt, ideal response). The model learns to produce outputs that look like the ideal responses you showed it. This is great for teaching format, style, or general behavior — for example, teaching a base language model to act like a chat assistant. The catch is that the model can only get as good as the demonstrations you provide. If your demonstrators are mediocre, your model will be too.\n\nRLHF works differently. Instead of giving the model ideal responses to imitate, you give it *preference pairs* — two different responses to the same prompt, with a human (or model) saying 'A is better than B.' The model learns from those comparisons. The interesting consequence is that the model can actually exceed the quality of any single demonstrator, because it's learning what makes one response better than another rather than copying any specific example.\n\nIn practice, modern LLMs use both. First, SFT teaches the base model the general format of being a helpful assistant. Then RLHF (or its cousin DPO, which you're using) refines the model on the harder, more nuanced preferences that are difficult to demonstrate directly — things like 'be helpful but not pushy,' or in your project's case, 'don't over-format casual responses.'\n\nThe one-line summary: SFT shows the model what to do; RLHF/DPO shows the model what's better."
    },
    {
        "context": "concept_explain", "topic_area": "devops",
        "prompt": "What's the difference between authentication and authorization? I always mix them up.",
        "rejected": "## Authentication vs Authorization 🔐\n\n### Quick Distinction:\n- **Authentication (AuthN):** Who are you?\n- **Authorization (AuthZ):** What are you allowed to do?\n\n### Authentication:\n- ✅ Proves identity\n- ✅ Usually happens first\n- 🔑 Examples: passwords, biometrics, OAuth login\n\n### Authorization:\n- ✅ Checks permissions\n- ✅ Happens after authentication\n- 🔑 Examples: role-based access, ACLs, token scopes\n\n### Real-World Analogy:\n- **AuthN:** Showing your ID at a building entrance\n- **AuthZ:** Your badge granting access to specific floors\n\n### Code-Level View:\n```\nLogin (AuthN) → Token issued → Each request checks AuthZ → Allowed/Denied\n```\n\n### Common Confusions:\n- 🔴 'Login' often involves both\n- 🔴 Same system frequently handles both\n- 🔴 Failures may look identical to user\n\n### Verdict:\nRemember: AuthN proves identity, AuthZ controls access!",
        "chosen": "Easiest way to remember: authentication is *who you are*, authorization is *what you're allowed to do*.\n\nThe analogy that always clicks: imagine going to a hotel. When you check in, the front desk asks for your ID and confirms you're the person whose reservation it is. That's authentication — proving identity. Once they've authenticated you, they hand you a key card. That key card only works on certain doors — your room, the gym, the pool, but not other guests' rooms or the staff areas. That's authorization — deciding what you can access.\n\nIn software, the same flow happens. You log in (authentication) — the system confirms you're really you, usually with a password or some other proof. Then for every action you try to take after that, the system checks whether *this user* is allowed to do *this thing* (authorization). Reading your own profile? Yes. Reading someone else's profile? Maybe not, depending on the rules.\n\nThe reason people mix them up is that they often happen together and use similar-sounding terminology (both abbreviated 'auth'). But they're distinct steps with distinct purposes. A common security mistake is conflating them — assuming that because someone is authenticated they must be authorized to do whatever they're asking. Modern systems treat them separately on purpose."
    },
    {
        "context": "concept_explain", "topic_area": "ml",
        "prompt": "What is a 'context window' in LLMs and why do people make such a big deal about it being large?",
        "rejected": "## Context Window in LLMs 📏\n\n### Definition:\nThe maximum amount of text (in tokens) that an LLM can process in a single input.\n\n### Why It Matters:\n- ✅ Determines how much context can be provided\n- ✅ Limits document length you can summarize\n- ✅ Constrains conversational memory\n- ✅ Affects RAG implementations\n\n### Size Examples:\n| Model | Context Window |\n|-------|----------------|\n| GPT-3.5 | 4K → 16K tokens |\n| GPT-4 | 8K → 128K tokens |\n| Claude 2 | 100K tokens |\n| Claude 3 | 200K tokens |\n| Gemini 1.5 | 1M+ tokens |\n\n### Tokens vs Words:\n- ~1 token = ~0.75 words (English)\n- 100K tokens ≈ ~75,000 words ≈ ~300 pages\n\n### Why Bigger Context Matters:\n- 📚 Whole books in one prompt\n- 💼 Entire codebases analyzed at once\n- 🗣️ Long conversations remembered\n- 🔄 Less reliance on retrieval (RAG)\n\n### Trade-offs:\n- 🔴 Bigger context = more compute = slower / pricier\n- 🔴 Some models still 'lose track' deep in long contexts\n- 🔴 Quality may degrade with extreme lengths\n\n### Verdict:\nLarger context = more capability, but at a real cost!",
        "chosen": "The context window is the maximum amount of text an LLM can 'see' at once when generating a response. It includes everything: your prompt, any documents you pasted in, the conversation history, and the answer it's producing. Once you fill up the window, older information gets pushed out.\n\nThink of it like the model's short-term memory. A model with a small context window is like talking to someone with very short-term memory — they can only consider the last few exchanges. A model with a large context window can look at hundreds of pages of material at once and reason across all of it.\n\nThis matters because so many real applications hinge on it. Want to summarize a long report? It has to fit in the context window. Want to have a long conversation where the model remembers things from earlier? Those earlier messages need to still be in the window. Want to analyze an entire codebase or feed in a book? Same constraint.\n\nThe progression has been dramatic. GPT-3 had a 4,000-token context window in 2022 — about 3,000 words, enough for a long email but not a paper. Modern models like Claude and Gemini now support hundreds of thousands or even millions of tokens — entire books, codebases, or hours of meeting transcripts in a single prompt.\n\nThe catch is that bigger context isn't free. It costs more to process, response times get slower, and models often have subtle quality degradation deep in very long contexts (a phenomenon called 'lost in the middle'). So just because a model *can* take a million tokens doesn't mean stuffing in a million is always the best use of it."
    },

    # ============ DECISION_ADVICE (3) ============
    {
        "context": "decision_advice", "topic_area": "career",
        "prompt": "Should I become a generalist software engineer or specialize in ML / AI given how hot the field is right now?",
        "rejected": "## Generalist SWE vs ML/AI Specialist 🛠️ vs 🤖\n\n### Quick Take:\nML hype is real but trade-offs matter.\n\n### Generalist SWE:\n\n**Pros:**\n- ✅ Broad demand across industries\n- ✅ Stable career path\n- ✅ Easier transitions between roles\n- ✅ Foundational skills age well\n\n**Cons:**\n- 🔴 Lower compensation ceiling\n- 🔴 Less hype-related opportunities\n- 🔴 Harder to differentiate\n\n### ML / AI Specialist:\n\n**Pros:**\n- ✅ Top compensation\n- ✅ Hot job market\n- ✅ Cutting-edge work\n- ✅ Strong investor / startup pull\n\n**Cons:**\n- 🔴 Hype-driven cycles\n- 🔴 Rapid technique churn\n- 🔴 Higher entry bar\n- 🔴 May commoditize over time\n\n### Decision Factors:\n| Factor | Generalist | ML Specialist |\n|--------|------------|---------------|\n| Stability | High | Moderate |\n| Comp ceiling | Moderate | High |\n| Hype risk | Low | High |\n| Learning curve | Standard | Steeper |\n| Transferability | Excellent | Specialized |\n\n### Verdict:\nGeneralist for stability, ML specialist for upside — at the cost of specialization risk!",
        "chosen": "Honest answer: chasing whatever's hot is a bad way to make this decision. The field's been around long enough now to see what happens to people who pick based on hype.\n\nFive years ago the same question was being asked about blockchain, then crypto, then AR/VR. People who specialized into those at the peak found the demand much smaller a few years later than the hype suggested. The people who quietly stayed strong software engineers were the ones who could move between trends.\n\nML is different in one important way: it's not going away. The applications are real and broad, not just speculative. So specializing into ML isn't the same kind of bet as specializing into crypto was. But there's still a real question about *what kind* of ML work you want to do, because 'ML' is now broad enough to encompass everything from data engineering to research scientists to ML infrastructure to applied ML at product companies.\n\nMy honest read: become a strong software engineer first, with real ML depth as a serious side specialty. Pure ML specialists who can't write production code struggle when the rubber hits the road; pure generalists who refuse to learn ML are increasingly missing out. The T-shape — strong generalist foundation with one deep area — is the most resilient path.\n\nWhat's drawing you toward ML specifically — the work itself, or the hype around it? That answer often clarifies the right move."
    },
    {
        "context": "decision_advice", "topic_area": "career",
        "prompt": "Should I take a job that pays more but feels less mission-aligned, or take a lower-paying job at a non-profit I care about?",
        "rejected": "## Higher Pay vs Mission Alignment 💰 vs 🌍\n\n### Quick Take:\nBoth choices are valid; depends on your life situation.\n\n### Higher Pay (Corporate):\n\n**Pros:**\n- ✅ Financial security\n- ✅ Save and invest more\n- ✅ Flexibility for life choices\n- ✅ Resume strength\n\n**Cons:**\n- 🔴 May feel unfulfilling\n- 🔴 'Golden handcuffs' risk\n- 🔴 Longer-term regret possible\n\n### Lower-Pay Mission:\n\n**Pros:**\n- ✅ Daily sense of purpose\n- ✅ Mission-driven colleagues\n- ✅ Often more impact\n- ✅ Better mental health (for many)\n\n**Cons:**\n- 🔴 Financial constraints\n- 🔴 Slower career growth (sometimes)\n- 🔴 Tougher economic environment\n\n### Decision Factors:\n| Factor | Corporate | Non-profit |\n|--------|-----------|------------|\n| Financial freedom | High | Limited |\n| Mission fit | Variable | Strong |\n| Career path | Clearer | Less defined |\n| Stress level | Variable | Variable |\n| Long-term satisfaction | Depends on you | Depends on you |\n\n### Verdict:\nIf finances allow, mission usually wins long-term. If finances are tight, corporate first, mission later!",
        "chosen": "There's no universal answer here, but the honest framing matters more than the dollar comparison.\n\nFirst, run the numbers. Not 'will I survive on the lower salary' but 'what does my life actually look like.' Can I still save? Can I afford to take risks later? Can I handle a sudden expense? If the lower salary makes you financially fragile, that's a real cost that will start to gnaw at you, regardless of how much you love the mission.\n\nSecond, be honest about how strong the mission pull actually is. Real mission alignment is different from 'this sounds important.' Real mission means: you'd genuinely think about this problem on weekends, you'd be excited to tell your friends what you do, you'd resent a job that paid more but pulled you away. If the mission isn't *that* strong for you, the lower salary will start to feel like a penalty rather than a trade.\n\nThird, watch out for the 'sacrifice today, optimize later' fantasy. People often plan to take the high-paying corporate job 'for a few years' and then switch to the mission work. Sometimes that works. But lifestyle creep is real — you'll likely adjust your spending to your salary, and the leap to a much lower paying role gets harder, not easier, over time.\n\nThe pattern I see hold up: take the mission job when the mission is genuinely strong AND you can afford it. Take the corporate job when finances genuinely require it, but be deliberate about not letting your lifestyle drift to the point you can't leave.\n\nWhat does the actual financial gap look like, and how strong is the mission pull for you?"
    },
    {
        "context": "decision_advice", "topic_area": "courses",
        "prompt": "Should I learn a foreign language seriously or invest the same time into more technical skills?",
        "rejected": "## Foreign Language vs Technical Skills 🌍 vs 💻\n\n### Quick Take:\nFor most career growth: technical. For life enrichment: language.\n\n### Technical Skills:\n- ✅ Direct career impact\n- ✅ Higher comp ceiling\n- ✅ Marketable globally\n- ✅ Compounds over time\n\n### Foreign Language:\n- ✅ Personal growth\n- ✅ Cultural enrichment\n- ✅ Travel + relationships\n- ✅ Cognitive benefits\n- ✅ Career boost in specific contexts\n\n### Time Investment:\n| Skill | Hours to Proficient |\n|-------|---------------------|\n| New programming language | 100–200 |\n| New ML technique | 50–100 |\n| Foreign language B2 | 600–1000 |\n\n### When Language Wins:\n- 🎯 Living abroad\n- 🎯 Targeted markets\n- 🎯 Personal interest\n- 🎯 Long-term commitment\n\n### When Technical Wins:\n- 💼 Career advancement\n- 💼 Time-constrained\n- 💼 ROI maximization\n\n### Verdict:\nFor career: technical. For life: language. Ideally do both, prioritized by life stage!",
        "chosen": "Depends entirely on what you're optimizing for. The framing matters more than the answer.\n\nLearning a foreign language seriously is a huge time investment — easily 600–1000 hours to reach a useful working level in most languages, more for the harder ones. That's an enormous amount of time. The honest career return is usually modest unless you're specifically planning to work in or with that language's region. So if you're framing this as 'what will pay off in my career?' technical skills are almost always the better bet hour for hour.\n\nWhere language wins: when you're optimizing for life and meaning rather than career. Speaking another language opens up a different culture, a different set of friendships, a different way of seeing the world that's genuinely transformative. People who've done it often describe it as one of the most enriching things they've done with their time — and that has its own value, even if it doesn't show up in your paycheck.\n\nThe useful question to ask yourself: which one will you regret not doing in twenty years? For some people, it's clearly the language — they imagine moving to a country, raising kids who speak it, building a life shaped by another culture. For others, it's the technical skill that would have unlocked a specific career path they care about. There's no universally right answer.\n\nThe trap to avoid: starting a language casually 'for the cognitive benefits' and putting in 50 hours over a year. You don't really get the benefits at that scale — you mostly get the frustration of being stuck at beginner level. Either commit seriously or pick something else.\n\nWhat would actually pull at you about learning the language — is it a specific country, culture, person, or just the general idea?"
    },

    # ============ SIMPLIFY_REQUEST (1) ============
    {
        "context": "simplify_request", "topic_area": "ml",
        "prompt": "Can you explain what 'cross-entropy loss' is to me really simply? I've seen the formula and it just looks like Greek letters.",
        "rejected": "## Cross-Entropy Loss — Really Simply 🎯\n\n**Quick definition:** Measures how 'wrong' a probability prediction is.\n\n### Simple Setup:\n- Model predicts a probability distribution over classes\n- True class is known\n- Cross-entropy measures distance between them\n\n### Intuition:\n- ✅ **Right & confident:** Tiny loss\n- ⚠️ **Right & uncertain:** Small loss\n- ❌ **Wrong & confident:** HUGE loss\n- ⚠️ **Wrong & uncertain:** Moderate loss\n\n### Mathematical View (Plain):\n- Take log of probability assigned to correct class\n- Negate it\n- That's the loss\n\n### Why Punish Confident Wrong Answers Hard:\n- ✅ Encourages calibration\n- ✅ Forces meaningful learning\n- ✅ Smooth gradient for optimization\n\n### Verdict:\nCross-entropy = standard loss for classification; punishes confident wrong predictions most!",
        "chosen": "Forget the formula. Here's the intuition.\n\nImagine you're a weather forecaster. Every day you have to give a probability that it'll rain — 90% chance, 30% chance, whatever. The next day, it either rains or it doesn't. You want a way to score how good your forecasts were over time.\n\nA naive score would just be 'were you right or wrong?' But that misses something important: a forecast of 51% rain that turned out right is barely better than a coin flip. A forecast of 99% rain that turned out right is much more impressive. The good score should reward confidence in correct predictions and punish confidence in wrong ones.\n\nCross-entropy loss is exactly that kind of score. When your model predicts a probability for what turns out to be the correct answer, cross-entropy says: 'if you were confident, great, low penalty; if you were uncertain, medium penalty; if you were confident in the *wrong* answer, huge penalty.'\n\nIn classification problems, this is the standard loss because it does the right thing: it encourages the model to be both accurate *and* calibrated in its confidence. Wild confidence in wrong answers gets punished hardest, which is exactly what you want — you don't want your spam filter being 99% sure that an obvious email from your boss is spam.\n\nThe scary-looking formula is just the math for computing this score across many predictions. The concept is just 'penalize confident mistakes more than uncertain ones, and reward confident correct answers most.'"
    },

    # ============ CASUAL_REPLY (1) ============
    {
        "context": "casual_reply",
        "prompt": "Reply to a friend's Slack: 'i'm thinking of quitting my job. talk me out of it?'",
        "rejected": "Here are some response options:\n\n**Curious / questioning:**\n- Why are you thinking about it? What's going on?\n\n**Half-joking:**\n- I will not. Tell me more first.\n\n**Empathic:**\n- That's a big thought. Want to grab coffee and talk?\n\n**Practical:**\n- Don't think I can talk you out of it without knowing more. What's the situation?\n\n**Best practice:**\n- Resist immediate advice\n- Ask what's behind it\n- Offer presence, not solutions",
        "chosen": "I will not, until I know why. What's going on? Coffee tomorrow?"
    },
]


def main() -> None:
    path = Path("data/formatting_pairs_v1.jsonl")
    assert path.exists()
    existing = set()
    with path.open() as f:
        for line in f:
            existing.add(json.loads(line)["prompt"])
    new = [r for r in ROWS if r["prompt"] not in existing]
    with path.open("a") as f:
        for row in new:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    counts = Counter()
    with path.open() as f:
        all_rows = [json.loads(line) for line in f]
    for r in all_rows:
        counts[r["context"]] += 1
    print(f"Appended: {len(new)} new (skipped {len(ROWS)-len(new)} dupes)")
    print(f"Total: {len(all_rows)}\n")
    for c, n in sorted(counts.items()):
        print(f"  {c:18} {n}")


if __name__ == "__main__":
    main()
